# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/agentversioninfo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ai/agentversioninfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import agentversionsummary_pb2 as ai_dot_agentversionsummary__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61i/agentversioninfo.proto\x12\x08nacos.ai\x1a\x1c\x61i/agentversionsummary.proto\"\xe2\x01\n\x10\x41gentVersionInfo\x12\x16\n\x0e\x65\x64itingVersion\x18\x01 \x01(\t\x12\x18\n\x10reviewingVersion\x18\x02 \x01(\t\x12\x35\n\x0eonlineVersions\x18\x03 \x03(\x0b\x32\x1d.nacos.ai.AgentVersionSummary\x12\x36\n\x06labels\x18\x04 \x03(\x0b\x32&.nacos.ai.AgentVersionInfo.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.agentversioninfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_AGENTVERSIONINFO_LABELSENTRY']._loaded_options = None
  _globals['_AGENTVERSIONINFO_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_AGENTVERSIONINFO']._serialized_start=70
  _globals['_AGENTVERSIONINFO']._serialized_end=296
  _globals['_AGENTVERSIONINFO_LABELSENTRY']._serialized_start=251
  _globals['_AGENTVERSIONINFO_LABELSENTRY']._serialized_end=296
# @@protoc_insertion_point(module_scope)
