# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/agentdiscoveryendpoint.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ai/agentdiscoveryendpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import runtimeversionbinding_pb2 as ai_dot_runtimeversionbinding__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61i/agentdiscoveryendpoint.proto\x12\x08nacos.ai\x1a\x1e\x61i/runtimeversionbinding.proto\"\x91\x02\n\x16\x41gentDiscoveryEndpoint\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x11\n\ttransport\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\x12\x0e\n\x06weight\x18\x04 \x01(\x01\x12@\n\x08metadata\x18\x05 \x03(\x0b\x32..nacos.ai.AgentDiscoveryEndpoint.MetadataEntry\x12\x0f\n\x07healthy\x18\x06 \x01(\x08\x12\x31\n\x08\x62indings\x18\x07 \x03(\x0b\x32\x1f.nacos.ai.RuntimeVersionBinding\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.agentdiscoveryendpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_AGENTDISCOVERYENDPOINT_METADATAENTRY']._loaded_options = None
  _globals['_AGENTDISCOVERYENDPOINT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AGENTDISCOVERYENDPOINT']._serialized_start=78
  _globals['_AGENTDISCOVERYENDPOINT']._serialized_end=351
  _globals['_AGENTDISCOVERYENDPOINT_METADATAENTRY']._serialized_start=304
  _globals['_AGENTDISCOVERYENDPOINT_METADATAENTRY']._serialized_end=351
# @@protoc_insertion_point(module_scope)
