# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/agentdiscoveryresult.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ai/agentdiscoveryresult.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import agentdiscoverycallinterface_pb2 as ai_dot_agentdiscoverycallinterface__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61i/agentdiscoveryresult.proto\x12\x08nacos.ai\x1a$ai/agentdiscoverycallinterface.proto\"\xa5\x01\n\x14\x41gentDiscoveryResult\x12\x13\n\x0bnamespaceId\x18\x01 \x01(\t\x12\x11\n\tagentName\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x15\n\rcontentDigest\x18\x04 \x01(\t\x12=\n\x0e\x63\x61llInterfaces\x18\x05 \x03(\x0b\x32%.nacos.ai.AgentDiscoveryCallInterfaceB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.agentdiscoveryresult_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_AGENTDISCOVERYRESULT']._serialized_start=82
  _globals['_AGENTDISCOVERYRESULT']._serialized_end=247
# @@protoc_insertion_point(module_scope)
