# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/agentcarddetailinfo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ai/agentcarddetailinfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import agentcapabilities_pb2 as ai_dot_agentcapabilities__pb2
from ai import agentinterface_pb2 as ai_dot_agentinterface__pb2
from ai import agentprovider_pb2 as ai_dot_agentprovider__pb2
from ai import agentskill_pb2 as ai_dot_agentskill__pb2
from ai import securityscheme_pb2 as ai_dot_securityscheme__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61i/agentcarddetailinfo.proto\x12\x08nacos.ai\x1a\x1a\x61i/agentcapabilities.proto\x1a\x17\x61i/agentinterface.proto\x1a\x16\x61i/agentprovider.proto\x1a\x13\x61i/agentskill.proto\x1a\x17\x61i/securityscheme.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfc\x06\n\x13\x41gentCardDetailInfo\x12\x17\n\x0fprotocolVersion\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0f\n\x07iconUrl\x18\x05 \x01(\t\x12\x31\n\x0c\x63\x61pabilities\x18\x06 \x01(\x0b\x32\x1b.nacos.ai.AgentCapabilities\x12$\n\x06skills\x18\x07 \x03(\x0b\x32\x14.nacos.ai.AgentSkill\x12\x0b\n\x03url\x18\x08 \x01(\t\x12\x1a\n\x12preferredTransport\x18\t \x01(\t\x12\x36\n\x14\x61\x64\x64itionalInterfaces\x18\n \x03(\x0b\x32\x18.nacos.ai.AgentInterface\x12\x35\n\x13supportedInterfaces\x18\x17 \x03(\x0b\x32\x18.nacos.ai.AgentInterface\x12,\n\x08provider\x18\x0b \x01(\x0b\x32\x1a.nacos.ai.A2aAgentProvider\x12\x18\n\x10\x64ocumentationUrl\x18\x0c \x01(\t\x12K\n\x0fsecuritySchemes\x18\r \x03(\x0b\x32\x32.nacos.ai.AgentCardDetailInfo.SecuritySchemesEntry\x12(\n\x08security\x18\x0e \x03(\x0b\x32\x16.google.protobuf.Value\x12\x34\n\x14securityRequirements\x18\x18 \x03(\x0b\x32\x16.google.protobuf.Value\x12\x19\n\x11\x64\x65\x66\x61ultInputModes\x18\x0f \x03(\t\x12\x1a\n\x12\x64\x65\x66\x61ultOutputModes\x18\x10 \x03(\t\x12)\n!supportsAuthenticatedExtendedCard\x18\x11 \x01(\x08\x12*\n\nsignatures\x18\x19 \x03(\x0b\x32\x16.google.protobuf.Value\x12\x18\n\x10registrationType\x18\x12 \x01(\t\x12\x15\n\rlatestVersion\x18\x13 \x01(\x08\x1aP\n\x14SecuritySchemesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.nacos.ai.SecurityScheme:\x02\x38\x01J\x04\x08\x14\x10\x15J\x04\x08\x15\x10\x16J\x04\x08\x16\x10\x17\x42.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.agentcarddetailinfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_AGENTCARDDETAILINFO_SECURITYSCHEMESENTRY']._loaded_options = None
  _globals['_AGENTCARDDETAILINFO_SECURITYSCHEMESENTRY']._serialized_options = b'8\001'
  _globals['_AGENTCARDDETAILINFO']._serialized_start=196
  _globals['_AGENTCARDDETAILINFO']._serialized_end=1088
  _globals['_AGENTCARDDETAILINFO_SECURITYSCHEMESENTRY']._serialized_start=990
  _globals['_AGENTCARDDETAILINFO_SECURITYSCHEMESENTRY']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
