# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/agentversiondetail.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ai/agentversiondetail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import agentcallinterface_pb2 as ai_dot_agentcallinterface__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61i/agentversiondetail.proto\x12\x08nacos.ai\x1a\x1b\x61i/agentcallinterface.proto\"\xfd\x01\n\x12\x41gentVersionDetail\x12\x13\n\x0bnamespaceId\x18\x01 \x01(\t\x12\x11\n\tagentName\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x34\n\x0e\x63\x61llInterfaces\x18\x05 \x03(\x0b\x32\x1c.nacos.ai.AgentCallInterface\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\x12\x19\n\x11\x63hangeDescription\x18\x07 \x01(\t\x12\x15\n\rcontentDigest\x18\x08 \x01(\t\x12\x12\n\ncreateTime\x18\t \x01(\x03\x12\x12\n\nupdateTime\x18\n \x01(\x03\x42.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.agentversiondetail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_AGENTVERSIONDETAIL']._serialized_start=71
  _globals['_AGENTVERSIONDETAIL']._serialized_end=324
# @@protoc_insertion_point(module_scope)
