# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/endpointset.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ai/endpointset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import endpoint_pb2 as ai_dot_endpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61i/endpointset.proto\x12\x08nacos.ai\x1a\x11\x61i/endpoint.proto\"\\\n\x0b\x45ndpointSet\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x16\n\x0esourceRevision\x18\x02 \x01(\t\x12%\n\tendpoints\x18\x03 \x03(\x0b\x32\x12.nacos.ai.EndpointB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.endpointset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_ENDPOINTSET']._serialized_start=53
  _globals['_ENDPOINTSET']._serialized_end=145
# @@protoc_insertion_point(module_scope)
