# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai/mcpserverremoteserviceconfig.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import frontendpointconfig_pb2 as ai_dot_frontendpointconfig__pb2
from ai import mcpserviceref_pb2 as ai_dot_mcpserviceref__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ai/mcpserverremoteserviceconfig.proto\x12\x08nacos.ai\x1a\x1c\x61i/frontendpointconfig.proto\x1a\x16\x61i/mcpserviceref.proto\"\x9f\x01\n\x1cMcpServerRemoteServiceConfig\x12+\n\nserviceRef\x18\x01 \x01(\x0b\x32\x17.nacos.ai.McpServiceRef\x12\x12\n\nexportPath\x18\x02 \x01(\t\x12>\n\x17\x66rontEndpointConfigList\x18\x03 \x03(\x0b\x32\x1d.nacos.ai.FrontEndpointConfigB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.mcpserverremoteserviceconfig_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_MCPSERVERREMOTESERVICECONFIG']._serialized_start=106
  _globals['_MCPSERVERREMOTESERVICECONFIG']._serialized_end=265
# @@protoc_insertion_point(module_scope)
