# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/mcpserverbasicinfo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ai/mcpserverbasicinfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import icon_pb2 as ai_dot_icon__pb2
from ai import mcpserverremoteserviceconfig_pb2 as ai_dot_mcpserverremoteserviceconfig__pb2
from ai import package_pb2 as ai_dot_package__pb2
from ai import repository_pb2 as ai_dot_repository__pb2
from ai import serverversiondetail_pb2 as ai_dot_serverversiondetail__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61i/mcpserverbasicinfo.proto\x12\x08nacos.ai\x1a\rai/icon.proto\x1a%ai/mcpserverremoteserviceconfig.proto\x1a\x10\x61i/package.proto\x1a\x13\x61i/repository.proto\x1a\x1c\x61i/serverversiondetail.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe7\x04\n\x12McpServerBasicInfo\x12\x13\n\x0bnamespaceId\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08protocol\x18\x04 \x01(\t\x12\x15\n\rfrontProtocol\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12(\n\nrepository\x18\x07 \x01(\x0b\x32\x14.nacos.ai.Repository\x12#\n\x08packages\x18\x08 \x03(\x0b\x32\x11.nacos.ai.Package\x12\x1d\n\x05icons\x18\t \x03(\x0b\x32\x0e.nacos.ai.Icon\x12\x12\n\nwebsiteUrl\x18\n \x01(\t\x12\x34\n\rversionDetail\x18\x0b \x01(\x0b\x32\x1d.nacos.ai.ServerVersionDetail\x12\x0f\n\x07version\x18\x0c \x01(\t\x12\x42\n\x12remoteServerConfig\x18\r \x01(\x0b\x32&.nacos.ai.McpServerRemoteServiceConfig\x12N\n\x11localServerConfig\x18\x0e \x03(\x0b\x32\x33.nacos.ai.McpServerBasicInfo.LocalServerConfigEntry\x12\x0f\n\x07\x65nabled\x18\x0f \x01(\x08\x12\x0e\n\x06status\x18\x10 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x11 \x03(\t\x1aP\n\x16LocalServerConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x42.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.mcpserverbasicinfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_MCPSERVERBASICINFO_LOCALSERVERCONFIGENTRY']._loaded_options = None
  _globals['_MCPSERVERBASICINFO_LOCALSERVERCONFIGENTRY']._serialized_options = b'8\001'
  _globals['_MCPSERVERBASICINFO']._serialized_start=195
  _globals['_MCPSERVERBASICINFO']._serialized_end=810
  _globals['_MCPSERVERBASICINFO_LOCALSERVERCONFIGENTRY']._serialized_start=730
  _globals['_MCPSERVERBASICINFO_LOCALSERVERCONFIGENTRY']._serialized_end=810
# @@protoc_insertion_point(module_scope)
