# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/mcptoolspecification.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ai/mcptoolspecification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import encryptobject_pb2 as ai_dot_encryptobject__pb2
from ai import mcptool_pb2 as ai_dot_mcptool__pb2
from ai import mcptoolmeta_pb2 as ai_dot_mcptoolmeta__pb2
from ai import securityscheme_pb2 as ai_dot_securityscheme__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61i/mcptoolspecification.proto\x12\x08nacos.ai\x1a\x16\x61i/encryptobject.proto\x1a\x10\x61i/mcptool.proto\x1a\x14\x61i/mcptoolmeta.proto\x1a\x17\x61i/securityscheme.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd1\x03\n\x14McpToolSpecification\x12\x19\n\x11specificationType\x18\x01 \x01(\t\x12,\n\x0b\x65ncryptData\x18\x02 \x01(\x0b\x32\x17.nacos.ai.EncryptObject\x12 \n\x05tools\x18\x03 \x03(\x0b\x32\x11.nacos.ai.McpTool\x12@\n\ttoolsMeta\x18\x04 \x03(\x0b\x32-.nacos.ai.McpToolSpecification.ToolsMetaEntry\x12\x34\n\x0fsecuritySchemes\x18\x05 \x03(\x0b\x32\x1b.nacos.ai.McpSecurityScheme\x12\x42\n\nextensions\x18\x06 \x03(\x0b\x32..nacos.ai.McpToolSpecification.ExtensionsEntry\x1aG\n\x0eToolsMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.nacos.ai.McpToolMeta:\x02\x38\x01\x1aI\n\x0f\x45xtensionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x42.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.mcptoolspecification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_MCPTOOLSPECIFICATION_TOOLSMETAENTRY']._loaded_options = None
  _globals['_MCPTOOLSPECIFICATION_TOOLSMETAENTRY']._serialized_options = b'8\001'
  _globals['_MCPTOOLSPECIFICATION_EXTENSIONSENTRY']._loaded_options = None
  _globals['_MCPTOOLSPECIFICATION_EXTENSIONSENTRY']._serialized_options = b'8\001'
  _globals['_MCPTOOLSPECIFICATION']._serialized_start=163
  _globals['_MCPTOOLSPECIFICATION']._serialized_end=628
  _globals['_MCPTOOLSPECIFICATION_TOOLSMETAENTRY']._serialized_start=482
  _globals['_MCPTOOLSPECIFICATION_TOOLSMETAENTRY']._serialized_end=553
  _globals['_MCPTOOLSPECIFICATION_EXTENSIONSENTRY']._serialized_start=555
  _globals['_MCPTOOLSPECIFICATION_EXTENSIONSENTRY']._serialized_end=628
# @@protoc_insertion_point(module_scope)
