# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai/prompt.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai import promptvariable_pb2 as ai_dot_promptvariable__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61i/prompt.proto\x12\x08nacos.ai\x1a\x17\x61i/promptvariable.proto\"x\n\x06Prompt\x12\x11\n\tpromptKey\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x10\n\x08template\x18\x03 \x01(\t\x12\x0b\n\x03md5\x18\x04 \x01(\t\x12+\n\tvariables\x18\x05 \x03(\x0b\x32\x18.nacos.ai.PromptVariableB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.prompt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nacos-group/nacos-sdk-proto/go/ai'
  _globals['_PROMPT']._serialized_start=54
  _globals['_PROMPT']._serialized_end=174
# @@protoc_insertion_point(module_scope)
