package com.alibaba.nacos.proto.generator;

import java.io.IOException;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

public class ProtoFileWriter {

    private static final Map<String, String> MODULE_PACKAGES = Map.of(
        "common", "nacos.common",
        "config", "nacos.config",
        "naming", "nacos.naming",
        "lock", "nacos.lock",
        "ai", "nacos.ai"
    );

    private String goModuleBase;

    public void setGoModuleBase(String goModuleBase) {
        this.goModuleBase = goModuleBase;
    }

    private final TypeMapper typeMapper = new TypeMapper();

    public void setClassToMessageName(Map<Class<?>, String> classToMessageName) {
        typeMapper.setClassToMessageName(classToMessageName);
    }

    public void setGenericMessageNames(Map<Type, String> genericMessageNames) {
        typeMapper.setGenericMessageNames(genericMessageNames);
    }

    public void write(Path outputDir, Map<String, List<MessageDescriptor>> messagesByFile) throws IOException {
        if (goModuleBase == null || goModuleBase.isEmpty()) {
            throw new IllegalStateException("goModuleBase must be set before writing proto files. Use --go-module-base CLI arg.");
        }
        // Build global map: message name -> file path
        Map<String, String> messageToFile = new HashMap<>();
        for (var entry : messagesByFile.entrySet()) {
            for (MessageDescriptor msg : entry.getValue()) {
                messageToFile.put(msg.name(), entry.getKey());
            }
        }

        for (var entry : messagesByFile.entrySet()) {
            String filePath = entry.getKey();
            List<MessageDescriptor> messages = entry.getValue();
            if (messages.isEmpty()) continue;

            String module = messages.get(0).module();
            Path outFile = outputDir.resolve(filePath);
            Files.createDirectories(outFile.getParent());

            StringBuilder sb = new StringBuilder();
            sb.append("// Auto-generated by proto-generator. DO NOT EDIT.\n");
            sb.append("syntax = \"proto3\";\n");
            sb.append("package ").append(MODULE_PACKAGES.getOrDefault(module, "nacos." + module)).append(";\n\n");
            sb.append("option go_package = \"")
              .append(goModuleBase).append("/").append(module)
              .append("\";\n");

            Set<String> imports = collectImports(messages, filePath, messageToFile);
            if (!imports.isEmpty()) {
                sb.append("\n");
                for (String imp : imports) {
                    sb.append("import \"").append(imp).append("\";\n");
                }
            }

            for (MessageDescriptor msg : messages) {
                sb.append("\n");
                sb.append("// metadata.type = \"").append(msg.name()).append("\"\n");
                sb.append("// Flattened from: ").append(msg.inheritanceChain()).append("\n");
                sb.append("message ").append(msg.name()).append(" {\n");

                for (FieldInfo field : msg.fields()) {
                    String protoType = typeMapper.mapType(field.type(), field.genericType());
                    int number = msg.fieldNumbers().get(field.name());
                    sb.append("  ").append(protoType).append(" ").append(field.name())
                      .append(" = ").append(number).append(";\n");
                }

                if (!msg.reserved().isEmpty()) {
                    sb.append("  reserved ").append(
                        msg.reserved().stream().map(String::valueOf).collect(Collectors.joining(", "))
                    ).append(";\n");
                }

                sb.append("}\n");
            }

            Files.writeString(outFile, sb.toString());
        }
    }

    private Set<String> collectImports(List<MessageDescriptor> messages, String currentFilePath,
            Map<String, String> messageToFile) {
        Set<String> imports = new TreeSet<>();
        // Collect message names defined in this file
        Set<String> localMessages = messages.stream()
            .map(MessageDescriptor::name)
            .collect(Collectors.toSet());

        for (MessageDescriptor msg : messages) {
            for (FieldInfo field : msg.fields()) {
                String protoType = typeMapper.mapType(field.type(), field.genericType());
                if (protoType.contains("google.protobuf.Value")) {
                    imports.add("google/protobuf/struct.proto");
                }

                // Check for cross-file message references
                Set<String> referencedTypes = extractReferencedTypes(field);
                for (String refType : referencedTypes) {
                    if (!localMessages.contains(refType) && messageToFile.containsKey(refType)) {
                        String refFile = messageToFile.get(refType);
                        if (!refFile.equals(currentFilePath)) {
                            imports.add(refFile);
                        }
                    }
                }
            }
        }
        return imports;
    }

    private Set<String> extractReferencedTypes(FieldInfo field) {
        Set<String> types = new HashSet<>();
        Class<?> fieldType = field.type();
        Type genericType = field.genericType();

        // Monomorphized generic instantiation (e.g. Page<McpTool> -> McpToolPage)
        String genericName = typeMapper.genericMessageName(genericType);
        if (genericName != null) {
            types.add(genericName);
            return types;
        }

        if (Collection.class.isAssignableFrom(fieldType) && genericType instanceof ParameterizedType pt) {
            Type elemType = pt.getActualTypeArguments()[0];
            if (elemType instanceof Class<?> cls && !cls.isPrimitive() && !cls.getName().startsWith("java.")) {
                types.add(cls.getSimpleName());
            }
        } else if (Map.class.isAssignableFrom(fieldType) && genericType instanceof ParameterizedType pt) {
            for (Type arg : pt.getActualTypeArguments()) {
                if (arg instanceof Class<?> cls && !cls.isPrimitive() && !cls.getName().startsWith("java.")) {
                    types.add(cls.getSimpleName());
                }
            }
        } else if (!fieldType.isPrimitive() && !fieldType.getName().startsWith("java.")
                   && !fieldType.isEnum() && fieldType != Object.class
                   && !java.io.Serializable.class.equals(fieldType)) {
            types.add(fieldType.getSimpleName());
        }
        return types;
    }
}
