// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/agentdiscoveryfilter.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentDiscoveryFilter"
// Flattened from: AgentDiscoveryFilter
type AgentDiscoveryFilter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Protocols        []string               `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
	ProtocolVersion  string                 `protobuf:"bytes,2,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	Transports       []string               `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	EndpointSources  []string               `protobuf:"bytes,4,rep,name=endpointSources,proto3" json:"endpointSources,omitempty"`
	MetadataSelector map[string]string      `protobuf:"bytes,5,rep,name=metadataSelector,proto3" json:"metadataSelector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentDiscoveryFilter) Reset() {
	*x = AgentDiscoveryFilter{}
	mi := &file_ai_agentdiscoveryfilter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDiscoveryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDiscoveryFilter) ProtoMessage() {}

func (x *AgentDiscoveryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agentdiscoveryfilter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDiscoveryFilter.ProtoReflect.Descriptor instead.
func (*AgentDiscoveryFilter) Descriptor() ([]byte, []int) {
	return file_ai_agentdiscoveryfilter_proto_rawDescGZIP(), []int{0}
}

func (x *AgentDiscoveryFilter) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *AgentDiscoveryFilter) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AgentDiscoveryFilter) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *AgentDiscoveryFilter) GetEndpointSources() []string {
	if x != nil {
		return x.EndpointSources
	}
	return nil
}

func (x *AgentDiscoveryFilter) GetMetadataSelector() map[string]string {
	if x != nil {
		return x.MetadataSelector
	}
	return nil
}

var File_ai_agentdiscoveryfilter_proto protoreflect.FileDescriptor

const file_ai_agentdiscoveryfilter_proto_rawDesc = "" +
	"\n" +
	"\x1dai/agentdiscoveryfilter.proto\x12\bnacos.ai\"\xcf\x02\n" +
	"\x14AgentDiscoveryFilter\x12\x1c\n" +
	"\tprotocols\x18\x01 \x03(\tR\tprotocols\x12(\n" +
	"\x0fprotocolVersion\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports\x12(\n" +
	"\x0fendpointSources\x18\x04 \x03(\tR\x0fendpointSources\x12`\n" +
	"\x10metadataSelector\x18\x05 \x03(\v24.nacos.ai.AgentDiscoveryFilter.MetadataSelectorEntryR\x10metadataSelector\x1aC\n" +
	"\x15MetadataSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_agentdiscoveryfilter_proto_rawDescOnce sync.Once
	file_ai_agentdiscoveryfilter_proto_rawDescData []byte
)

func file_ai_agentdiscoveryfilter_proto_rawDescGZIP() []byte {
	file_ai_agentdiscoveryfilter_proto_rawDescOnce.Do(func() {
		file_ai_agentdiscoveryfilter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agentdiscoveryfilter_proto_rawDesc), len(file_ai_agentdiscoveryfilter_proto_rawDesc)))
	})
	return file_ai_agentdiscoveryfilter_proto_rawDescData
}

var file_ai_agentdiscoveryfilter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_agentdiscoveryfilter_proto_goTypes = []any{
	(*AgentDiscoveryFilter)(nil), // 0: nacos.ai.AgentDiscoveryFilter
	nil,                          // 1: nacos.ai.AgentDiscoveryFilter.MetadataSelectorEntry
}
var file_ai_agentdiscoveryfilter_proto_depIdxs = []int32{
	1, // 0: nacos.ai.AgentDiscoveryFilter.metadataSelector:type_name -> nacos.ai.AgentDiscoveryFilter.MetadataSelectorEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_agentdiscoveryfilter_proto_init() }
func file_ai_agentdiscoveryfilter_proto_init() {
	if File_ai_agentdiscoveryfilter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agentdiscoveryfilter_proto_rawDesc), len(file_ai_agentdiscoveryfilter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_agentdiscoveryfilter_proto_goTypes,
		DependencyIndexes: file_ai_agentdiscoveryfilter_proto_depIdxs,
		MessageInfos:      file_ai_agentdiscoveryfilter_proto_msgTypes,
	}.Build()
	File_ai_agentdiscoveryfilter_proto = out.File
	file_ai_agentdiscoveryfilter_proto_goTypes = nil
	file_ai_agentdiscoveryfilter_proto_depIdxs = nil
}
