// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: ai/agentcallinterface.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentCallInterface"
// Flattened from: AgentCallInterface
type AgentCallInterface struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Protocol            string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ProtocolVersion     string                 `protobuf:"bytes,2,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	DescriptorMediaType string                 `protobuf:"bytes,3,opt,name=descriptorMediaType,proto3" json:"descriptorMediaType,omitempty"`
	NativeDescriptor    *structpb.Value        `protobuf:"bytes,4,opt,name=nativeDescriptor,proto3" json:"nativeDescriptor,omitempty"`
	EndpointSourceOrder []string               `protobuf:"bytes,5,rep,name=endpointSourceOrder,proto3" json:"endpointSourceOrder,omitempty"`
	DeclaredEndpoints   []*Endpoint            `protobuf:"bytes,6,rep,name=declaredEndpoints,proto3" json:"declaredEndpoints,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentCallInterface) Reset() {
	*x = AgentCallInterface{}
	mi := &file_ai_agentcallinterface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCallInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCallInterface) ProtoMessage() {}

func (x *AgentCallInterface) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agentcallinterface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCallInterface.ProtoReflect.Descriptor instead.
func (*AgentCallInterface) Descriptor() ([]byte, []int) {
	return file_ai_agentcallinterface_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCallInterface) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AgentCallInterface) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AgentCallInterface) GetDescriptorMediaType() string {
	if x != nil {
		return x.DescriptorMediaType
	}
	return ""
}

func (x *AgentCallInterface) GetNativeDescriptor() *structpb.Value {
	if x != nil {
		return x.NativeDescriptor
	}
	return nil
}

func (x *AgentCallInterface) GetEndpointSourceOrder() []string {
	if x != nil {
		return x.EndpointSourceOrder
	}
	return nil
}

func (x *AgentCallInterface) GetDeclaredEndpoints() []*Endpoint {
	if x != nil {
		return x.DeclaredEndpoints
	}
	return nil
}

var File_ai_agentcallinterface_proto protoreflect.FileDescriptor

const file_ai_agentcallinterface_proto_rawDesc = "" +
	"\n" +
	"\x1bai/agentcallinterface.proto\x12\bnacos.ai\x1a\x11ai/endpoint.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc4\x02\n" +
	"\x12AgentCallInterface\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12(\n" +
	"\x0fprotocolVersion\x18\x02 \x01(\tR\x0fprotocolVersion\x120\n" +
	"\x13descriptorMediaType\x18\x03 \x01(\tR\x13descriptorMediaType\x12B\n" +
	"\x10nativeDescriptor\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x10nativeDescriptor\x120\n" +
	"\x13endpointSourceOrder\x18\x05 \x03(\tR\x13endpointSourceOrder\x12@\n" +
	"\x11declaredEndpoints\x18\x06 \x03(\v2\x12.nacos.ai.EndpointR\x11declaredEndpointsB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_agentcallinterface_proto_rawDescOnce sync.Once
	file_ai_agentcallinterface_proto_rawDescData []byte
)

func file_ai_agentcallinterface_proto_rawDescGZIP() []byte {
	file_ai_agentcallinterface_proto_rawDescOnce.Do(func() {
		file_ai_agentcallinterface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agentcallinterface_proto_rawDesc), len(file_ai_agentcallinterface_proto_rawDesc)))
	})
	return file_ai_agentcallinterface_proto_rawDescData
}

var file_ai_agentcallinterface_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_agentcallinterface_proto_goTypes = []any{
	(*AgentCallInterface)(nil), // 0: nacos.ai.AgentCallInterface
	(*structpb.Value)(nil),     // 1: google.protobuf.Value
	(*Endpoint)(nil),           // 2: nacos.ai.Endpoint
}
var file_ai_agentcallinterface_proto_depIdxs = []int32{
	1, // 0: nacos.ai.AgentCallInterface.nativeDescriptor:type_name -> google.protobuf.Value
	2, // 1: nacos.ai.AgentCallInterface.declaredEndpoints:type_name -> nacos.ai.Endpoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_agentcallinterface_proto_init() }
func file_ai_agentcallinterface_proto_init() {
	if File_ai_agentcallinterface_proto != nil {
		return
	}
	file_ai_endpoint_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agentcallinterface_proto_rawDesc), len(file_ai_agentcallinterface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_agentcallinterface_proto_goTypes,
		DependencyIndexes: file_ai_agentcallinterface_proto_depIdxs,
		MessageInfos:      file_ai_agentcallinterface_proto_msgTypes,
	}.Build()
	File_ai_agentcallinterface_proto = out.File
	file_ai_agentcallinterface_proto_goTypes = nil
	file_ai_agentcallinterface_proto_depIdxs = nil
}
