// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/agentcatalogentry.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentCatalogEntry"
// Flattened from: AgentCatalogEntry
type AgentCatalogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agentName,proto3" json:"agentName,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	Provider      *AgentProvider         `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	LatestVersion string                 `protobuf:"bytes,7,opt,name=latestVersion,proto3" json:"latestVersion,omitempty"`
	Versions      []*AgentCatalogVersion `protobuf:"bytes,8,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCatalogEntry) Reset() {
	*x = AgentCatalogEntry{}
	mi := &file_ai_agentcatalogentry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCatalogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCatalogEntry) ProtoMessage() {}

func (x *AgentCatalogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agentcatalogentry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCatalogEntry.ProtoReflect.Descriptor instead.
func (*AgentCatalogEntry) Descriptor() ([]byte, []int) {
	return file_ai_agentcatalogentry_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCatalogEntry) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentCatalogEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentCatalogEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCatalogEntry) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *AgentCatalogEntry) GetProvider() *AgentProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *AgentCatalogEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentCatalogEntry) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *AgentCatalogEntry) GetVersions() []*AgentCatalogVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_ai_agentcatalogentry_proto protoreflect.FileDescriptor

const file_ai_agentcatalogentry_proto_rawDesc = "" +
	"\n" +
	"\x1aai/agentcatalogentry.proto\x12\bnacos.ai\x1a\x1cai/agentcatalogversion.proto\x1a\x16ai/agentprovider.proto\"\xb9\x02\n" +
	"\x11AgentCatalogEntry\x12\x1c\n" +
	"\tagentName\x18\x01 \x01(\tR\tagentName\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aiconUrl\x18\x04 \x01(\tR\aiconUrl\x123\n" +
	"\bprovider\x18\x05 \x01(\v2\x17.nacos.ai.AgentProviderR\bprovider\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12$\n" +
	"\rlatestVersion\x18\a \x01(\tR\rlatestVersion\x129\n" +
	"\bversions\x18\b \x03(\v2\x1d.nacos.ai.AgentCatalogVersionR\bversionsB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_agentcatalogentry_proto_rawDescOnce sync.Once
	file_ai_agentcatalogentry_proto_rawDescData []byte
)

func file_ai_agentcatalogentry_proto_rawDescGZIP() []byte {
	file_ai_agentcatalogentry_proto_rawDescOnce.Do(func() {
		file_ai_agentcatalogentry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agentcatalogentry_proto_rawDesc), len(file_ai_agentcatalogentry_proto_rawDesc)))
	})
	return file_ai_agentcatalogentry_proto_rawDescData
}

var file_ai_agentcatalogentry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_agentcatalogentry_proto_goTypes = []any{
	(*AgentCatalogEntry)(nil),   // 0: nacos.ai.AgentCatalogEntry
	(*AgentProvider)(nil),       // 1: nacos.ai.AgentProvider
	(*AgentCatalogVersion)(nil), // 2: nacos.ai.AgentCatalogVersion
}
var file_ai_agentcatalogentry_proto_depIdxs = []int32{
	1, // 0: nacos.ai.AgentCatalogEntry.provider:type_name -> nacos.ai.AgentProvider
	2, // 1: nacos.ai.AgentCatalogEntry.versions:type_name -> nacos.ai.AgentCatalogVersion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_agentcatalogentry_proto_init() }
func file_ai_agentcatalogentry_proto_init() {
	if File_ai_agentcatalogentry_proto != nil {
		return
	}
	file_ai_agentcatalogversion_proto_init()
	file_ai_agentprovider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agentcatalogentry_proto_rawDesc), len(file_ai_agentcatalogentry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_agentcatalogentry_proto_goTypes,
		DependencyIndexes: file_ai_agentcatalogentry_proto_depIdxs,
		MessageInfos:      file_ai_agentcatalogentry_proto_msgTypes,
	}.Build()
	File_ai_agentcatalogentry_proto = out.File
	file_ai_agentcatalogentry_proto_goTypes = nil
	file_ai_agentcatalogentry_proto_depIdxs = nil
}
