// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/agentdiscoveryendpoint.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentDiscoveryEndpoint"
// Flattened from: AgentDiscoveryEndpoint -> Endpoint
type AgentDiscoveryEndpoint struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Uri           string                   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Transport     string                   `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	Priority      int32                    `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        float64                  `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Metadata      map[string]string        `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Healthy       bool                     `protobuf:"varint,6,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Bindings      []*RuntimeVersionBinding `protobuf:"bytes,7,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDiscoveryEndpoint) Reset() {
	*x = AgentDiscoveryEndpoint{}
	mi := &file_ai_agentdiscoveryendpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDiscoveryEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDiscoveryEndpoint) ProtoMessage() {}

func (x *AgentDiscoveryEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agentdiscoveryendpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDiscoveryEndpoint.ProtoReflect.Descriptor instead.
func (*AgentDiscoveryEndpoint) Descriptor() ([]byte, []int) {
	return file_ai_agentdiscoveryendpoint_proto_rawDescGZIP(), []int{0}
}

func (x *AgentDiscoveryEndpoint) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *AgentDiscoveryEndpoint) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *AgentDiscoveryEndpoint) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AgentDiscoveryEndpoint) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AgentDiscoveryEndpoint) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentDiscoveryEndpoint) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *AgentDiscoveryEndpoint) GetBindings() []*RuntimeVersionBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

var File_ai_agentdiscoveryendpoint_proto protoreflect.FileDescriptor

const file_ai_agentdiscoveryendpoint_proto_rawDesc = "" +
	"\n" +
	"\x1fai/agentdiscoveryendpoint.proto\x12\bnacos.ai\x1a\x1eai/runtimeversionbinding.proto\"\xdc\x02\n" +
	"\x16AgentDiscoveryEndpoint\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..nacos.ai.AgentDiscoveryEndpoint.MetadataEntryR\bmetadata\x12\x18\n" +
	"\ahealthy\x18\x06 \x01(\bR\ahealthy\x12;\n" +
	"\bbindings\x18\a \x03(\v2\x1f.nacos.ai.RuntimeVersionBindingR\bbindings\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_agentdiscoveryendpoint_proto_rawDescOnce sync.Once
	file_ai_agentdiscoveryendpoint_proto_rawDescData []byte
)

func file_ai_agentdiscoveryendpoint_proto_rawDescGZIP() []byte {
	file_ai_agentdiscoveryendpoint_proto_rawDescOnce.Do(func() {
		file_ai_agentdiscoveryendpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agentdiscoveryendpoint_proto_rawDesc), len(file_ai_agentdiscoveryendpoint_proto_rawDesc)))
	})
	return file_ai_agentdiscoveryendpoint_proto_rawDescData
}

var file_ai_agentdiscoveryendpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_agentdiscoveryendpoint_proto_goTypes = []any{
	(*AgentDiscoveryEndpoint)(nil), // 0: nacos.ai.AgentDiscoveryEndpoint
	nil,                            // 1: nacos.ai.AgentDiscoveryEndpoint.MetadataEntry
	(*RuntimeVersionBinding)(nil),  // 2: nacos.ai.RuntimeVersionBinding
}
var file_ai_agentdiscoveryendpoint_proto_depIdxs = []int32{
	1, // 0: nacos.ai.AgentDiscoveryEndpoint.metadata:type_name -> nacos.ai.AgentDiscoveryEndpoint.MetadataEntry
	2, // 1: nacos.ai.AgentDiscoveryEndpoint.bindings:type_name -> nacos.ai.RuntimeVersionBinding
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_agentdiscoveryendpoint_proto_init() }
func file_ai_agentdiscoveryendpoint_proto_init() {
	if File_ai_agentdiscoveryendpoint_proto != nil {
		return
	}
	file_ai_runtimeversionbinding_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agentdiscoveryendpoint_proto_rawDesc), len(file_ai_agentdiscoveryendpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_agentdiscoveryendpoint_proto_goTypes,
		DependencyIndexes: file_ai_agentdiscoveryendpoint_proto_depIdxs,
		MessageInfos:      file_ai_agentdiscoveryendpoint_proto_msgTypes,
	}.Build()
	File_ai_agentdiscoveryendpoint_proto = out.File
	file_ai_agentdiscoveryendpoint_proto_goTypes = nil
	file_ai_agentdiscoveryendpoint_proto_depIdxs = nil
}
