// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: ai/agentversiondetail.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentVersionDetail"
// Flattened from: AgentVersionDetail
type AgentVersionDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId       string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	AgentName         string                 `protobuf:"bytes,2,opt,name=agentName,proto3" json:"agentName,omitempty"`
	Version           string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CallInterfaces    []*AgentCallInterface  `protobuf:"bytes,5,rep,name=callInterfaces,proto3" json:"callInterfaces,omitempty"`
	Author            string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	ChangeDescription string                 `protobuf:"bytes,7,opt,name=changeDescription,proto3" json:"changeDescription,omitempty"`
	ContentDigest     string                 `protobuf:"bytes,8,opt,name=contentDigest,proto3" json:"contentDigest,omitempty"`
	CreateTime        int64                  `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime        int64                  `protobuf:"varint,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentVersionDetail) Reset() {
	*x = AgentVersionDetail{}
	mi := &file_ai_agentversiondetail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentVersionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentVersionDetail) ProtoMessage() {}

func (x *AgentVersionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agentversiondetail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentVersionDetail.ProtoReflect.Descriptor instead.
func (*AgentVersionDetail) Descriptor() ([]byte, []int) {
	return file_ai_agentversiondetail_proto_rawDescGZIP(), []int{0}
}

func (x *AgentVersionDetail) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *AgentVersionDetail) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentVersionDetail) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentVersionDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentVersionDetail) GetCallInterfaces() []*AgentCallInterface {
	if x != nil {
		return x.CallInterfaces
	}
	return nil
}

func (x *AgentVersionDetail) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AgentVersionDetail) GetChangeDescription() string {
	if x != nil {
		return x.ChangeDescription
	}
	return ""
}

func (x *AgentVersionDetail) GetContentDigest() string {
	if x != nil {
		return x.ContentDigest
	}
	return ""
}

func (x *AgentVersionDetail) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AgentVersionDetail) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_ai_agentversiondetail_proto protoreflect.FileDescriptor

const file_ai_agentversiondetail_proto_rawDesc = "" +
	"\n" +
	"\x1bai/agentversiondetail.proto\x12\bnacos.ai\x1a\x1bai/agentcallinterface.proto\"\xf8\x02\n" +
	"\x12AgentVersionDetail\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tagentName\x18\x02 \x01(\tR\tagentName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12D\n" +
	"\x0ecallInterfaces\x18\x05 \x03(\v2\x1c.nacos.ai.AgentCallInterfaceR\x0ecallInterfaces\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12,\n" +
	"\x11changeDescription\x18\a \x01(\tR\x11changeDescription\x12$\n" +
	"\rcontentDigest\x18\b \x01(\tR\rcontentDigest\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\n" +
	" \x01(\x03R\n" +
	"updateTimeB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_agentversiondetail_proto_rawDescOnce sync.Once
	file_ai_agentversiondetail_proto_rawDescData []byte
)

func file_ai_agentversiondetail_proto_rawDescGZIP() []byte {
	file_ai_agentversiondetail_proto_rawDescOnce.Do(func() {
		file_ai_agentversiondetail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agentversiondetail_proto_rawDesc), len(file_ai_agentversiondetail_proto_rawDesc)))
	})
	return file_ai_agentversiondetail_proto_rawDescData
}

var file_ai_agentversiondetail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_agentversiondetail_proto_goTypes = []any{
	(*AgentVersionDetail)(nil), // 0: nacos.ai.AgentVersionDetail
	(*AgentCallInterface)(nil), // 1: nacos.ai.AgentCallInterface
}
var file_ai_agentversiondetail_proto_depIdxs = []int32{
	1, // 0: nacos.ai.AgentVersionDetail.callInterfaces:type_name -> nacos.ai.AgentCallInterface
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_agentversiondetail_proto_init() }
func file_ai_agentversiondetail_proto_init() {
	if File_ai_agentversiondetail_proto != nil {
		return
	}
	file_ai_agentcallinterface_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agentversiondetail_proto_rawDesc), len(file_ai_agentversiondetail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_agentversiondetail_proto_goTypes,
		DependencyIndexes: file_ai_agentversiondetail_proto_depIdxs,
		MessageInfos:      file_ai_agentversiondetail_proto_msgTypes,
	}.Build()
	File_ai_agentversiondetail_proto = out.File
	file_ai_agentversiondetail_proto_goTypes = nil
	file_ai_agentversiondetail_proto_depIdxs = nil
}
