// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/agentcatalogversion.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentCatalogVersion"
// Flattened from: AgentCatalogVersion
type AgentCatalogVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Protocols     []string               `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCatalogVersion) Reset() {
	*x = AgentCatalogVersion{}
	mi := &file_ai_agentcatalogversion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCatalogVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCatalogVersion) ProtoMessage() {}

func (x *AgentCatalogVersion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agentcatalogversion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCatalogVersion.ProtoReflect.Descriptor instead.
func (*AgentCatalogVersion) Descriptor() ([]byte, []int) {
	return file_ai_agentcatalogversion_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCatalogVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentCatalogVersion) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentCatalogVersion) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

var File_ai_agentcatalogversion_proto protoreflect.FileDescriptor

const file_ai_agentcatalogversion_proto_rawDesc = "" +
	"\n" +
	"\x1cai/agentcatalogversion.proto\x12\bnacos.ai\"e\n" +
	"\x13AgentCatalogVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12\x1c\n" +
	"\tprotocols\x18\x03 \x03(\tR\tprotocolsB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_agentcatalogversion_proto_rawDescOnce sync.Once
	file_ai_agentcatalogversion_proto_rawDescData []byte
)

func file_ai_agentcatalogversion_proto_rawDescGZIP() []byte {
	file_ai_agentcatalogversion_proto_rawDescOnce.Do(func() {
		file_ai_agentcatalogversion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agentcatalogversion_proto_rawDesc), len(file_ai_agentcatalogversion_proto_rawDesc)))
	})
	return file_ai_agentcatalogversion_proto_rawDescData
}

var file_ai_agentcatalogversion_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_agentcatalogversion_proto_goTypes = []any{
	(*AgentCatalogVersion)(nil), // 0: nacos.ai.AgentCatalogVersion
}
var file_ai_agentcatalogversion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_agentcatalogversion_proto_init() }
func file_ai_agentcatalogversion_proto_init() {
	if File_ai_agentcatalogversion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agentcatalogversion_proto_rawDesc), len(file_ai_agentcatalogversion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_agentcatalogversion_proto_goTypes,
		DependencyIndexes: file_ai_agentcatalogversion_proto_depIdxs,
		MessageInfos:      file_ai_agentcatalogversion_proto_msgTypes,
	}.Build()
	File_ai_agentcatalogversion_proto = out.File
	file_ai_agentcatalogversion_proto_goTypes = nil
	file_ai_agentcatalogversion_proto_depIdxs = nil
}
