// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/agentcapabilities.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentCapabilities"
// Flattened from: AgentCapabilities
type AgentCapabilities struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Streaming              bool                   `protobuf:"varint,1,opt,name=streaming,proto3" json:"streaming,omitempty"`
	PushNotifications      bool                   `protobuf:"varint,2,opt,name=pushNotifications,proto3" json:"pushNotifications,omitempty"`
	StateTransitionHistory bool                   `protobuf:"varint,3,opt,name=stateTransitionHistory,proto3" json:"stateTransitionHistory,omitempty"`
	ExtendedAgentCard      bool                   `protobuf:"varint,6,opt,name=extendedAgentCard,proto3" json:"extendedAgentCard,omitempty"`
	Extensions             []*AgentExtension      `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_ai_agentcapabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agentcapabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_ai_agentcapabilities_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCapabilities) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *AgentCapabilities) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *AgentCapabilities) GetStateTransitionHistory() bool {
	if x != nil {
		return x.StateTransitionHistory
	}
	return false
}

func (x *AgentCapabilities) GetExtendedAgentCard() bool {
	if x != nil {
		return x.ExtendedAgentCard
	}
	return false
}

func (x *AgentCapabilities) GetExtensions() []*AgentExtension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_ai_agentcapabilities_proto protoreflect.FileDescriptor

const file_ai_agentcapabilities_proto_rawDesc = "" +
	"\n" +
	"\x1aai/agentcapabilities.proto\x12\bnacos.ai\x1a\x17ai/agentextension.proto\"\x85\x02\n" +
	"\x11AgentCapabilities\x12\x1c\n" +
	"\tstreaming\x18\x01 \x01(\bR\tstreaming\x12,\n" +
	"\x11pushNotifications\x18\x02 \x01(\bR\x11pushNotifications\x126\n" +
	"\x16stateTransitionHistory\x18\x03 \x01(\bR\x16stateTransitionHistory\x12,\n" +
	"\x11extendedAgentCard\x18\x06 \x01(\bR\x11extendedAgentCard\x128\n" +
	"\n" +
	"extensions\x18\x04 \x03(\v2\x18.nacos.ai.AgentExtensionR\n" +
	"extensionsJ\x04\b\x05\x10\x06B.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_agentcapabilities_proto_rawDescOnce sync.Once
	file_ai_agentcapabilities_proto_rawDescData []byte
)

func file_ai_agentcapabilities_proto_rawDescGZIP() []byte {
	file_ai_agentcapabilities_proto_rawDescOnce.Do(func() {
		file_ai_agentcapabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agentcapabilities_proto_rawDesc), len(file_ai_agentcapabilities_proto_rawDesc)))
	})
	return file_ai_agentcapabilities_proto_rawDescData
}

var file_ai_agentcapabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_agentcapabilities_proto_goTypes = []any{
	(*AgentCapabilities)(nil), // 0: nacos.ai.AgentCapabilities
	(*AgentExtension)(nil),    // 1: nacos.ai.AgentExtension
}
var file_ai_agentcapabilities_proto_depIdxs = []int32{
	1, // 0: nacos.ai.AgentCapabilities.extensions:type_name -> nacos.ai.AgentExtension
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_agentcapabilities_proto_init() }
func file_ai_agentcapabilities_proto_init() {
	if File_ai_agentcapabilities_proto != nil {
		return
	}
	file_ai_agentextension_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agentcapabilities_proto_rawDesc), len(file_ai_agentcapabilities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_agentcapabilities_proto_goTypes,
		DependencyIndexes: file_ai_agentcapabilities_proto_depIdxs,
		MessageInfos:      file_ai_agentcapabilities_proto_msgTypes,
	}.Build()
	File_ai_agentcapabilities_proto = out.File
	file_ai_agentcapabilities_proto_goTypes = nil
	file_ai_agentcapabilities_proto_depIdxs = nil
}
