// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: ai/ai_response.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "AgentEndpointResponse"
// Flattened from: AgentEndpointResponse -> Response
type AgentEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEndpointResponse) Reset() {
	*x = AgentEndpointResponse{}
	mi := &file_ai_ai_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEndpointResponse) ProtoMessage() {}

func (x *AgentEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEndpointResponse.ProtoReflect.Descriptor instead.
func (*AgentEndpointResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_response_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEndpointResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *AgentEndpointResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *AgentEndpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentEndpointResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentEndpointResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// metadata.type = "McpServerEndpointResponse"
// Flattened from: McpServerEndpointResponse -> Response
type McpServerEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpServerEndpointResponse) Reset() {
	*x = McpServerEndpointResponse{}
	mi := &file_ai_ai_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpServerEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpServerEndpointResponse) ProtoMessage() {}

func (x *McpServerEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpServerEndpointResponse.ProtoReflect.Descriptor instead.
func (*McpServerEndpointResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_response_proto_rawDescGZIP(), []int{1}
}

func (x *McpServerEndpointResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *McpServerEndpointResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *McpServerEndpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *McpServerEndpointResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *McpServerEndpointResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// metadata.type = "QueryAgentCardResponse"
// Flattened from: QueryAgentCardResponse -> Response
type QueryAgentCardResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResultCode          int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode           int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message             string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId           string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	AgentCardDetailInfo *AgentCardDetailInfo   `protobuf:"bytes,5,opt,name=agentCardDetailInfo,proto3" json:"agentCardDetailInfo,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryAgentCardResponse) Reset() {
	*x = QueryAgentCardResponse{}
	mi := &file_ai_ai_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAgentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAgentCardResponse) ProtoMessage() {}

func (x *QueryAgentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAgentCardResponse.ProtoReflect.Descriptor instead.
func (*QueryAgentCardResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_response_proto_rawDescGZIP(), []int{2}
}

func (x *QueryAgentCardResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *QueryAgentCardResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *QueryAgentCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryAgentCardResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryAgentCardResponse) GetAgentCardDetailInfo() *AgentCardDetailInfo {
	if x != nil {
		return x.AgentCardDetailInfo
	}
	return nil
}

// metadata.type = "QueryMcpServerResponse"
// Flattened from: QueryMcpServerResponse -> Response
type QueryMcpServerResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResultCode          int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode           int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message             string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId           string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	McpServerDetailInfo *McpServerDetailInfo   `protobuf:"bytes,5,opt,name=mcpServerDetailInfo,proto3" json:"mcpServerDetailInfo,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryMcpServerResponse) Reset() {
	*x = QueryMcpServerResponse{}
	mi := &file_ai_ai_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMcpServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMcpServerResponse) ProtoMessage() {}

func (x *QueryMcpServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMcpServerResponse.ProtoReflect.Descriptor instead.
func (*QueryMcpServerResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_response_proto_rawDescGZIP(), []int{3}
}

func (x *QueryMcpServerResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *QueryMcpServerResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *QueryMcpServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryMcpServerResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryMcpServerResponse) GetMcpServerDetailInfo() *McpServerDetailInfo {
	if x != nil {
		return x.McpServerDetailInfo
	}
	return nil
}

// metadata.type = "QueryPromptResponse"
// Flattened from: QueryPromptResponse -> Response
type QueryPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	PromptInfo    *Prompt                `protobuf:"bytes,5,opt,name=promptInfo,proto3" json:"promptInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPromptResponse) Reset() {
	*x = QueryPromptResponse{}
	mi := &file_ai_ai_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPromptResponse) ProtoMessage() {}

func (x *QueryPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPromptResponse.ProtoReflect.Descriptor instead.
func (*QueryPromptResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_response_proto_rawDescGZIP(), []int{4}
}

func (x *QueryPromptResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *QueryPromptResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *QueryPromptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryPromptResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryPromptResponse) GetPromptInfo() *Prompt {
	if x != nil {
		return x.PromptInfo
	}
	return nil
}

// metadata.type = "ReleaseAgentCardResponse"
// Flattened from: ReleaseAgentCardResponse -> Response
type ReleaseAgentCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseAgentCardResponse) Reset() {
	*x = ReleaseAgentCardResponse{}
	mi := &file_ai_ai_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseAgentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseAgentCardResponse) ProtoMessage() {}

func (x *ReleaseAgentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseAgentCardResponse.ProtoReflect.Descriptor instead.
func (*ReleaseAgentCardResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_response_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseAgentCardResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ReleaseAgentCardResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ReleaseAgentCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReleaseAgentCardResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ReleaseMcpServerResponse"
// Flattened from: ReleaseMcpServerResponse -> Response
type ReleaseMcpServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	McpId         string                 `protobuf:"bytes,5,opt,name=mcpId,proto3" json:"mcpId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseMcpServerResponse) Reset() {
	*x = ReleaseMcpServerResponse{}
	mi := &file_ai_ai_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseMcpServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseMcpServerResponse) ProtoMessage() {}

func (x *ReleaseMcpServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseMcpServerResponse.ProtoReflect.Descriptor instead.
func (*ReleaseMcpServerResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_response_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseMcpServerResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ReleaseMcpServerResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ReleaseMcpServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReleaseMcpServerResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReleaseMcpServerResponse) GetMcpId() string {
	if x != nil {
		return x.McpId
	}
	return ""
}

var File_ai_ai_response_proto protoreflect.FileDescriptor

const file_ai_ai_response_proto_rawDesc = "" +
	"\n" +
	"\x14ai/ai_response.proto\x12\bnacos.ai\x1a\x1cai/agentcarddetailinfo.proto\x1a\x1cai/mcpserverdetailinfo.proto\x1a\x0fai/prompt.proto\"\xa1\x01\n" +
	"\x15AgentEndpointResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\xa5\x01\n" +
	"\x19McpServerEndpointResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\xdf\x01\n" +
	"\x16QueryAgentCardResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12O\n" +
	"\x13agentCardDetailInfo\x18\x05 \x01(\v2\x1d.nacos.ai.AgentCardDetailInfoR\x13agentCardDetailInfo\"\xdf\x01\n" +
	"\x16QueryMcpServerResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12O\n" +
	"\x13mcpServerDetailInfo\x18\x05 \x01(\v2\x1d.nacos.ai.McpServerDetailInfoR\x13mcpServerDetailInfo\"\xbd\x01\n" +
	"\x13QueryPromptResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x120\n" +
	"\n" +
	"promptInfo\x18\x05 \x01(\v2\x10.nacos.ai.PromptR\n" +
	"promptInfo\"\x90\x01\n" +
	"\x18ReleaseAgentCardResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\xa6\x01\n" +
	"\x18ReleaseMcpServerResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x14\n" +
	"\x05mcpId\x18\x05 \x01(\tR\x05mcpIdB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_ai_response_proto_rawDescOnce sync.Once
	file_ai_ai_response_proto_rawDescData []byte
)

func file_ai_ai_response_proto_rawDescGZIP() []byte {
	file_ai_ai_response_proto_rawDescOnce.Do(func() {
		file_ai_ai_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_ai_response_proto_rawDesc), len(file_ai_ai_response_proto_rawDesc)))
	})
	return file_ai_ai_response_proto_rawDescData
}

var file_ai_ai_response_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ai_ai_response_proto_goTypes = []any{
	(*AgentEndpointResponse)(nil),     // 0: nacos.ai.AgentEndpointResponse
	(*McpServerEndpointResponse)(nil), // 1: nacos.ai.McpServerEndpointResponse
	(*QueryAgentCardResponse)(nil),    // 2: nacos.ai.QueryAgentCardResponse
	(*QueryMcpServerResponse)(nil),    // 3: nacos.ai.QueryMcpServerResponse
	(*QueryPromptResponse)(nil),       // 4: nacos.ai.QueryPromptResponse
	(*ReleaseAgentCardResponse)(nil),  // 5: nacos.ai.ReleaseAgentCardResponse
	(*ReleaseMcpServerResponse)(nil),  // 6: nacos.ai.ReleaseMcpServerResponse
	(*AgentCardDetailInfo)(nil),       // 7: nacos.ai.AgentCardDetailInfo
	(*McpServerDetailInfo)(nil),       // 8: nacos.ai.McpServerDetailInfo
	(*Prompt)(nil),                    // 9: nacos.ai.Prompt
}
var file_ai_ai_response_proto_depIdxs = []int32{
	7, // 0: nacos.ai.QueryAgentCardResponse.agentCardDetailInfo:type_name -> nacos.ai.AgentCardDetailInfo
	8, // 1: nacos.ai.QueryMcpServerResponse.mcpServerDetailInfo:type_name -> nacos.ai.McpServerDetailInfo
	9, // 2: nacos.ai.QueryPromptResponse.promptInfo:type_name -> nacos.ai.Prompt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ai_ai_response_proto_init() }
func file_ai_ai_response_proto_init() {
	if File_ai_ai_response_proto != nil {
		return
	}
	file_ai_agentcarddetailinfo_proto_init()
	file_ai_mcpserverdetailinfo_proto_init()
	file_ai_prompt_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_ai_response_proto_rawDesc), len(file_ai_ai_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_ai_response_proto_goTypes,
		DependencyIndexes: file_ai_ai_response_proto_depIdxs,
		MessageInfos:      file_ai_ai_response_proto_msgTypes,
	}.Build()
	File_ai_ai_response_proto = out.File
	file_ai_ai_response_proto_goTypes = nil
	file_ai_ai_response_proto_depIdxs = nil
}
