// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: ai/mcpendpointspec.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "McpEndpointSpec"
// Flattened from: McpEndpointSpec
type McpEndpointSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpEndpointSpec) Reset() {
	*x = McpEndpointSpec{}
	mi := &file_ai_mcpendpointspec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpEndpointSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpEndpointSpec) ProtoMessage() {}

func (x *McpEndpointSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ai_mcpendpointspec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpEndpointSpec.ProtoReflect.Descriptor instead.
func (*McpEndpointSpec) Descriptor() ([]byte, []int) {
	return file_ai_mcpendpointspec_proto_rawDescGZIP(), []int{0}
}

func (x *McpEndpointSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *McpEndpointSpec) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ai_mcpendpointspec_proto protoreflect.FileDescriptor

const file_ai_mcpendpointspec_proto_rawDesc = "" +
	"\n" +
	"\x18ai/mcpendpointspec.proto\x12\bnacos.ai\"\x97\x01\n" +
	"\x0fMcpEndpointSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x127\n" +
	"\x04data\x18\x02 \x03(\v2#.nacos.ai.McpEndpointSpec.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_mcpendpointspec_proto_rawDescOnce sync.Once
	file_ai_mcpendpointspec_proto_rawDescData []byte
)

func file_ai_mcpendpointspec_proto_rawDescGZIP() []byte {
	file_ai_mcpendpointspec_proto_rawDescOnce.Do(func() {
		file_ai_mcpendpointspec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_mcpendpointspec_proto_rawDesc), len(file_ai_mcpendpointspec_proto_rawDesc)))
	})
	return file_ai_mcpendpointspec_proto_rawDescData
}

var file_ai_mcpendpointspec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_mcpendpointspec_proto_goTypes = []any{
	(*McpEndpointSpec)(nil), // 0: nacos.ai.McpEndpointSpec
	nil,                     // 1: nacos.ai.McpEndpointSpec.DataEntry
}
var file_ai_mcpendpointspec_proto_depIdxs = []int32{
	1, // 0: nacos.ai.McpEndpointSpec.data:type_name -> nacos.ai.McpEndpointSpec.DataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_mcpendpointspec_proto_init() }
func file_ai_mcpendpointspec_proto_init() {
	if File_ai_mcpendpointspec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_mcpendpointspec_proto_rawDesc), len(file_ai_mcpendpointspec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_mcpendpointspec_proto_goTypes,
		DependencyIndexes: file_ai_mcpendpointspec_proto_depIdxs,
		MessageInfos:      file_ai_mcpendpointspec_proto_msgTypes,
	}.Build()
	File_ai_mcpendpointspec_proto = out.File
	file_ai_mcpendpointspec_proto_goTypes = nil
	file_ai_mcpendpointspec_proto_depIdxs = nil
}
