// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: ai/mcpserviceref.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "McpServiceRef"
// Flattened from: McpServiceRef
type McpServiceRef struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId       string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName         string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName       string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	TransportProtocol string                 `protobuf:"bytes,4,opt,name=transportProtocol,proto3" json:"transportProtocol,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *McpServiceRef) Reset() {
	*x = McpServiceRef{}
	mi := &file_ai_mcpserviceref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpServiceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpServiceRef) ProtoMessage() {}

func (x *McpServiceRef) ProtoReflect() protoreflect.Message {
	mi := &file_ai_mcpserviceref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpServiceRef.ProtoReflect.Descriptor instead.
func (*McpServiceRef) Descriptor() ([]byte, []int) {
	return file_ai_mcpserviceref_proto_rawDescGZIP(), []int{0}
}

func (x *McpServiceRef) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *McpServiceRef) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *McpServiceRef) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *McpServiceRef) GetTransportProtocol() string {
	if x != nil {
		return x.TransportProtocol
	}
	return ""
}

var File_ai_mcpserviceref_proto protoreflect.FileDescriptor

const file_ai_mcpserviceref_proto_rawDesc = "" +
	"\n" +
	"\x16ai/mcpserviceref.proto\x12\bnacos.ai\"\x9f\x01\n" +
	"\rMcpServiceRef\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12,\n" +
	"\x11transportProtocol\x18\x04 \x01(\tR\x11transportProtocolB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_mcpserviceref_proto_rawDescOnce sync.Once
	file_ai_mcpserviceref_proto_rawDescData []byte
)

func file_ai_mcpserviceref_proto_rawDescGZIP() []byte {
	file_ai_mcpserviceref_proto_rawDescOnce.Do(func() {
		file_ai_mcpserviceref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_mcpserviceref_proto_rawDesc), len(file_ai_mcpserviceref_proto_rawDesc)))
	})
	return file_ai_mcpserviceref_proto_rawDescData
}

var file_ai_mcpserviceref_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_mcpserviceref_proto_goTypes = []any{
	(*McpServiceRef)(nil), // 0: nacos.ai.McpServiceRef
}
var file_ai_mcpserviceref_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_mcpserviceref_proto_init() }
func file_ai_mcpserviceref_proto_init() {
	if File_ai_mcpserviceref_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_mcpserviceref_proto_rawDesc), len(file_ai_mcpserviceref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_mcpserviceref_proto_goTypes,
		DependencyIndexes: file_ai_mcpserviceref_proto_depIdxs,
		MessageInfos:      file_ai_mcpserviceref_proto_msgTypes,
	}.Build()
	File_ai_mcpserviceref_proto = out.File
	file_ai_mcpserviceref_proto_goTypes = nil
	file_ai_mcpserviceref_proto_depIdxs = nil
}
