// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: ai/mcptoolspecification.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "McpToolSpecification"
// Flattened from: McpToolSpecification
type McpToolSpecification struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	SpecificationType string                     `protobuf:"bytes,1,opt,name=specificationType,proto3" json:"specificationType,omitempty"`
	EncryptData       *EncryptObject             `protobuf:"bytes,2,opt,name=encryptData,proto3" json:"encryptData,omitempty"`
	Tools             []*McpTool                 `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	ToolsMeta         map[string]*McpToolMeta    `protobuf:"bytes,4,rep,name=toolsMeta,proto3" json:"toolsMeta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SecuritySchemes   []*McpSecurityScheme       `protobuf:"bytes,5,rep,name=securitySchemes,proto3" json:"securitySchemes,omitempty"`
	Extensions        map[string]*structpb.Value `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *McpToolSpecification) Reset() {
	*x = McpToolSpecification{}
	mi := &file_ai_mcptoolspecification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpToolSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpToolSpecification) ProtoMessage() {}

func (x *McpToolSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_ai_mcptoolspecification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpToolSpecification.ProtoReflect.Descriptor instead.
func (*McpToolSpecification) Descriptor() ([]byte, []int) {
	return file_ai_mcptoolspecification_proto_rawDescGZIP(), []int{0}
}

func (x *McpToolSpecification) GetSpecificationType() string {
	if x != nil {
		return x.SpecificationType
	}
	return ""
}

func (x *McpToolSpecification) GetEncryptData() *EncryptObject {
	if x != nil {
		return x.EncryptData
	}
	return nil
}

func (x *McpToolSpecification) GetTools() []*McpTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *McpToolSpecification) GetToolsMeta() map[string]*McpToolMeta {
	if x != nil {
		return x.ToolsMeta
	}
	return nil
}

func (x *McpToolSpecification) GetSecuritySchemes() []*McpSecurityScheme {
	if x != nil {
		return x.SecuritySchemes
	}
	return nil
}

func (x *McpToolSpecification) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_ai_mcptoolspecification_proto protoreflect.FileDescriptor

const file_ai_mcptoolspecification_proto_rawDesc = "" +
	"\n" +
	"\x1dai/mcptoolspecification.proto\x12\bnacos.ai\x1a\x16ai/encryptobject.proto\x1a\x10ai/mcptool.proto\x1a\x14ai/mcptoolmeta.proto\x1a\x17ai/securityscheme.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb8\x04\n" +
	"\x14McpToolSpecification\x12,\n" +
	"\x11specificationType\x18\x01 \x01(\tR\x11specificationType\x129\n" +
	"\vencryptData\x18\x02 \x01(\v2\x17.nacos.ai.EncryptObjectR\vencryptData\x12'\n" +
	"\x05tools\x18\x03 \x03(\v2\x11.nacos.ai.McpToolR\x05tools\x12K\n" +
	"\ttoolsMeta\x18\x04 \x03(\v2-.nacos.ai.McpToolSpecification.ToolsMetaEntryR\ttoolsMeta\x12E\n" +
	"\x0fsecuritySchemes\x18\x05 \x03(\v2\x1b.nacos.ai.McpSecuritySchemeR\x0fsecuritySchemes\x12N\n" +
	"\n" +
	"extensions\x18\x06 \x03(\v2..nacos.ai.McpToolSpecification.ExtensionsEntryR\n" +
	"extensions\x1aS\n" +
	"\x0eToolsMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.nacos.ai.McpToolMetaR\x05value:\x028\x01\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_mcptoolspecification_proto_rawDescOnce sync.Once
	file_ai_mcptoolspecification_proto_rawDescData []byte
)

func file_ai_mcptoolspecification_proto_rawDescGZIP() []byte {
	file_ai_mcptoolspecification_proto_rawDescOnce.Do(func() {
		file_ai_mcptoolspecification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_mcptoolspecification_proto_rawDesc), len(file_ai_mcptoolspecification_proto_rawDesc)))
	})
	return file_ai_mcptoolspecification_proto_rawDescData
}

var file_ai_mcptoolspecification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ai_mcptoolspecification_proto_goTypes = []any{
	(*McpToolSpecification)(nil), // 0: nacos.ai.McpToolSpecification
	nil,                          // 1: nacos.ai.McpToolSpecification.ToolsMetaEntry
	nil,                          // 2: nacos.ai.McpToolSpecification.ExtensionsEntry
	(*EncryptObject)(nil),        // 3: nacos.ai.EncryptObject
	(*McpTool)(nil),              // 4: nacos.ai.McpTool
	(*McpSecurityScheme)(nil),    // 5: nacos.ai.McpSecurityScheme
	(*McpToolMeta)(nil),          // 6: nacos.ai.McpToolMeta
	(*structpb.Value)(nil),       // 7: google.protobuf.Value
}
var file_ai_mcptoolspecification_proto_depIdxs = []int32{
	3, // 0: nacos.ai.McpToolSpecification.encryptData:type_name -> nacos.ai.EncryptObject
	4, // 1: nacos.ai.McpToolSpecification.tools:type_name -> nacos.ai.McpTool
	1, // 2: nacos.ai.McpToolSpecification.toolsMeta:type_name -> nacos.ai.McpToolSpecification.ToolsMetaEntry
	5, // 3: nacos.ai.McpToolSpecification.securitySchemes:type_name -> nacos.ai.McpSecurityScheme
	2, // 4: nacos.ai.McpToolSpecification.extensions:type_name -> nacos.ai.McpToolSpecification.ExtensionsEntry
	6, // 5: nacos.ai.McpToolSpecification.ToolsMetaEntry.value:type_name -> nacos.ai.McpToolMeta
	7, // 6: nacos.ai.McpToolSpecification.ExtensionsEntry.value:type_name -> google.protobuf.Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ai_mcptoolspecification_proto_init() }
func file_ai_mcptoolspecification_proto_init() {
	if File_ai_mcptoolspecification_proto != nil {
		return
	}
	file_ai_encryptobject_proto_init()
	file_ai_mcptool_proto_init()
	file_ai_mcptoolmeta_proto_init()
	file_ai_securityscheme_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_mcptoolspecification_proto_rawDesc), len(file_ai_mcptoolspecification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_mcptoolspecification_proto_goTypes,
		DependencyIndexes: file_ai_mcptoolspecification_proto_depIdxs,
		MessageInfos:      file_ai_mcptoolspecification_proto_msgTypes,
	}.Build()
	File_ai_mcptoolspecification_proto = out.File
	file_ai_mcptoolspecification_proto_goTypes = nil
	file_ai_mcptoolspecification_proto_depIdxs = nil
}
