// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/mcptoolmeta.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "McpToolMeta"
// Flattened from: McpToolMeta
type McpToolMeta struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	InvokeContext map[string]string          `protobuf:"bytes,1,rep,name=invokeContext,proto3" json:"invokeContext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled       bool                       `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Templates     map[string]*structpb.Value `protobuf:"bytes,3,rep,name=templates,proto3" json:"templates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpToolMeta) Reset() {
	*x = McpToolMeta{}
	mi := &file_ai_mcptoolmeta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpToolMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpToolMeta) ProtoMessage() {}

func (x *McpToolMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ai_mcptoolmeta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpToolMeta.ProtoReflect.Descriptor instead.
func (*McpToolMeta) Descriptor() ([]byte, []int) {
	return file_ai_mcptoolmeta_proto_rawDescGZIP(), []int{0}
}

func (x *McpToolMeta) GetInvokeContext() map[string]string {
	if x != nil {
		return x.InvokeContext
	}
	return nil
}

func (x *McpToolMeta) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *McpToolMeta) GetTemplates() map[string]*structpb.Value {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_ai_mcptoolmeta_proto protoreflect.FileDescriptor

const file_ai_mcptoolmeta_proto_rawDesc = "" +
	"\n" +
	"\x14ai/mcptoolmeta.proto\x12\bnacos.ai\x1a\x1cgoogle/protobuf/struct.proto\"\xd3\x02\n" +
	"\vMcpToolMeta\x12N\n" +
	"\rinvokeContext\x18\x01 \x03(\v2(.nacos.ai.McpToolMeta.InvokeContextEntryR\rinvokeContext\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12B\n" +
	"\ttemplates\x18\x03 \x03(\v2$.nacos.ai.McpToolMeta.TemplatesEntryR\ttemplates\x1a@\n" +
	"\x12InvokeContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aT\n" +
	"\x0eTemplatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_mcptoolmeta_proto_rawDescOnce sync.Once
	file_ai_mcptoolmeta_proto_rawDescData []byte
)

func file_ai_mcptoolmeta_proto_rawDescGZIP() []byte {
	file_ai_mcptoolmeta_proto_rawDescOnce.Do(func() {
		file_ai_mcptoolmeta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_mcptoolmeta_proto_rawDesc), len(file_ai_mcptoolmeta_proto_rawDesc)))
	})
	return file_ai_mcptoolmeta_proto_rawDescData
}

var file_ai_mcptoolmeta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ai_mcptoolmeta_proto_goTypes = []any{
	(*McpToolMeta)(nil),    // 0: nacos.ai.McpToolMeta
	nil,                    // 1: nacos.ai.McpToolMeta.InvokeContextEntry
	nil,                    // 2: nacos.ai.McpToolMeta.TemplatesEntry
	(*structpb.Value)(nil), // 3: google.protobuf.Value
}
var file_ai_mcptoolmeta_proto_depIdxs = []int32{
	1, // 0: nacos.ai.McpToolMeta.invokeContext:type_name -> nacos.ai.McpToolMeta.InvokeContextEntry
	2, // 1: nacos.ai.McpToolMeta.templates:type_name -> nacos.ai.McpToolMeta.TemplatesEntry
	3, // 2: nacos.ai.McpToolMeta.TemplatesEntry.value:type_name -> google.protobuf.Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ai_mcptoolmeta_proto_init() }
func file_ai_mcptoolmeta_proto_init() {
	if File_ai_mcptoolmeta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_mcptoolmeta_proto_rawDesc), len(file_ai_mcptoolmeta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_mcptoolmeta_proto_goTypes,
		DependencyIndexes: file_ai_mcptoolmeta_proto_depIdxs,
		MessageInfos:      file_ai_mcptoolmeta_proto_msgTypes,
	}.Build()
	File_ai_mcptoolmeta_proto = out.File
	file_ai_mcptoolmeta_proto_goTypes = nil
	file_ai_mcptoolmeta_proto_depIdxs = nil
}
