// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: ai/prompt.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "Prompt"
// Flattened from: Prompt
type Prompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromptKey     string                 `protobuf:"bytes,1,opt,name=promptKey,proto3" json:"promptKey,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Template      string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Md5           string                 `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`
	Variables     []*PromptVariable      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	mi := &file_ai_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_ai_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_ai_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *Prompt) GetPromptKey() string {
	if x != nil {
		return x.PromptKey
	}
	return ""
}

func (x *Prompt) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Prompt) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Prompt) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *Prompt) GetVariables() []*PromptVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

var File_ai_prompt_proto protoreflect.FileDescriptor

const file_ai_prompt_proto_rawDesc = "" +
	"\n" +
	"\x0fai/prompt.proto\x12\bnacos.ai\x1a\x17ai/promptvariable.proto\"\xa6\x01\n" +
	"\x06Prompt\x12\x1c\n" +
	"\tpromptKey\x18\x01 \x01(\tR\tpromptKey\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12\x10\n" +
	"\x03md5\x18\x04 \x01(\tR\x03md5\x126\n" +
	"\tvariables\x18\x05 \x03(\v2\x18.nacos.ai.PromptVariableR\tvariablesB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_prompt_proto_rawDescOnce sync.Once
	file_ai_prompt_proto_rawDescData []byte
)

func file_ai_prompt_proto_rawDescGZIP() []byte {
	file_ai_prompt_proto_rawDescOnce.Do(func() {
		file_ai_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_prompt_proto_rawDesc), len(file_ai_prompt_proto_rawDesc)))
	})
	return file_ai_prompt_proto_rawDescData
}

var file_ai_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_prompt_proto_goTypes = []any{
	(*Prompt)(nil),         // 0: nacos.ai.Prompt
	(*PromptVariable)(nil), // 1: nacos.ai.PromptVariable
}
var file_ai_prompt_proto_depIdxs = []int32{
	1, // 0: nacos.ai.Prompt.variables:type_name -> nacos.ai.PromptVariable
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_prompt_proto_init() }
func file_ai_prompt_proto_init() {
	if File_ai_prompt_proto != nil {
		return
	}
	file_ai_promptvariable_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_prompt_proto_rawDesc), len(file_ai_prompt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_prompt_proto_goTypes,
		DependencyIndexes: file_ai_prompt_proto_depIdxs,
		MessageInfos:      file_ai_prompt_proto_msgTypes,
	}.Build()
	File_ai_prompt_proto = out.File
	file_ai_prompt_proto_goTypes = nil
	file_ai_prompt_proto_depIdxs = nil
}
