// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/runtimeversionbinding.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "RuntimeVersionBinding"
// Flattened from: RuntimeVersionBinding
type RuntimeVersionBinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuntimeVersion string                 `protobuf:"bytes,1,opt,name=runtimeVersion,proto3" json:"runtimeVersion,omitempty"`
	VersionRange   string                 `protobuf:"bytes,2,opt,name=versionRange,proto3" json:"versionRange,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeVersionBinding) Reset() {
	*x = RuntimeVersionBinding{}
	mi := &file_ai_runtimeversionbinding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeVersionBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeVersionBinding) ProtoMessage() {}

func (x *RuntimeVersionBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ai_runtimeversionbinding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeVersionBinding.ProtoReflect.Descriptor instead.
func (*RuntimeVersionBinding) Descriptor() ([]byte, []int) {
	return file_ai_runtimeversionbinding_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeVersionBinding) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *RuntimeVersionBinding) GetVersionRange() string {
	if x != nil {
		return x.VersionRange
	}
	return ""
}

var File_ai_runtimeversionbinding_proto protoreflect.FileDescriptor

const file_ai_runtimeversionbinding_proto_rawDesc = "" +
	"\n" +
	"\x1eai/runtimeversionbinding.proto\x12\bnacos.ai\"c\n" +
	"\x15RuntimeVersionBinding\x12&\n" +
	"\x0eruntimeVersion\x18\x01 \x01(\tR\x0eruntimeVersion\x12\"\n" +
	"\fversionRange\x18\x02 \x01(\tR\fversionRangeB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_runtimeversionbinding_proto_rawDescOnce sync.Once
	file_ai_runtimeversionbinding_proto_rawDescData []byte
)

func file_ai_runtimeversionbinding_proto_rawDescGZIP() []byte {
	file_ai_runtimeversionbinding_proto_rawDescOnce.Do(func() {
		file_ai_runtimeversionbinding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_runtimeversionbinding_proto_rawDesc), len(file_ai_runtimeversionbinding_proto_rawDesc)))
	})
	return file_ai_runtimeversionbinding_proto_rawDescData
}

var file_ai_runtimeversionbinding_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_runtimeversionbinding_proto_goTypes = []any{
	(*RuntimeVersionBinding)(nil), // 0: nacos.ai.RuntimeVersionBinding
}
var file_ai_runtimeversionbinding_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_runtimeversionbinding_proto_init() }
func file_ai_runtimeversionbinding_proto_init() {
	if File_ai_runtimeversionbinding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_runtimeversionbinding_proto_rawDesc), len(file_ai_runtimeversionbinding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_runtimeversionbinding_proto_goTypes,
		DependencyIndexes: file_ai_runtimeversionbinding_proto_depIdxs,
		MessageInfos:      file_ai_runtimeversionbinding_proto_msgTypes,
	}.Build()
	File_ai_runtimeversionbinding_proto = out.File
	file_ai_runtimeversionbinding_proto_goTypes = nil
	file_ai_runtimeversionbinding_proto_depIdxs = nil
}
