// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: ai/securityscheme.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "SecurityScheme"
// Flattened from: SecurityScheme
type SecurityScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     int32                  `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	LoadFactor    float32                `protobuf:"fixed32,2,opt,name=loadFactor,proto3" json:"loadFactor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityScheme) Reset() {
	*x = SecurityScheme{}
	mi := &file_ai_securityscheme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityScheme) ProtoMessage() {}

func (x *SecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_ai_securityscheme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityScheme.ProtoReflect.Descriptor instead.
func (*SecurityScheme) Descriptor() ([]byte, []int) {
	return file_ai_securityscheme_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityScheme) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SecurityScheme) GetLoadFactor() float32 {
	if x != nil {
		return x.LoadFactor
	}
	return 0
}

// metadata.type = "McpSecurityScheme"
// Flattened from: SecurityScheme
type McpSecurityScheme struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type              string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Scheme            string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	In                string                 `protobuf:"bytes,4,opt,name=in,proto3" json:"in,omitempty"`
	Name              string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	DefaultCredential string                 `protobuf:"bytes,6,opt,name=defaultCredential,proto3" json:"defaultCredential,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *McpSecurityScheme) Reset() {
	*x = McpSecurityScheme{}
	mi := &file_ai_securityscheme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpSecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpSecurityScheme) ProtoMessage() {}

func (x *McpSecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_ai_securityscheme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpSecurityScheme.ProtoReflect.Descriptor instead.
func (*McpSecurityScheme) Descriptor() ([]byte, []int) {
	return file_ai_securityscheme_proto_rawDescGZIP(), []int{1}
}

func (x *McpSecurityScheme) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *McpSecurityScheme) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *McpSecurityScheme) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *McpSecurityScheme) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *McpSecurityScheme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *McpSecurityScheme) GetDefaultCredential() string {
	if x != nil {
		return x.DefaultCredential
	}
	return ""
}

var File_ai_securityscheme_proto protoreflect.FileDescriptor

const file_ai_securityscheme_proto_rawDesc = "" +
	"\n" +
	"\x17ai/securityscheme.proto\x12\bnacos.ai\"N\n" +
	"\x0eSecurityScheme\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x05R\tthreshold\x12\x1e\n" +
	"\n" +
	"loadFactor\x18\x02 \x01(\x02R\n" +
	"loadFactor\"\xa1\x01\n" +
	"\x11McpSecurityScheme\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12\x0e\n" +
	"\x02in\x18\x04 \x01(\tR\x02in\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12,\n" +
	"\x11defaultCredential\x18\x06 \x01(\tR\x11defaultCredentialB.Z,github.com/nacos-group/nacos-sdk-proto/go/aib\x06proto3"

var (
	file_ai_securityscheme_proto_rawDescOnce sync.Once
	file_ai_securityscheme_proto_rawDescData []byte
)

func file_ai_securityscheme_proto_rawDescGZIP() []byte {
	file_ai_securityscheme_proto_rawDescOnce.Do(func() {
		file_ai_securityscheme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_securityscheme_proto_rawDesc), len(file_ai_securityscheme_proto_rawDesc)))
	})
	return file_ai_securityscheme_proto_rawDescData
}

var file_ai_securityscheme_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_securityscheme_proto_goTypes = []any{
	(*SecurityScheme)(nil),    // 0: nacos.ai.SecurityScheme
	(*McpSecurityScheme)(nil), // 1: nacos.ai.McpSecurityScheme
}
var file_ai_securityscheme_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_securityscheme_proto_init() }
func file_ai_securityscheme_proto_init() {
	if File_ai_securityscheme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_securityscheme_proto_rawDesc), len(file_ai_securityscheme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_securityscheme_proto_goTypes,
		DependencyIndexes: file_ai_securityscheme_proto_depIdxs,
		MessageInfos:      file_ai_securityscheme_proto_msgTypes,
	}.Build()
	File_ai_securityscheme_proto = out.File
	file_ai_securityscheme_proto_goTypes = nil
	file_ai_securityscheme_proto_depIdxs = nil
}
