// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: naming/instance.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "Instance"
 * Flattened from: Instance
 */
export interface Instance {
  instanceId: string;
  ip: string;
  port: number;
  weight: number;
  healthy: boolean;
  enabled: boolean;
  ephemeral: boolean;
  clusterName: string;
  serviceName: string;
  metadata: { [key: string]: string };
}

export interface Instance_MetadataEntry {
  key: string;
  value: string;
}

function createBaseInstance(): Instance {
  return {
    instanceId: "",
    ip: "",
    port: 0,
    weight: 0,
    healthy: false,
    enabled: false,
    ephemeral: false,
    clusterName: "",
    serviceName: "",
    metadata: {},
  };
}

export const Instance: MessageFns<Instance> = {
  fromJSON(object: any): Instance {
    return {
      instanceId: isSet(object.instanceId) ? globalThis.String(object.instanceId) : "",
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      weight: isSet(object.weight) ? globalThis.Number(object.weight) : 0,
      healthy: isSet(object.healthy) ? globalThis.Boolean(object.healthy) : false,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      ephemeral: isSet(object.ephemeral) ? globalThis.Boolean(object.ephemeral) : false,
      clusterName: isSet(object.clusterName) ? globalThis.String(object.clusterName) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: Instance): unknown {
    const obj: any = {};
    if (message.instanceId !== "") {
      obj.instanceId = message.instanceId;
    }
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.weight !== 0) {
      obj.weight = message.weight;
    }
    if (message.healthy !== false) {
      obj.healthy = message.healthy;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.ephemeral !== false) {
      obj.ephemeral = message.ephemeral;
    }
    if (message.clusterName !== "") {
      obj.clusterName = message.clusterName;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Instance>, I>>(base?: I): Instance {
    return Instance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Instance>, I>>(object: I): Instance {
    const message = createBaseInstance();
    message.instanceId = object.instanceId ?? "";
    message.ip = object.ip ?? "";
    message.port = object.port ?? 0;
    message.weight = object.weight ?? 0;
    message.healthy = object.healthy ?? false;
    message.enabled = object.enabled ?? false;
    message.ephemeral = object.ephemeral ?? false;
    message.clusterName = object.clusterName ?? "";
    message.serviceName = object.serviceName ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseInstance_MetadataEntry(): Instance_MetadataEntry {
  return { key: "", value: "" };
}

export const Instance_MetadataEntry: MessageFns<Instance_MetadataEntry> = {
  fromJSON(object: any): Instance_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Instance_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Instance_MetadataEntry>, I>>(base?: I): Instance_MetadataEntry {
    return Instance_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Instance_MetadataEntry>, I>>(object: I): Instance_MetadataEntry {
    const message = createBaseInstance_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
