// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: naming/naming_request.proto

/* eslint-disable */
import { Instance } from "./instance";
import { ServiceInfo } from "./serviceinfo";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "BatchInstanceRequest"
 * Flattened from: BatchInstanceRequest -> AbstractNamingRequest -> Request
 */
export interface BatchInstanceRequest {
  requestId: string;
  namespace: string;
  serviceName: string;
  groupName: string;
  type: string;
  instances: Instance[];
}

/**
 * metadata.type = "InstanceRequest"
 * Flattened from: InstanceRequest -> AbstractNamingRequest -> Request
 */
export interface InstanceRequest {
  requestId: string;
  namespace: string;
  serviceName: string;
  groupName: string;
  type: string;
  instance: Instance | undefined;
}

/**
 * metadata.type = "NamingFuzzyWatchChangeNotifyRequest"
 * Flattened from: NamingFuzzyWatchChangeNotifyRequest -> AbstractFuzzyWatchNotifyRequest -> ServerRequest -> Request
 */
export interface NamingFuzzyWatchChangeNotifyRequest {
  requestId: string;
  syncType: string;
  serviceKey: string;
  changedType: string;
}

/**
 * metadata.type = "NamingFuzzyWatchRequest"
 * Flattened from: NamingFuzzyWatchRequest -> Request
 */
export interface NamingFuzzyWatchRequest {
  requestId: string;
  isInitializing: boolean;
  namespace: string;
  groupKeyPattern: string;
  receivedGroupKeys: string[];
  watchType: string;
}

/**
 * metadata.type = "NamingFuzzyWatchSyncRequest"
 * Flattened from: NamingFuzzyWatchSyncRequest -> AbstractFuzzyWatchNotifyRequest -> ServerRequest -> Request
 */
export interface NamingFuzzyWatchSyncRequest {
  requestId: string;
  syncType: string;
  groupKeyPattern: string;
  contexts: NamingFuzzyWatchSyncRequestContext[];
  totalBatch: number;
  currentBatch: number;
}

/**
 * metadata.type = "NamingFuzzyWatchSyncRequestContext"
 * Flattened from: Context
 */
export interface NamingFuzzyWatchSyncRequestContext {
  serviceKey: string;
  changedType: string;
}

/**
 * metadata.type = "NotifySubscriberRequest"
 * Flattened from: NotifySubscriberRequest -> ServerRequest -> Request
 */
export interface NotifySubscriberRequest {
  requestId: string;
  namespace: string;
  serviceName: string;
  groupName: string;
  serviceInfo: ServiceInfo | undefined;
}

/**
 * metadata.type = "PersistentInstanceRequest"
 * Flattened from: PersistentInstanceRequest -> AbstractNamingRequest -> Request
 */
export interface PersistentInstanceRequest {
  requestId: string;
  namespace: string;
  serviceName: string;
  groupName: string;
  type: string;
  instance: Instance | undefined;
}

/**
 * metadata.type = "ServiceListRequest"
 * Flattened from: ServiceListRequest -> AbstractNamingRequest -> Request
 */
export interface ServiceListRequest {
  requestId: string;
  namespace: string;
  serviceName: string;
  groupName: string;
  pageNo: number;
  pageSize: number;
  selector: string;
}

/**
 * metadata.type = "ServiceQueryRequest"
 * Flattened from: ServiceQueryRequest -> AbstractNamingRequest -> Request
 */
export interface ServiceQueryRequest {
  requestId: string;
  namespace: string;
  serviceName: string;
  groupName: string;
  cluster: string;
  healthyOnly: boolean;
  udpPort: number;
}

/**
 * metadata.type = "SubscribeServiceRequest"
 * Flattened from: SubscribeServiceRequest -> AbstractNamingRequest -> Request
 */
export interface SubscribeServiceRequest {
  requestId: string;
  namespace: string;
  serviceName: string;
  groupName: string;
  subscribe: boolean;
  clusters: string;
}

function createBaseBatchInstanceRequest(): BatchInstanceRequest {
  return { requestId: "", namespace: "", serviceName: "", groupName: "", type: "", instances: [] };
}

export const BatchInstanceRequest: MessageFns<BatchInstanceRequest> = {
  fromJSON(object: any): BatchInstanceRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      instances: globalThis.Array.isArray(object?.instances)
        ? object.instances.map((e: any) => Instance.fromJSON(e))
        : [],
    };
  },

  toJSON(message: BatchInstanceRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.instances?.length) {
      obj.instances = message.instances.map((e) => Instance.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BatchInstanceRequest>, I>>(base?: I): BatchInstanceRequest {
    return BatchInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BatchInstanceRequest>, I>>(object: I): BatchInstanceRequest {
    const message = createBaseBatchInstanceRequest();
    message.requestId = object.requestId ?? "";
    message.namespace = object.namespace ?? "";
    message.serviceName = object.serviceName ?? "";
    message.groupName = object.groupName ?? "";
    message.type = object.type ?? "";
    message.instances = object.instances?.map((e) => Instance.fromPartial(e)) || [];
    return message;
  },
};

function createBaseInstanceRequest(): InstanceRequest {
  return { requestId: "", namespace: "", serviceName: "", groupName: "", type: "", instance: undefined };
}

export const InstanceRequest: MessageFns<InstanceRequest> = {
  fromJSON(object: any): InstanceRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      instance: isSet(object.instance) ? Instance.fromJSON(object.instance) : undefined,
    };
  },

  toJSON(message: InstanceRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.instance !== undefined) {
      obj.instance = Instance.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InstanceRequest>, I>>(base?: I): InstanceRequest {
    return InstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstanceRequest>, I>>(object: I): InstanceRequest {
    const message = createBaseInstanceRequest();
    message.requestId = object.requestId ?? "";
    message.namespace = object.namespace ?? "";
    message.serviceName = object.serviceName ?? "";
    message.groupName = object.groupName ?? "";
    message.type = object.type ?? "";
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? Instance.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseNamingFuzzyWatchChangeNotifyRequest(): NamingFuzzyWatchChangeNotifyRequest {
  return { requestId: "", syncType: "", serviceKey: "", changedType: "" };
}

export const NamingFuzzyWatchChangeNotifyRequest: MessageFns<NamingFuzzyWatchChangeNotifyRequest> = {
  fromJSON(object: any): NamingFuzzyWatchChangeNotifyRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      syncType: isSet(object.syncType) ? globalThis.String(object.syncType) : "",
      serviceKey: isSet(object.serviceKey) ? globalThis.String(object.serviceKey) : "",
      changedType: isSet(object.changedType) ? globalThis.String(object.changedType) : "",
    };
  },

  toJSON(message: NamingFuzzyWatchChangeNotifyRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.syncType !== "") {
      obj.syncType = message.syncType;
    }
    if (message.serviceKey !== "") {
      obj.serviceKey = message.serviceKey;
    }
    if (message.changedType !== "") {
      obj.changedType = message.changedType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamingFuzzyWatchChangeNotifyRequest>, I>>(
    base?: I,
  ): NamingFuzzyWatchChangeNotifyRequest {
    return NamingFuzzyWatchChangeNotifyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamingFuzzyWatchChangeNotifyRequest>, I>>(
    object: I,
  ): NamingFuzzyWatchChangeNotifyRequest {
    const message = createBaseNamingFuzzyWatchChangeNotifyRequest();
    message.requestId = object.requestId ?? "";
    message.syncType = object.syncType ?? "";
    message.serviceKey = object.serviceKey ?? "";
    message.changedType = object.changedType ?? "";
    return message;
  },
};

function createBaseNamingFuzzyWatchRequest(): NamingFuzzyWatchRequest {
  return {
    requestId: "",
    isInitializing: false,
    namespace: "",
    groupKeyPattern: "",
    receivedGroupKeys: [],
    watchType: "",
  };
}

export const NamingFuzzyWatchRequest: MessageFns<NamingFuzzyWatchRequest> = {
  fromJSON(object: any): NamingFuzzyWatchRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      isInitializing: isSet(object.isInitializing) ? globalThis.Boolean(object.isInitializing) : false,
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      groupKeyPattern: isSet(object.groupKeyPattern) ? globalThis.String(object.groupKeyPattern) : "",
      receivedGroupKeys: globalThis.Array.isArray(object?.receivedGroupKeys)
        ? object.receivedGroupKeys.map((e: any) => globalThis.String(e))
        : [],
      watchType: isSet(object.watchType) ? globalThis.String(object.watchType) : "",
    };
  },

  toJSON(message: NamingFuzzyWatchRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.isInitializing !== false) {
      obj.isInitializing = message.isInitializing;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.groupKeyPattern !== "") {
      obj.groupKeyPattern = message.groupKeyPattern;
    }
    if (message.receivedGroupKeys?.length) {
      obj.receivedGroupKeys = message.receivedGroupKeys;
    }
    if (message.watchType !== "") {
      obj.watchType = message.watchType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamingFuzzyWatchRequest>, I>>(base?: I): NamingFuzzyWatchRequest {
    return NamingFuzzyWatchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamingFuzzyWatchRequest>, I>>(object: I): NamingFuzzyWatchRequest {
    const message = createBaseNamingFuzzyWatchRequest();
    message.requestId = object.requestId ?? "";
    message.isInitializing = object.isInitializing ?? false;
    message.namespace = object.namespace ?? "";
    message.groupKeyPattern = object.groupKeyPattern ?? "";
    message.receivedGroupKeys = object.receivedGroupKeys?.map((e) => e) || [];
    message.watchType = object.watchType ?? "";
    return message;
  },
};

function createBaseNamingFuzzyWatchSyncRequest(): NamingFuzzyWatchSyncRequest {
  return { requestId: "", syncType: "", groupKeyPattern: "", contexts: [], totalBatch: 0, currentBatch: 0 };
}

export const NamingFuzzyWatchSyncRequest: MessageFns<NamingFuzzyWatchSyncRequest> = {
  fromJSON(object: any): NamingFuzzyWatchSyncRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      syncType: isSet(object.syncType) ? globalThis.String(object.syncType) : "",
      groupKeyPattern: isSet(object.groupKeyPattern) ? globalThis.String(object.groupKeyPattern) : "",
      contexts: globalThis.Array.isArray(object?.contexts)
        ? object.contexts.map((e: any) => NamingFuzzyWatchSyncRequestContext.fromJSON(e))
        : [],
      totalBatch: isSet(object.totalBatch) ? globalThis.Number(object.totalBatch) : 0,
      currentBatch: isSet(object.currentBatch) ? globalThis.Number(object.currentBatch) : 0,
    };
  },

  toJSON(message: NamingFuzzyWatchSyncRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.syncType !== "") {
      obj.syncType = message.syncType;
    }
    if (message.groupKeyPattern !== "") {
      obj.groupKeyPattern = message.groupKeyPattern;
    }
    if (message.contexts?.length) {
      obj.contexts = message.contexts.map((e) => NamingFuzzyWatchSyncRequestContext.toJSON(e));
    }
    if (message.totalBatch !== 0) {
      obj.totalBatch = Math.round(message.totalBatch);
    }
    if (message.currentBatch !== 0) {
      obj.currentBatch = Math.round(message.currentBatch);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamingFuzzyWatchSyncRequest>, I>>(base?: I): NamingFuzzyWatchSyncRequest {
    return NamingFuzzyWatchSyncRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamingFuzzyWatchSyncRequest>, I>>(object: I): NamingFuzzyWatchSyncRequest {
    const message = createBaseNamingFuzzyWatchSyncRequest();
    message.requestId = object.requestId ?? "";
    message.syncType = object.syncType ?? "";
    message.groupKeyPattern = object.groupKeyPattern ?? "";
    message.contexts = object.contexts?.map((e) => NamingFuzzyWatchSyncRequestContext.fromPartial(e)) || [];
    message.totalBatch = object.totalBatch ?? 0;
    message.currentBatch = object.currentBatch ?? 0;
    return message;
  },
};

function createBaseNamingFuzzyWatchSyncRequestContext(): NamingFuzzyWatchSyncRequestContext {
  return { serviceKey: "", changedType: "" };
}

export const NamingFuzzyWatchSyncRequestContext: MessageFns<NamingFuzzyWatchSyncRequestContext> = {
  fromJSON(object: any): NamingFuzzyWatchSyncRequestContext {
    return {
      serviceKey: isSet(object.serviceKey) ? globalThis.String(object.serviceKey) : "",
      changedType: isSet(object.changedType) ? globalThis.String(object.changedType) : "",
    };
  },

  toJSON(message: NamingFuzzyWatchSyncRequestContext): unknown {
    const obj: any = {};
    if (message.serviceKey !== "") {
      obj.serviceKey = message.serviceKey;
    }
    if (message.changedType !== "") {
      obj.changedType = message.changedType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NamingFuzzyWatchSyncRequestContext>, I>>(
    base?: I,
  ): NamingFuzzyWatchSyncRequestContext {
    return NamingFuzzyWatchSyncRequestContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NamingFuzzyWatchSyncRequestContext>, I>>(
    object: I,
  ): NamingFuzzyWatchSyncRequestContext {
    const message = createBaseNamingFuzzyWatchSyncRequestContext();
    message.serviceKey = object.serviceKey ?? "";
    message.changedType = object.changedType ?? "";
    return message;
  },
};

function createBaseNotifySubscriberRequest(): NotifySubscriberRequest {
  return { requestId: "", namespace: "", serviceName: "", groupName: "", serviceInfo: undefined };
}

export const NotifySubscriberRequest: MessageFns<NotifySubscriberRequest> = {
  fromJSON(object: any): NotifySubscriberRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      serviceInfo: isSet(object.serviceInfo) ? ServiceInfo.fromJSON(object.serviceInfo) : undefined,
    };
  },

  toJSON(message: NotifySubscriberRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.serviceInfo !== undefined) {
      obj.serviceInfo = ServiceInfo.toJSON(message.serviceInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NotifySubscriberRequest>, I>>(base?: I): NotifySubscriberRequest {
    return NotifySubscriberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NotifySubscriberRequest>, I>>(object: I): NotifySubscriberRequest {
    const message = createBaseNotifySubscriberRequest();
    message.requestId = object.requestId ?? "";
    message.namespace = object.namespace ?? "";
    message.serviceName = object.serviceName ?? "";
    message.groupName = object.groupName ?? "";
    message.serviceInfo = (object.serviceInfo !== undefined && object.serviceInfo !== null)
      ? ServiceInfo.fromPartial(object.serviceInfo)
      : undefined;
    return message;
  },
};

function createBasePersistentInstanceRequest(): PersistentInstanceRequest {
  return { requestId: "", namespace: "", serviceName: "", groupName: "", type: "", instance: undefined };
}

export const PersistentInstanceRequest: MessageFns<PersistentInstanceRequest> = {
  fromJSON(object: any): PersistentInstanceRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      instance: isSet(object.instance) ? Instance.fromJSON(object.instance) : undefined,
    };
  },

  toJSON(message: PersistentInstanceRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.instance !== undefined) {
      obj.instance = Instance.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PersistentInstanceRequest>, I>>(base?: I): PersistentInstanceRequest {
    return PersistentInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PersistentInstanceRequest>, I>>(object: I): PersistentInstanceRequest {
    const message = createBasePersistentInstanceRequest();
    message.requestId = object.requestId ?? "";
    message.namespace = object.namespace ?? "";
    message.serviceName = object.serviceName ?? "";
    message.groupName = object.groupName ?? "";
    message.type = object.type ?? "";
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? Instance.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseServiceListRequest(): ServiceListRequest {
  return { requestId: "", namespace: "", serviceName: "", groupName: "", pageNo: 0, pageSize: 0, selector: "" };
}

export const ServiceListRequest: MessageFns<ServiceListRequest> = {
  fromJSON(object: any): ServiceListRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      pageNo: isSet(object.pageNo) ? globalThis.Number(object.pageNo) : 0,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
      selector: isSet(object.selector) ? globalThis.String(object.selector) : "",
    };
  },

  toJSON(message: ServiceListRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.pageNo !== 0) {
      obj.pageNo = Math.round(message.pageNo);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.selector !== "") {
      obj.selector = message.selector;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceListRequest>, I>>(base?: I): ServiceListRequest {
    return ServiceListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceListRequest>, I>>(object: I): ServiceListRequest {
    const message = createBaseServiceListRequest();
    message.requestId = object.requestId ?? "";
    message.namespace = object.namespace ?? "";
    message.serviceName = object.serviceName ?? "";
    message.groupName = object.groupName ?? "";
    message.pageNo = object.pageNo ?? 0;
    message.pageSize = object.pageSize ?? 0;
    message.selector = object.selector ?? "";
    return message;
  },
};

function createBaseServiceQueryRequest(): ServiceQueryRequest {
  return { requestId: "", namespace: "", serviceName: "", groupName: "", cluster: "", healthyOnly: false, udpPort: 0 };
}

export const ServiceQueryRequest: MessageFns<ServiceQueryRequest> = {
  fromJSON(object: any): ServiceQueryRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      cluster: isSet(object.cluster) ? globalThis.String(object.cluster) : "",
      healthyOnly: isSet(object.healthyOnly) ? globalThis.Boolean(object.healthyOnly) : false,
      udpPort: isSet(object.udpPort) ? globalThis.Number(object.udpPort) : 0,
    };
  },

  toJSON(message: ServiceQueryRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.cluster !== "") {
      obj.cluster = message.cluster;
    }
    if (message.healthyOnly !== false) {
      obj.healthyOnly = message.healthyOnly;
    }
    if (message.udpPort !== 0) {
      obj.udpPort = Math.round(message.udpPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceQueryRequest>, I>>(base?: I): ServiceQueryRequest {
    return ServiceQueryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceQueryRequest>, I>>(object: I): ServiceQueryRequest {
    const message = createBaseServiceQueryRequest();
    message.requestId = object.requestId ?? "";
    message.namespace = object.namespace ?? "";
    message.serviceName = object.serviceName ?? "";
    message.groupName = object.groupName ?? "";
    message.cluster = object.cluster ?? "";
    message.healthyOnly = object.healthyOnly ?? false;
    message.udpPort = object.udpPort ?? 0;
    return message;
  },
};

function createBaseSubscribeServiceRequest(): SubscribeServiceRequest {
  return { requestId: "", namespace: "", serviceName: "", groupName: "", subscribe: false, clusters: "" };
}

export const SubscribeServiceRequest: MessageFns<SubscribeServiceRequest> = {
  fromJSON(object: any): SubscribeServiceRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      subscribe: isSet(object.subscribe) ? globalThis.Boolean(object.subscribe) : false,
      clusters: isSet(object.clusters) ? globalThis.String(object.clusters) : "",
    };
  },

  toJSON(message: SubscribeServiceRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.subscribe !== false) {
      obj.subscribe = message.subscribe;
    }
    if (message.clusters !== "") {
      obj.clusters = message.clusters;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeServiceRequest>, I>>(base?: I): SubscribeServiceRequest {
    return SubscribeServiceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeServiceRequest>, I>>(object: I): SubscribeServiceRequest {
    const message = createBaseSubscribeServiceRequest();
    message.requestId = object.requestId ?? "";
    message.namespace = object.namespace ?? "";
    message.serviceName = object.serviceName ?? "";
    message.groupName = object.groupName ?? "";
    message.subscribe = object.subscribe ?? false;
    message.clusters = object.clusters ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
