// Code generated by render-version.sh from proto/VERSION. DO NOT EDIT.

/** The nacos ref (tag or branch) the protos were generated from. */
export const NACOS_REF = "develop";

/** The exact alibaba/nacos commit the protos were generated from. */
export const NACOS_COMMIT = "1b6309f5086c163a1ff9c0469fabd4494ec09093";
