// Code generated by render-version.sh from proto/VERSION. DO NOT EDIT.

/** The nacos ref (tag or branch) the protos were generated from. */
export const NACOS_REF = "develop";

/** The exact alibaba/nacos commit the protos were generated from. */
export const NACOS_COMMIT = "308bb56c204fc00c20e678fdb511d818ee8d5be6";
