// Code generated by render-version.sh from proto/VERSION. DO NOT EDIT.

/** The nacos ref (tag or branch) the protos were generated from. */
export const NACOS_REF = "develop";

/** The exact alibaba/nacos commit the protos were generated from. */
export const NACOS_COMMIT = "c19f283dca641f14d24abbcc1d9577e1ca5e2ff3";
