// Code generated by render-version.sh from proto/VERSION. DO NOT EDIT.

package _go

// NacosRef is the nacos ref (tag or branch) the protos were generated from.
const NacosRef = "develop"

// NacosCommit is the exact alibaba/nacos commit the protos were generated from.
const NacosCommit = "e9b1b81edb87faab4707438f66af267a13a416db"
