// Code generated by render-version.sh from proto/VERSION. DO NOT EDIT.

package _go

// NacosRef is the nacos ref (tag or branch) the protos were generated from.
const NacosRef = "develop"

// NacosCommit is the exact alibaba/nacos commit the protos were generated from.
const NacosCommit = "2a8809fd446b5426e1fd5ca19cba60aa7aeb62e7"
