// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v5.28.3
// source: ai/agentversioninfo.proto

/* eslint-disable */
import { AgentVersionSummary } from "./agentversionsummary";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentVersionInfo"
 * Flattened from: AgentVersionInfo
 */
export interface AgentVersionInfo {
  editingVersion: string;
  reviewingVersion: string;
  onlineVersions: AgentVersionSummary[];
  labels: { [key: string]: string };
}

export interface AgentVersionInfo_LabelsEntry {
  key: string;
  value: string;
}

function createBaseAgentVersionInfo(): AgentVersionInfo {
  return { editingVersion: "", reviewingVersion: "", onlineVersions: [], labels: {} };
}

export const AgentVersionInfo: MessageFns<AgentVersionInfo> = {
  fromJSON(object: any): AgentVersionInfo {
    return {
      editingVersion: isSet(object.editingVersion) ? globalThis.String(object.editingVersion) : "",
      reviewingVersion: isSet(object.reviewingVersion) ? globalThis.String(object.reviewingVersion) : "",
      onlineVersions: globalThis.Array.isArray(object?.onlineVersions)
        ? object.onlineVersions.map((e: any) => AgentVersionSummary.fromJSON(e))
        : [],
      labels: isObject(object.labels)
        ? (globalThis.Object.entries(object.labels) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: AgentVersionInfo): unknown {
    const obj: any = {};
    if (message.editingVersion !== "") {
      obj.editingVersion = message.editingVersion;
    }
    if (message.reviewingVersion !== "") {
      obj.reviewingVersion = message.reviewingVersion;
    }
    if (message.onlineVersions?.length) {
      obj.onlineVersions = message.onlineVersions.map((e) => AgentVersionSummary.toJSON(e));
    }
    if (message.labels) {
      const entries = globalThis.Object.entries(message.labels) as [string, string][];
      if (entries.length > 0) {
        obj.labels = {};
        entries.forEach(([k, v]) => {
          obj.labels[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentVersionInfo>, I>>(base?: I): AgentVersionInfo {
    return AgentVersionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentVersionInfo>, I>>(object: I): AgentVersionInfo {
    const message = createBaseAgentVersionInfo();
    message.editingVersion = object.editingVersion ?? "";
    message.reviewingVersion = object.reviewingVersion ?? "";
    message.onlineVersions = object.onlineVersions?.map((e) => AgentVersionSummary.fromPartial(e)) || [];
    message.labels = (globalThis.Object.entries(object.labels ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseAgentVersionInfo_LabelsEntry(): AgentVersionInfo_LabelsEntry {
  return { key: "", value: "" };
}

export const AgentVersionInfo_LabelsEntry: MessageFns<AgentVersionInfo_LabelsEntry> = {
  fromJSON(object: any): AgentVersionInfo_LabelsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: AgentVersionInfo_LabelsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentVersionInfo_LabelsEntry>, I>>(base?: I): AgentVersionInfo_LabelsEntry {
    return AgentVersionInfo_LabelsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentVersionInfo_LabelsEntry>, I>>(object: I): AgentVersionInfo_LabelsEntry {
    const message = createBaseAgentVersionInfo_LabelsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
