// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v5.28.3
// source: ai/agentsummary.proto

/* eslint-disable */
import { AgentProvider } from "./agentprovider";
import { AgentVersionInfo } from "./agentversioninfo";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentSummary"
 * Flattened from: AgentSummary -> AbstractAgentMetadata
 */
export interface AgentSummary {
  agentName: string;
  displayName: string;
  description: string;
  iconUrl: string;
  provider: AgentProvider | undefined;
  tags: string[];
  extensions: { [key: string]: any | undefined };
  namespaceId: string;
  status: string;
  owner: string;
  scope: string;
  versionInfo: AgentVersionInfo | undefined;
  metaVersion: number;
  createTime: number;
  updateTime: number;
}

export interface AgentSummary_ExtensionsEntry {
  key: string;
  value: any | undefined;
}

function createBaseAgentSummary(): AgentSummary {
  return {
    agentName: "",
    displayName: "",
    description: "",
    iconUrl: "",
    provider: undefined,
    tags: [],
    extensions: {},
    namespaceId: "",
    status: "",
    owner: "",
    scope: "",
    versionInfo: undefined,
    metaVersion: 0,
    createTime: 0,
    updateTime: 0,
  };
}

export const AgentSummary: MessageFns<AgentSummary> = {
  fromJSON(object: any): AgentSummary {
    return {
      agentName: isSet(object.agentName) ? globalThis.String(object.agentName) : "",
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      iconUrl: isSet(object.iconUrl) ? globalThis.String(object.iconUrl) : "",
      provider: isSet(object.provider) ? AgentProvider.fromJSON(object.provider) : undefined,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      extensions: isObject(object.extensions)
        ? (globalThis.Object.entries(object.extensions) as [string, any][]).reduce(
          (acc: { [key: string]: any | undefined }, [key, value]: [string, any]) => {
            acc[key] = value as any | undefined;
            return acc;
          },
          {},
        )
        : {},
      namespaceId: isSet(object.namespaceId) ? globalThis.String(object.namespaceId) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
      versionInfo: isSet(object.versionInfo) ? AgentVersionInfo.fromJSON(object.versionInfo) : undefined,
      metaVersion: isSet(object.metaVersion) ? globalThis.Number(object.metaVersion) : 0,
      createTime: isSet(object.createTime) ? globalThis.Number(object.createTime) : 0,
      updateTime: isSet(object.updateTime) ? globalThis.Number(object.updateTime) : 0,
    };
  },

  toJSON(message: AgentSummary): unknown {
    const obj: any = {};
    if (message.agentName !== "") {
      obj.agentName = message.agentName;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.iconUrl !== "") {
      obj.iconUrl = message.iconUrl;
    }
    if (message.provider !== undefined) {
      obj.provider = AgentProvider.toJSON(message.provider);
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.extensions) {
      const entries = globalThis.Object.entries(message.extensions) as [string, any | undefined][];
      if (entries.length > 0) {
        obj.extensions = {};
        entries.forEach(([k, v]) => {
          obj.extensions[k] = v;
        });
      }
    }
    if (message.namespaceId !== "") {
      obj.namespaceId = message.namespaceId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.scope !== "") {
      obj.scope = message.scope;
    }
    if (message.versionInfo !== undefined) {
      obj.versionInfo = AgentVersionInfo.toJSON(message.versionInfo);
    }
    if (message.metaVersion !== 0) {
      obj.metaVersion = Math.round(message.metaVersion);
    }
    if (message.createTime !== 0) {
      obj.createTime = Math.round(message.createTime);
    }
    if (message.updateTime !== 0) {
      obj.updateTime = Math.round(message.updateTime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentSummary>, I>>(base?: I): AgentSummary {
    return AgentSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentSummary>, I>>(object: I): AgentSummary {
    const message = createBaseAgentSummary();
    message.agentName = object.agentName ?? "";
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    message.iconUrl = object.iconUrl ?? "";
    message.provider = (object.provider !== undefined && object.provider !== null)
      ? AgentProvider.fromPartial(object.provider)
      : undefined;
    message.tags = object.tags?.map((e) => e) || [];
    message.extensions = (globalThis.Object.entries(object.extensions ?? {}) as [string, any | undefined][]).reduce(
      (acc: { [key: string]: any | undefined }, [key, value]: [string, any | undefined]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.namespaceId = object.namespaceId ?? "";
    message.status = object.status ?? "";
    message.owner = object.owner ?? "";
    message.scope = object.scope ?? "";
    message.versionInfo = (object.versionInfo !== undefined && object.versionInfo !== null)
      ? AgentVersionInfo.fromPartial(object.versionInfo)
      : undefined;
    message.metaVersion = object.metaVersion ?? 0;
    message.createTime = object.createTime ?? 0;
    message.updateTime = object.updateTime ?? 0;
    return message;
  },
};

function createBaseAgentSummary_ExtensionsEntry(): AgentSummary_ExtensionsEntry {
  return { key: "", value: undefined };
}

export const AgentSummary_ExtensionsEntry: MessageFns<AgentSummary_ExtensionsEntry> = {
  fromJSON(object: any): AgentSummary_ExtensionsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: AgentSummary_ExtensionsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentSummary_ExtensionsEntry>, I>>(base?: I): AgentSummary_ExtensionsEntry {
    return AgentSummary_ExtensionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentSummary_ExtensionsEntry>, I>>(object: I): AgentSummary_ExtensionsEntry {
    const message = createBaseAgentSummary_ExtensionsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
