// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: ai/agentinterface.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentInterface"
 * Flattened from: AgentInterface
 */
export interface AgentInterface {
  url: string;
  transport: string;
  protocolBinding: string;
  protocolVersion: string;
  tenant: string;
}

function createBaseAgentInterface(): AgentInterface {
  return { url: "", transport: "", protocolBinding: "", protocolVersion: "", tenant: "" };
}

export const AgentInterface: MessageFns<AgentInterface> = {
  fromJSON(object: any): AgentInterface {
    return {
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      transport: isSet(object.transport) ? globalThis.String(object.transport) : "",
      protocolBinding: isSet(object.protocolBinding) ? globalThis.String(object.protocolBinding) : "",
      protocolVersion: isSet(object.protocolVersion) ? globalThis.String(object.protocolVersion) : "",
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
    };
  },

  toJSON(message: AgentInterface): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.transport !== "") {
      obj.transport = message.transport;
    }
    if (message.protocolBinding !== "") {
      obj.protocolBinding = message.protocolBinding;
    }
    if (message.protocolVersion !== "") {
      obj.protocolVersion = message.protocolVersion;
    }
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentInterface>, I>>(base?: I): AgentInterface {
    return AgentInterface.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentInterface>, I>>(object: I): AgentInterface {
    const message = createBaseAgentInterface();
    message.url = object.url ?? "";
    message.transport = object.transport ?? "";
    message.protocolBinding = object.protocolBinding ?? "";
    message.protocolVersion = object.protocolVersion ?? "";
    message.tenant = object.tenant ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
