// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v5.28.3
// source: ai/agentcatalogentry.proto

/* eslint-disable */
import { AgentCatalogVersion } from "./agentcatalogversion";
import { AgentProvider } from "./agentprovider";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentCatalogEntry"
 * Flattened from: AgentCatalogEntry
 */
export interface AgentCatalogEntry {
  agentName: string;
  displayName: string;
  description: string;
  iconUrl: string;
  provider: AgentProvider | undefined;
  tags: string[];
  latestVersion: string;
  versions: AgentCatalogVersion[];
}

function createBaseAgentCatalogEntry(): AgentCatalogEntry {
  return {
    agentName: "",
    displayName: "",
    description: "",
    iconUrl: "",
    provider: undefined,
    tags: [],
    latestVersion: "",
    versions: [],
  };
}

export const AgentCatalogEntry: MessageFns<AgentCatalogEntry> = {
  fromJSON(object: any): AgentCatalogEntry {
    return {
      agentName: isSet(object.agentName) ? globalThis.String(object.agentName) : "",
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      iconUrl: isSet(object.iconUrl) ? globalThis.String(object.iconUrl) : "",
      provider: isSet(object.provider) ? AgentProvider.fromJSON(object.provider) : undefined,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      latestVersion: isSet(object.latestVersion) ? globalThis.String(object.latestVersion) : "",
      versions: globalThis.Array.isArray(object?.versions)
        ? object.versions.map((e: any) => AgentCatalogVersion.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AgentCatalogEntry): unknown {
    const obj: any = {};
    if (message.agentName !== "") {
      obj.agentName = message.agentName;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.iconUrl !== "") {
      obj.iconUrl = message.iconUrl;
    }
    if (message.provider !== undefined) {
      obj.provider = AgentProvider.toJSON(message.provider);
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.latestVersion !== "") {
      obj.latestVersion = message.latestVersion;
    }
    if (message.versions?.length) {
      obj.versions = message.versions.map((e) => AgentCatalogVersion.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentCatalogEntry>, I>>(base?: I): AgentCatalogEntry {
    return AgentCatalogEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentCatalogEntry>, I>>(object: I): AgentCatalogEntry {
    const message = createBaseAgentCatalogEntry();
    message.agentName = object.agentName ?? "";
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    message.iconUrl = object.iconUrl ?? "";
    message.provider = (object.provider !== undefined && object.provider !== null)
      ? AgentProvider.fromPartial(object.provider)
      : undefined;
    message.tags = object.tags?.map((e) => e) || [];
    message.latestVersion = object.latestVersion ?? "";
    message.versions = object.versions?.map((e) => AgentCatalogVersion.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
