// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: ai/agentendpoint.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentEndpoint"
 * Flattened from: AgentEndpoint
 */
export interface AgentEndpoint {
  transport: string;
  address: string;
  port: number;
  path: string;
  supportTls: boolean;
  version: string;
  protocolVersion: string;
  tenant: string;
  protocol: string;
  query: string;
}

function createBaseAgentEndpoint(): AgentEndpoint {
  return {
    transport: "",
    address: "",
    port: 0,
    path: "",
    supportTls: false,
    version: "",
    protocolVersion: "",
    tenant: "",
    protocol: "",
    query: "",
  };
}

export const AgentEndpoint: MessageFns<AgentEndpoint> = {
  fromJSON(object: any): AgentEndpoint {
    return {
      transport: isSet(object.transport) ? globalThis.String(object.transport) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      supportTls: isSet(object.supportTls) ? globalThis.Boolean(object.supportTls) : false,
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      protocolVersion: isSet(object.protocolVersion) ? globalThis.String(object.protocolVersion) : "",
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
      query: isSet(object.query) ? globalThis.String(object.query) : "",
    };
  },

  toJSON(message: AgentEndpoint): unknown {
    const obj: any = {};
    if (message.transport !== "") {
      obj.transport = message.transport;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.supportTls !== false) {
      obj.supportTls = message.supportTls;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.protocolVersion !== "") {
      obj.protocolVersion = message.protocolVersion;
    }
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.protocol !== "") {
      obj.protocol = message.protocol;
    }
    if (message.query !== "") {
      obj.query = message.query;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentEndpoint>, I>>(base?: I): AgentEndpoint {
    return AgentEndpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentEndpoint>, I>>(object: I): AgentEndpoint {
    const message = createBaseAgentEndpoint();
    message.transport = object.transport ?? "";
    message.address = object.address ?? "";
    message.port = object.port ?? 0;
    message.path = object.path ?? "";
    message.supportTls = object.supportTls ?? false;
    message.version = object.version ?? "";
    message.protocolVersion = object.protocolVersion ?? "";
    message.tenant = object.tenant ?? "";
    message.protocol = object.protocol ?? "";
    message.query = object.query ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
