// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v5.28.3
// source: ai/agentversiondetail.proto

/* eslint-disable */
import { AgentCallInterface } from "./agentcallinterface";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentVersionDetail"
 * Flattened from: AgentVersionDetail -> AgentVersionSummary
 */
export interface AgentVersionDetail {
  version: string;
  labels: string[];
  protocols: string[];
  status: string;
  publishPipelineInfo: string;
  author: string;
  changeDescription: string;
  contentDigest: string;
  createTime: number;
  updateTime: number;
  namespaceId: string;
  agentName: string;
  callInterfaces: AgentCallInterface[];
}

function createBaseAgentVersionDetail(): AgentVersionDetail {
  return {
    version: "",
    labels: [],
    protocols: [],
    status: "",
    publishPipelineInfo: "",
    author: "",
    changeDescription: "",
    contentDigest: "",
    createTime: 0,
    updateTime: 0,
    namespaceId: "",
    agentName: "",
    callInterfaces: [],
  };
}

export const AgentVersionDetail: MessageFns<AgentVersionDetail> = {
  fromJSON(object: any): AgentVersionDetail {
    return {
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      labels: globalThis.Array.isArray(object?.labels) ? object.labels.map((e: any) => globalThis.String(e)) : [],
      protocols: globalThis.Array.isArray(object?.protocols)
        ? object.protocols.map((e: any) => globalThis.String(e))
        : [],
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      publishPipelineInfo: isSet(object.publishPipelineInfo) ? globalThis.String(object.publishPipelineInfo) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      changeDescription: isSet(object.changeDescription) ? globalThis.String(object.changeDescription) : "",
      contentDigest: isSet(object.contentDigest) ? globalThis.String(object.contentDigest) : "",
      createTime: isSet(object.createTime) ? globalThis.Number(object.createTime) : 0,
      updateTime: isSet(object.updateTime) ? globalThis.Number(object.updateTime) : 0,
      namespaceId: isSet(object.namespaceId) ? globalThis.String(object.namespaceId) : "",
      agentName: isSet(object.agentName) ? globalThis.String(object.agentName) : "",
      callInterfaces: globalThis.Array.isArray(object?.callInterfaces)
        ? object.callInterfaces.map((e: any) => AgentCallInterface.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AgentVersionDetail): unknown {
    const obj: any = {};
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.labels?.length) {
      obj.labels = message.labels;
    }
    if (message.protocols?.length) {
      obj.protocols = message.protocols;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.publishPipelineInfo !== "") {
      obj.publishPipelineInfo = message.publishPipelineInfo;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.changeDescription !== "") {
      obj.changeDescription = message.changeDescription;
    }
    if (message.contentDigest !== "") {
      obj.contentDigest = message.contentDigest;
    }
    if (message.createTime !== 0) {
      obj.createTime = Math.round(message.createTime);
    }
    if (message.updateTime !== 0) {
      obj.updateTime = Math.round(message.updateTime);
    }
    if (message.namespaceId !== "") {
      obj.namespaceId = message.namespaceId;
    }
    if (message.agentName !== "") {
      obj.agentName = message.agentName;
    }
    if (message.callInterfaces?.length) {
      obj.callInterfaces = message.callInterfaces.map((e) => AgentCallInterface.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentVersionDetail>, I>>(base?: I): AgentVersionDetail {
    return AgentVersionDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentVersionDetail>, I>>(object: I): AgentVersionDetail {
    const message = createBaseAgentVersionDetail();
    message.version = object.version ?? "";
    message.labels = object.labels?.map((e) => e) || [];
    message.protocols = object.protocols?.map((e) => e) || [];
    message.status = object.status ?? "";
    message.publishPipelineInfo = object.publishPipelineInfo ?? "";
    message.author = object.author ?? "";
    message.changeDescription = object.changeDescription ?? "";
    message.contentDigest = object.contentDigest ?? "";
    message.createTime = object.createTime ?? 0;
    message.updateTime = object.updateTime ?? 0;
    message.namespaceId = object.namespaceId ?? "";
    message.agentName = object.agentName ?? "";
    message.callInterfaces = object.callInterfaces?.map((e) => AgentCallInterface.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
