// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v5.28.3
// source: ai/agentdiscoveryresult.proto

/* eslint-disable */
import { AgentDiscoveryCallInterface } from "./agentdiscoverycallinterface";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentDiscoveryResult"
 * Flattened from: AgentDiscoveryResult
 */
export interface AgentDiscoveryResult {
  namespaceId: string;
  agentName: string;
  version: string;
  contentDigest: string;
  callInterfaces: AgentDiscoveryCallInterface[];
}

function createBaseAgentDiscoveryResult(): AgentDiscoveryResult {
  return { namespaceId: "", agentName: "", version: "", contentDigest: "", callInterfaces: [] };
}

export const AgentDiscoveryResult: MessageFns<AgentDiscoveryResult> = {
  fromJSON(object: any): AgentDiscoveryResult {
    return {
      namespaceId: isSet(object.namespaceId) ? globalThis.String(object.namespaceId) : "",
      agentName: isSet(object.agentName) ? globalThis.String(object.agentName) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      contentDigest: isSet(object.contentDigest) ? globalThis.String(object.contentDigest) : "",
      callInterfaces: globalThis.Array.isArray(object?.callInterfaces)
        ? object.callInterfaces.map((e: any) => AgentDiscoveryCallInterface.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AgentDiscoveryResult): unknown {
    const obj: any = {};
    if (message.namespaceId !== "") {
      obj.namespaceId = message.namespaceId;
    }
    if (message.agentName !== "") {
      obj.agentName = message.agentName;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.contentDigest !== "") {
      obj.contentDigest = message.contentDigest;
    }
    if (message.callInterfaces?.length) {
      obj.callInterfaces = message.callInterfaces.map((e) => AgentDiscoveryCallInterface.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentDiscoveryResult>, I>>(base?: I): AgentDiscoveryResult {
    return AgentDiscoveryResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentDiscoveryResult>, I>>(object: I): AgentDiscoveryResult {
    const message = createBaseAgentDiscoveryResult();
    message.namespaceId = object.namespaceId ?? "";
    message.agentName = object.agentName ?? "";
    message.version = object.version ?? "";
    message.contentDigest = object.contentDigest ?? "";
    message.callInterfaces = object.callInterfaces?.map((e) => AgentDiscoveryCallInterface.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
