// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v5.28.3
// source: ai/agentendpointregistrationbatch.proto

/* eslint-disable */
import { Endpoint } from "./endpoint";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "AgentEndpointRegistrationBatch"
 * Flattened from: AgentEndpointRegistrationBatch
 */
export interface AgentEndpointRegistrationBatch {
  namespaceId: string;
  agentName: string;
  runtimeVersion: string;
  versionRange: string;
  protocol: string;
  endpoints: Endpoint[];
}

function createBaseAgentEndpointRegistrationBatch(): AgentEndpointRegistrationBatch {
  return { namespaceId: "", agentName: "", runtimeVersion: "", versionRange: "", protocol: "", endpoints: [] };
}

export const AgentEndpointRegistrationBatch: MessageFns<AgentEndpointRegistrationBatch> = {
  fromJSON(object: any): AgentEndpointRegistrationBatch {
    return {
      namespaceId: isSet(object.namespaceId) ? globalThis.String(object.namespaceId) : "",
      agentName: isSet(object.agentName) ? globalThis.String(object.agentName) : "",
      runtimeVersion: isSet(object.runtimeVersion) ? globalThis.String(object.runtimeVersion) : "",
      versionRange: isSet(object.versionRange) ? globalThis.String(object.versionRange) : "",
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
      endpoints: globalThis.Array.isArray(object?.endpoints)
        ? object.endpoints.map((e: any) => Endpoint.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AgentEndpointRegistrationBatch): unknown {
    const obj: any = {};
    if (message.namespaceId !== "") {
      obj.namespaceId = message.namespaceId;
    }
    if (message.agentName !== "") {
      obj.agentName = message.agentName;
    }
    if (message.runtimeVersion !== "") {
      obj.runtimeVersion = message.runtimeVersion;
    }
    if (message.versionRange !== "") {
      obj.versionRange = message.versionRange;
    }
    if (message.protocol !== "") {
      obj.protocol = message.protocol;
    }
    if (message.endpoints?.length) {
      obj.endpoints = message.endpoints.map((e) => Endpoint.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentEndpointRegistrationBatch>, I>>(base?: I): AgentEndpointRegistrationBatch {
    return AgentEndpointRegistrationBatch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentEndpointRegistrationBatch>, I>>(
    object: I,
  ): AgentEndpointRegistrationBatch {
    const message = createBaseAgentEndpointRegistrationBatch();
    message.namespaceId = object.namespaceId ?? "";
    message.agentName = object.agentName ?? "";
    message.runtimeVersion = object.runtimeVersion ?? "";
    message.versionRange = object.versionRange ?? "";
    message.protocol = object.protocol ?? "";
    message.endpoints = object.endpoints?.map((e) => Endpoint.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
