// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: ai/keyvalueinput.proto

/* eslint-disable */
import { Input } from "./input";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "KeyValueInput"
 * Flattened from: KeyValueInput -> InputWithVariables -> Input
 */
export interface KeyValueInput {
  description: string;
  isRequired: boolean;
  format: string;
  value: string;
  isSecret: boolean;
  defaultValue: string;
  choices: string[];
  placeholder: string;
  variables: { [key: string]: Input };
  name: string;
}

export interface KeyValueInput_VariablesEntry {
  key: string;
  value: Input | undefined;
}

function createBaseKeyValueInput(): KeyValueInput {
  return {
    description: "",
    isRequired: false,
    format: "",
    value: "",
    isSecret: false,
    defaultValue: "",
    choices: [],
    placeholder: "",
    variables: {},
    name: "",
  };
}

export const KeyValueInput: MessageFns<KeyValueInput> = {
  fromJSON(object: any): KeyValueInput {
    return {
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      isRequired: isSet(object.isRequired) ? globalThis.Boolean(object.isRequired) : false,
      format: isSet(object.format) ? globalThis.String(object.format) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      isSecret: isSet(object.isSecret) ? globalThis.Boolean(object.isSecret) : false,
      defaultValue: isSet(object.defaultValue) ? globalThis.String(object.defaultValue) : "",
      choices: globalThis.Array.isArray(object?.choices) ? object.choices.map((e: any) => globalThis.String(e)) : [],
      placeholder: isSet(object.placeholder) ? globalThis.String(object.placeholder) : "",
      variables: isObject(object.variables)
        ? (globalThis.Object.entries(object.variables) as [string, any][]).reduce(
          (acc: { [key: string]: Input }, [key, value]: [string, any]) => {
            acc[key] = Input.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: KeyValueInput): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.isRequired !== false) {
      obj.isRequired = message.isRequired;
    }
    if (message.format !== "") {
      obj.format = message.format;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.isSecret !== false) {
      obj.isSecret = message.isSecret;
    }
    if (message.defaultValue !== "") {
      obj.defaultValue = message.defaultValue;
    }
    if (message.choices?.length) {
      obj.choices = message.choices;
    }
    if (message.placeholder !== "") {
      obj.placeholder = message.placeholder;
    }
    if (message.variables) {
      const entries = globalThis.Object.entries(message.variables) as [string, Input][];
      if (entries.length > 0) {
        obj.variables = {};
        entries.forEach(([k, v]) => {
          obj.variables[k] = Input.toJSON(v);
        });
      }
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyValueInput>, I>>(base?: I): KeyValueInput {
    return KeyValueInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyValueInput>, I>>(object: I): KeyValueInput {
    const message = createBaseKeyValueInput();
    message.description = object.description ?? "";
    message.isRequired = object.isRequired ?? false;
    message.format = object.format ?? "";
    message.value = object.value ?? "";
    message.isSecret = object.isSecret ?? false;
    message.defaultValue = object.defaultValue ?? "";
    message.choices = object.choices?.map((e) => e) || [];
    message.placeholder = object.placeholder ?? "";
    message.variables = (globalThis.Object.entries(object.variables ?? {}) as [string, Input][]).reduce(
      (acc: { [key: string]: Input }, [key, value]: [string, Input]) => {
        if (value !== undefined) {
          acc[key] = Input.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseKeyValueInput_VariablesEntry(): KeyValueInput_VariablesEntry {
  return { key: "", value: undefined };
}

export const KeyValueInput_VariablesEntry: MessageFns<KeyValueInput_VariablesEntry> = {
  fromJSON(object: any): KeyValueInput_VariablesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Input.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: KeyValueInput_VariablesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Input.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyValueInput_VariablesEntry>, I>>(base?: I): KeyValueInput_VariablesEntry {
    return KeyValueInput_VariablesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyValueInput_VariablesEntry>, I>>(object: I): KeyValueInput_VariablesEntry {
    const message = createBaseKeyValueInput_VariablesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Input.fromPartial(object.value) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
