// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: ai/mcpendpointspec.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "McpEndpointSpec"
 * Flattened from: McpEndpointSpec
 */
export interface McpEndpointSpec {
  type: string;
  data: { [key: string]: string };
}

export interface McpEndpointSpec_DataEntry {
  key: string;
  value: string;
}

function createBaseMcpEndpointSpec(): McpEndpointSpec {
  return { type: "", data: {} };
}

export const McpEndpointSpec: MessageFns<McpEndpointSpec> = {
  fromJSON(object: any): McpEndpointSpec {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      data: isObject(object.data)
        ? (globalThis.Object.entries(object.data) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: McpEndpointSpec): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.data) {
      const entries = globalThis.Object.entries(message.data) as [string, string][];
      if (entries.length > 0) {
        obj.data = {};
        entries.forEach(([k, v]) => {
          obj.data[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpEndpointSpec>, I>>(base?: I): McpEndpointSpec {
    return McpEndpointSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpEndpointSpec>, I>>(object: I): McpEndpointSpec {
    const message = createBaseMcpEndpointSpec();
    message.type = object.type ?? "";
    message.data = (globalThis.Object.entries(object.data ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseMcpEndpointSpec_DataEntry(): McpEndpointSpec_DataEntry {
  return { key: "", value: "" };
}

export const McpEndpointSpec_DataEntry: MessageFns<McpEndpointSpec_DataEntry> = {
  fromJSON(object: any): McpEndpointSpec_DataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: McpEndpointSpec_DataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpEndpointSpec_DataEntry>, I>>(base?: I): McpEndpointSpec_DataEntry {
    return McpEndpointSpec_DataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpEndpointSpec_DataEntry>, I>>(object: I): McpEndpointSpec_DataEntry {
    const message = createBaseMcpEndpointSpec_DataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
