// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: ai/mcpendpointinfo.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "McpEndpointInfo"
 * Flattened from: McpEndpointInfo
 */
export interface McpEndpointInfo {
  protocol: string;
  address: string;
  port: number;
  path: string;
}

function createBaseMcpEndpointInfo(): McpEndpointInfo {
  return { protocol: "", address: "", port: 0, path: "" };
}

export const McpEndpointInfo: MessageFns<McpEndpointInfo> = {
  fromJSON(object: any): McpEndpointInfo {
    return {
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      path: isSet(object.path) ? globalThis.String(object.path) : "",
    };
  },

  toJSON(message: McpEndpointInfo): unknown {
    const obj: any = {};
    if (message.protocol !== "") {
      obj.protocol = message.protocol;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpEndpointInfo>, I>>(base?: I): McpEndpointInfo {
    return McpEndpointInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpEndpointInfo>, I>>(object: I): McpEndpointInfo {
    const message = createBaseMcpEndpointInfo();
    message.protocol = object.protocol ?? "";
    message.address = object.address ?? "";
    message.port = object.port ?? 0;
    message.path = object.path ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
