// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: ai/mcpserverremoteserviceconfig.proto

/* eslint-disable */
import { FrontEndpointConfig } from "./frontendpointconfig";
import { McpServiceRef } from "./mcpserviceref";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "McpServerRemoteServiceConfig"
 * Flattened from: McpServerRemoteServiceConfig
 */
export interface McpServerRemoteServiceConfig {
  serviceRef: McpServiceRef | undefined;
  exportPath: string;
  frontEndpointConfigList: FrontEndpointConfig[];
}

function createBaseMcpServerRemoteServiceConfig(): McpServerRemoteServiceConfig {
  return { serviceRef: undefined, exportPath: "", frontEndpointConfigList: [] };
}

export const McpServerRemoteServiceConfig: MessageFns<McpServerRemoteServiceConfig> = {
  fromJSON(object: any): McpServerRemoteServiceConfig {
    return {
      serviceRef: isSet(object.serviceRef) ? McpServiceRef.fromJSON(object.serviceRef) : undefined,
      exportPath: isSet(object.exportPath) ? globalThis.String(object.exportPath) : "",
      frontEndpointConfigList: globalThis.Array.isArray(object?.frontEndpointConfigList)
        ? object.frontEndpointConfigList.map((e: any) => FrontEndpointConfig.fromJSON(e))
        : [],
    };
  },

  toJSON(message: McpServerRemoteServiceConfig): unknown {
    const obj: any = {};
    if (message.serviceRef !== undefined) {
      obj.serviceRef = McpServiceRef.toJSON(message.serviceRef);
    }
    if (message.exportPath !== "") {
      obj.exportPath = message.exportPath;
    }
    if (message.frontEndpointConfigList?.length) {
      obj.frontEndpointConfigList = message.frontEndpointConfigList.map((e) => FrontEndpointConfig.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpServerRemoteServiceConfig>, I>>(base?: I): McpServerRemoteServiceConfig {
    return McpServerRemoteServiceConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpServerRemoteServiceConfig>, I>>(object: I): McpServerRemoteServiceConfig {
    const message = createBaseMcpServerRemoteServiceConfig();
    message.serviceRef = (object.serviceRef !== undefined && object.serviceRef !== null)
      ? McpServiceRef.fromPartial(object.serviceRef)
      : undefined;
    message.exportPath = object.exportPath ?? "";
    message.frontEndpointConfigList = object.frontEndpointConfigList?.map((e) => FrontEndpointConfig.fromPartial(e)) ||
      [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
