// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: ai/mcpserverbasicinfo.proto

/* eslint-disable */
import { Icon } from "./icon";
import { McpServerRemoteServiceConfig } from "./mcpserverremoteserviceconfig";
import { Package } from "./package";
import { Repository } from "./repository";
import { ServerVersionDetail } from "./serverversiondetail";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "McpServerBasicInfo"
 * Flattened from: McpServerBasicInfo
 */
export interface McpServerBasicInfo {
  namespaceId: string;
  id: string;
  name: string;
  protocol: string;
  frontProtocol: string;
  description: string;
  repository: Repository | undefined;
  packages: Package[];
  icons: Icon[];
  websiteUrl: string;
  versionDetail: ServerVersionDetail | undefined;
  version: string;
  remoteServerConfig: McpServerRemoteServiceConfig | undefined;
  localServerConfig: { [key: string]: any | undefined };
  enabled: boolean;
  status: string;
  capabilities: string[];
}

export interface McpServerBasicInfo_LocalServerConfigEntry {
  key: string;
  value: any | undefined;
}

function createBaseMcpServerBasicInfo(): McpServerBasicInfo {
  return {
    namespaceId: "",
    id: "",
    name: "",
    protocol: "",
    frontProtocol: "",
    description: "",
    repository: undefined,
    packages: [],
    icons: [],
    websiteUrl: "",
    versionDetail: undefined,
    version: "",
    remoteServerConfig: undefined,
    localServerConfig: {},
    enabled: false,
    status: "",
    capabilities: [],
  };
}

export const McpServerBasicInfo: MessageFns<McpServerBasicInfo> = {
  fromJSON(object: any): McpServerBasicInfo {
    return {
      namespaceId: isSet(object.namespaceId) ? globalThis.String(object.namespaceId) : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
      frontProtocol: isSet(object.frontProtocol) ? globalThis.String(object.frontProtocol) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      repository: isSet(object.repository) ? Repository.fromJSON(object.repository) : undefined,
      packages: globalThis.Array.isArray(object?.packages) ? object.packages.map((e: any) => Package.fromJSON(e)) : [],
      icons: globalThis.Array.isArray(object?.icons) ? object.icons.map((e: any) => Icon.fromJSON(e)) : [],
      websiteUrl: isSet(object.websiteUrl) ? globalThis.String(object.websiteUrl) : "",
      versionDetail: isSet(object.versionDetail) ? ServerVersionDetail.fromJSON(object.versionDetail) : undefined,
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      remoteServerConfig: isSet(object.remoteServerConfig)
        ? McpServerRemoteServiceConfig.fromJSON(object.remoteServerConfig)
        : undefined,
      localServerConfig: isObject(object.localServerConfig)
        ? (globalThis.Object.entries(object.localServerConfig) as [string, any][]).reduce(
          (acc: { [key: string]: any | undefined }, [key, value]: [string, any]) => {
            acc[key] = value as any | undefined;
            return acc;
          },
          {},
        )
        : {},
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      capabilities: globalThis.Array.isArray(object?.capabilities)
        ? object.capabilities.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: McpServerBasicInfo): unknown {
    const obj: any = {};
    if (message.namespaceId !== "") {
      obj.namespaceId = message.namespaceId;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.protocol !== "") {
      obj.protocol = message.protocol;
    }
    if (message.frontProtocol !== "") {
      obj.frontProtocol = message.frontProtocol;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.repository !== undefined) {
      obj.repository = Repository.toJSON(message.repository);
    }
    if (message.packages?.length) {
      obj.packages = message.packages.map((e) => Package.toJSON(e));
    }
    if (message.icons?.length) {
      obj.icons = message.icons.map((e) => Icon.toJSON(e));
    }
    if (message.websiteUrl !== "") {
      obj.websiteUrl = message.websiteUrl;
    }
    if (message.versionDetail !== undefined) {
      obj.versionDetail = ServerVersionDetail.toJSON(message.versionDetail);
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.remoteServerConfig !== undefined) {
      obj.remoteServerConfig = McpServerRemoteServiceConfig.toJSON(message.remoteServerConfig);
    }
    if (message.localServerConfig) {
      const entries = globalThis.Object.entries(message.localServerConfig) as [string, any | undefined][];
      if (entries.length > 0) {
        obj.localServerConfig = {};
        entries.forEach(([k, v]) => {
          obj.localServerConfig[k] = v;
        });
      }
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.capabilities?.length) {
      obj.capabilities = message.capabilities;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpServerBasicInfo>, I>>(base?: I): McpServerBasicInfo {
    return McpServerBasicInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpServerBasicInfo>, I>>(object: I): McpServerBasicInfo {
    const message = createBaseMcpServerBasicInfo();
    message.namespaceId = object.namespaceId ?? "";
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.protocol = object.protocol ?? "";
    message.frontProtocol = object.frontProtocol ?? "";
    message.description = object.description ?? "";
    message.repository = (object.repository !== undefined && object.repository !== null)
      ? Repository.fromPartial(object.repository)
      : undefined;
    message.packages = object.packages?.map((e) => Package.fromPartial(e)) || [];
    message.icons = object.icons?.map((e) => Icon.fromPartial(e)) || [];
    message.websiteUrl = object.websiteUrl ?? "";
    message.versionDetail = (object.versionDetail !== undefined && object.versionDetail !== null)
      ? ServerVersionDetail.fromPartial(object.versionDetail)
      : undefined;
    message.version = object.version ?? "";
    message.remoteServerConfig = (object.remoteServerConfig !== undefined && object.remoteServerConfig !== null)
      ? McpServerRemoteServiceConfig.fromPartial(object.remoteServerConfig)
      : undefined;
    message.localServerConfig =
      (globalThis.Object.entries(object.localServerConfig ?? {}) as [string, any | undefined][]).reduce(
        (acc: { [key: string]: any | undefined }, [key, value]: [string, any | undefined]) => {
          if (value !== undefined) {
            acc[key] = value;
          }
          return acc;
        },
        {},
      );
    message.enabled = object.enabled ?? false;
    message.status = object.status ?? "";
    message.capabilities = object.capabilities?.map((e) => e) || [];
    return message;
  },
};

function createBaseMcpServerBasicInfo_LocalServerConfigEntry(): McpServerBasicInfo_LocalServerConfigEntry {
  return { key: "", value: undefined };
}

export const McpServerBasicInfo_LocalServerConfigEntry: MessageFns<McpServerBasicInfo_LocalServerConfigEntry> = {
  fromJSON(object: any): McpServerBasicInfo_LocalServerConfigEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: McpServerBasicInfo_LocalServerConfigEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpServerBasicInfo_LocalServerConfigEntry>, I>>(
    base?: I,
  ): McpServerBasicInfo_LocalServerConfigEntry {
    return McpServerBasicInfo_LocalServerConfigEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpServerBasicInfo_LocalServerConfigEntry>, I>>(
    object: I,
  ): McpServerBasicInfo_LocalServerConfigEntry {
    const message = createBaseMcpServerBasicInfo_LocalServerConfigEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
