// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: ai/mcptoolmeta.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "McpToolMeta"
 * Flattened from: McpToolMeta
 */
export interface McpToolMeta {
  invokeContext: { [key: string]: string };
  enabled: boolean;
  templates: { [key: string]: any | undefined };
}

export interface McpToolMeta_InvokeContextEntry {
  key: string;
  value: string;
}

export interface McpToolMeta_TemplatesEntry {
  key: string;
  value: any | undefined;
}

function createBaseMcpToolMeta(): McpToolMeta {
  return { invokeContext: {}, enabled: false, templates: {} };
}

export const McpToolMeta: MessageFns<McpToolMeta> = {
  fromJSON(object: any): McpToolMeta {
    return {
      invokeContext: isObject(object.invokeContext)
        ? (globalThis.Object.entries(object.invokeContext) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      templates: isObject(object.templates)
        ? (globalThis.Object.entries(object.templates) as [string, any][]).reduce(
          (acc: { [key: string]: any | undefined }, [key, value]: [string, any]) => {
            acc[key] = value as any | undefined;
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: McpToolMeta): unknown {
    const obj: any = {};
    if (message.invokeContext) {
      const entries = globalThis.Object.entries(message.invokeContext) as [string, string][];
      if (entries.length > 0) {
        obj.invokeContext = {};
        entries.forEach(([k, v]) => {
          obj.invokeContext[k] = v;
        });
      }
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.templates) {
      const entries = globalThis.Object.entries(message.templates) as [string, any | undefined][];
      if (entries.length > 0) {
        obj.templates = {};
        entries.forEach(([k, v]) => {
          obj.templates[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpToolMeta>, I>>(base?: I): McpToolMeta {
    return McpToolMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpToolMeta>, I>>(object: I): McpToolMeta {
    const message = createBaseMcpToolMeta();
    message.invokeContext = (globalThis.Object.entries(object.invokeContext ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.enabled = object.enabled ?? false;
    message.templates = (globalThis.Object.entries(object.templates ?? {}) as [string, any | undefined][]).reduce(
      (acc: { [key: string]: any | undefined }, [key, value]: [string, any | undefined]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseMcpToolMeta_InvokeContextEntry(): McpToolMeta_InvokeContextEntry {
  return { key: "", value: "" };
}

export const McpToolMeta_InvokeContextEntry: MessageFns<McpToolMeta_InvokeContextEntry> = {
  fromJSON(object: any): McpToolMeta_InvokeContextEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: McpToolMeta_InvokeContextEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpToolMeta_InvokeContextEntry>, I>>(base?: I): McpToolMeta_InvokeContextEntry {
    return McpToolMeta_InvokeContextEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpToolMeta_InvokeContextEntry>, I>>(
    object: I,
  ): McpToolMeta_InvokeContextEntry {
    const message = createBaseMcpToolMeta_InvokeContextEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseMcpToolMeta_TemplatesEntry(): McpToolMeta_TemplatesEntry {
  return { key: "", value: undefined };
}

export const McpToolMeta_TemplatesEntry: MessageFns<McpToolMeta_TemplatesEntry> = {
  fromJSON(object: any): McpToolMeta_TemplatesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: McpToolMeta_TemplatesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpToolMeta_TemplatesEntry>, I>>(base?: I): McpToolMeta_TemplatesEntry {
    return McpToolMeta_TemplatesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpToolMeta_TemplatesEntry>, I>>(object: I): McpToolMeta_TemplatesEntry {
    const message = createBaseMcpToolMeta_TemplatesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
