// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: ai/mcptool.proto

/* eslint-disable */
import { McpToolAnnotations } from "./mcptoolannotations";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "McpTool"
 * Flattened from: McpTool
 */
export interface McpTool {
  name: string;
  description: string;
  inputSchema: { [key: string]: any | undefined };
  outputSchema: { [key: string]: any | undefined };
  meta: { [key: string]: any | undefined };
  annotations: McpToolAnnotations | undefined;
}

export interface McpTool_InputSchemaEntry {
  key: string;
  value: any | undefined;
}

export interface McpTool_OutputSchemaEntry {
  key: string;
  value: any | undefined;
}

export interface McpTool_MetaEntry {
  key: string;
  value: any | undefined;
}

function createBaseMcpTool(): McpTool {
  return { name: "", description: "", inputSchema: {}, outputSchema: {}, meta: {}, annotations: undefined };
}

export const McpTool: MessageFns<McpTool> = {
  fromJSON(object: any): McpTool {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      inputSchema: isObject(object.inputSchema)
        ? (globalThis.Object.entries(object.inputSchema) as [string, any][]).reduce(
          (acc: { [key: string]: any | undefined }, [key, value]: [string, any]) => {
            acc[key] = value as any | undefined;
            return acc;
          },
          {},
        )
        : {},
      outputSchema: isObject(object.outputSchema)
        ? (globalThis.Object.entries(object.outputSchema) as [string, any][]).reduce(
          (acc: { [key: string]: any | undefined }, [key, value]: [string, any]) => {
            acc[key] = value as any | undefined;
            return acc;
          },
          {},
        )
        : {},
      meta: isObject(object.meta)
        ? (globalThis.Object.entries(object.meta) as [string, any][]).reduce(
          (acc: { [key: string]: any | undefined }, [key, value]: [string, any]) => {
            acc[key] = value as any | undefined;
            return acc;
          },
          {},
        )
        : {},
      annotations: isSet(object.annotations) ? McpToolAnnotations.fromJSON(object.annotations) : undefined,
    };
  },

  toJSON(message: McpTool): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.inputSchema) {
      const entries = globalThis.Object.entries(message.inputSchema) as [string, any | undefined][];
      if (entries.length > 0) {
        obj.inputSchema = {};
        entries.forEach(([k, v]) => {
          obj.inputSchema[k] = v;
        });
      }
    }
    if (message.outputSchema) {
      const entries = globalThis.Object.entries(message.outputSchema) as [string, any | undefined][];
      if (entries.length > 0) {
        obj.outputSchema = {};
        entries.forEach(([k, v]) => {
          obj.outputSchema[k] = v;
        });
      }
    }
    if (message.meta) {
      const entries = globalThis.Object.entries(message.meta) as [string, any | undefined][];
      if (entries.length > 0) {
        obj.meta = {};
        entries.forEach(([k, v]) => {
          obj.meta[k] = v;
        });
      }
    }
    if (message.annotations !== undefined) {
      obj.annotations = McpToolAnnotations.toJSON(message.annotations);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpTool>, I>>(base?: I): McpTool {
    return McpTool.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpTool>, I>>(object: I): McpTool {
    const message = createBaseMcpTool();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.inputSchema = (globalThis.Object.entries(object.inputSchema ?? {}) as [string, any | undefined][]).reduce(
      (acc: { [key: string]: any | undefined }, [key, value]: [string, any | undefined]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.outputSchema = (globalThis.Object.entries(object.outputSchema ?? {}) as [string, any | undefined][]).reduce(
      (acc: { [key: string]: any | undefined }, [key, value]: [string, any | undefined]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.meta = (globalThis.Object.entries(object.meta ?? {}) as [string, any | undefined][]).reduce(
      (acc: { [key: string]: any | undefined }, [key, value]: [string, any | undefined]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.annotations = (object.annotations !== undefined && object.annotations !== null)
      ? McpToolAnnotations.fromPartial(object.annotations)
      : undefined;
    return message;
  },
};

function createBaseMcpTool_InputSchemaEntry(): McpTool_InputSchemaEntry {
  return { key: "", value: undefined };
}

export const McpTool_InputSchemaEntry: MessageFns<McpTool_InputSchemaEntry> = {
  fromJSON(object: any): McpTool_InputSchemaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: McpTool_InputSchemaEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpTool_InputSchemaEntry>, I>>(base?: I): McpTool_InputSchemaEntry {
    return McpTool_InputSchemaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpTool_InputSchemaEntry>, I>>(object: I): McpTool_InputSchemaEntry {
    const message = createBaseMcpTool_InputSchemaEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseMcpTool_OutputSchemaEntry(): McpTool_OutputSchemaEntry {
  return { key: "", value: undefined };
}

export const McpTool_OutputSchemaEntry: MessageFns<McpTool_OutputSchemaEntry> = {
  fromJSON(object: any): McpTool_OutputSchemaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: McpTool_OutputSchemaEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpTool_OutputSchemaEntry>, I>>(base?: I): McpTool_OutputSchemaEntry {
    return McpTool_OutputSchemaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpTool_OutputSchemaEntry>, I>>(object: I): McpTool_OutputSchemaEntry {
    const message = createBaseMcpTool_OutputSchemaEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseMcpTool_MetaEntry(): McpTool_MetaEntry {
  return { key: "", value: undefined };
}

export const McpTool_MetaEntry: MessageFns<McpTool_MetaEntry> = {
  fromJSON(object: any): McpTool_MetaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: McpTool_MetaEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpTool_MetaEntry>, I>>(base?: I): McpTool_MetaEntry {
    return McpTool_MetaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpTool_MetaEntry>, I>>(object: I): McpTool_MetaEntry {
    const message = createBaseMcpTool_MetaEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
