// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: ai/mcptoolannotations.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "McpToolAnnotations"
 * Flattened from: McpToolAnnotations
 */
export interface McpToolAnnotations {
  title: string;
  readOnlyHint: boolean;
  destructiveHint: boolean;
  idempotentHint: boolean;
  openWorldHint: boolean;
}

function createBaseMcpToolAnnotations(): McpToolAnnotations {
  return { title: "", readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };
}

export const McpToolAnnotations: MessageFns<McpToolAnnotations> = {
  fromJSON(object: any): McpToolAnnotations {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      readOnlyHint: isSet(object.readOnlyHint) ? globalThis.Boolean(object.readOnlyHint) : false,
      destructiveHint: isSet(object.destructiveHint) ? globalThis.Boolean(object.destructiveHint) : false,
      idempotentHint: isSet(object.idempotentHint) ? globalThis.Boolean(object.idempotentHint) : false,
      openWorldHint: isSet(object.openWorldHint) ? globalThis.Boolean(object.openWorldHint) : false,
    };
  },

  toJSON(message: McpToolAnnotations): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.readOnlyHint !== false) {
      obj.readOnlyHint = message.readOnlyHint;
    }
    if (message.destructiveHint !== false) {
      obj.destructiveHint = message.destructiveHint;
    }
    if (message.idempotentHint !== false) {
      obj.idempotentHint = message.idempotentHint;
    }
    if (message.openWorldHint !== false) {
      obj.openWorldHint = message.openWorldHint;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<McpToolAnnotations>, I>>(base?: I): McpToolAnnotations {
    return McpToolAnnotations.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<McpToolAnnotations>, I>>(object: I): McpToolAnnotations {
    const message = createBaseMcpToolAnnotations();
    message.title = object.title ?? "";
    message.readOnlyHint = object.readOnlyHint ?? false;
    message.destructiveHint = object.destructiveHint ?? false;
    message.idempotentHint = object.idempotentHint ?? false;
    message.openWorldHint = object.openWorldHint ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
