// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: ai/package.proto

/* eslint-disable */
import { Argument } from "./argument";
import { KeyValueInput } from "./keyvalueinput";

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "Package"
 * Flattened from: Package
 */
export interface Package {
  registryType: string;
  registryBaseUrl: string;
  identifier: string;
  version: string;
  fileSha256: string;
  runtimeHint: string;
  runtimeArguments: Argument[];
  packageArguments: Argument[];
  environmentVariables: KeyValueInput[];
  transport: any | undefined;
}

function createBasePackage(): Package {
  return {
    registryType: "",
    registryBaseUrl: "",
    identifier: "",
    version: "",
    fileSha256: "",
    runtimeHint: "",
    runtimeArguments: [],
    packageArguments: [],
    environmentVariables: [],
    transport: undefined,
  };
}

export const Package: MessageFns<Package> = {
  fromJSON(object: any): Package {
    return {
      registryType: isSet(object.registryType) ? globalThis.String(object.registryType) : "",
      registryBaseUrl: isSet(object.registryBaseUrl) ? globalThis.String(object.registryBaseUrl) : "",
      identifier: isSet(object.identifier) ? globalThis.String(object.identifier) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      fileSha256: isSet(object.fileSha256) ? globalThis.String(object.fileSha256) : "",
      runtimeHint: isSet(object.runtimeHint) ? globalThis.String(object.runtimeHint) : "",
      runtimeArguments: globalThis.Array.isArray(object?.runtimeArguments)
        ? object.runtimeArguments.map((e: any) => Argument.fromJSON(e))
        : [],
      packageArguments: globalThis.Array.isArray(object?.packageArguments)
        ? object.packageArguments.map((e: any) => Argument.fromJSON(e))
        : [],
      environmentVariables: globalThis.Array.isArray(object?.environmentVariables)
        ? object.environmentVariables.map((e: any) => KeyValueInput.fromJSON(e))
        : [],
      transport: isSet(object?.transport) ? object.transport : undefined,
    };
  },

  toJSON(message: Package): unknown {
    const obj: any = {};
    if (message.registryType !== "") {
      obj.registryType = message.registryType;
    }
    if (message.registryBaseUrl !== "") {
      obj.registryBaseUrl = message.registryBaseUrl;
    }
    if (message.identifier !== "") {
      obj.identifier = message.identifier;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.fileSha256 !== "") {
      obj.fileSha256 = message.fileSha256;
    }
    if (message.runtimeHint !== "") {
      obj.runtimeHint = message.runtimeHint;
    }
    if (message.runtimeArguments?.length) {
      obj.runtimeArguments = message.runtimeArguments.map((e) => Argument.toJSON(e));
    }
    if (message.packageArguments?.length) {
      obj.packageArguments = message.packageArguments.map((e) => Argument.toJSON(e));
    }
    if (message.environmentVariables?.length) {
      obj.environmentVariables = message.environmentVariables.map((e) => KeyValueInput.toJSON(e));
    }
    if (message.transport !== undefined) {
      obj.transport = message.transport;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Package>, I>>(base?: I): Package {
    return Package.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Package>, I>>(object: I): Package {
    const message = createBasePackage();
    message.registryType = object.registryType ?? "";
    message.registryBaseUrl = object.registryBaseUrl ?? "";
    message.identifier = object.identifier ?? "";
    message.version = object.version ?? "";
    message.fileSha256 = object.fileSha256 ?? "";
    message.runtimeHint = object.runtimeHint ?? "";
    message.runtimeArguments = object.runtimeArguments?.map((e) => Argument.fromPartial(e)) || [];
    message.packageArguments = object.packageArguments?.map((e) => Argument.fromPartial(e)) || [];
    message.environmentVariables = object.environmentVariables?.map((e) => KeyValueInput.fromPartial(e)) || [];
    message.transport = object.transport ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
