// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v5.28.3
// source: ai/runtimeversionbinding.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "RuntimeVersionBinding"
 * Flattened from: RuntimeVersionBinding
 */
export interface RuntimeVersionBinding {
  runtimeVersion: string;
  versionRange: string;
}

function createBaseRuntimeVersionBinding(): RuntimeVersionBinding {
  return { runtimeVersion: "", versionRange: "" };
}

export const RuntimeVersionBinding: MessageFns<RuntimeVersionBinding> = {
  fromJSON(object: any): RuntimeVersionBinding {
    return {
      runtimeVersion: isSet(object.runtimeVersion) ? globalThis.String(object.runtimeVersion) : "",
      versionRange: isSet(object.versionRange) ? globalThis.String(object.versionRange) : "",
    };
  },

  toJSON(message: RuntimeVersionBinding): unknown {
    const obj: any = {};
    if (message.runtimeVersion !== "") {
      obj.runtimeVersion = message.runtimeVersion;
    }
    if (message.versionRange !== "") {
      obj.versionRange = message.versionRange;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RuntimeVersionBinding>, I>>(base?: I): RuntimeVersionBinding {
    return RuntimeVersionBinding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RuntimeVersionBinding>, I>>(object: I): RuntimeVersionBinding {
    const message = createBaseRuntimeVersionBinding();
    message.runtimeVersion = object.runtimeVersion ?? "";
    message.versionRange = object.versionRange ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
