// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: config/config_request.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "ClientConfigMetricRequest"
// Flattened from: ClientConfigMetricRequest -> ServerRequest -> Request
type ClientConfigMetricRequest struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	RequestId     string                                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	MetricsKeys   []*ClientConfigMetricRequestMetricsKey `protobuf:"bytes,2,rep,name=metricsKeys,proto3" json:"metricsKeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfigMetricRequest) Reset() {
	*x = ClientConfigMetricRequest{}
	mi := &file_config_config_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfigMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigMetricRequest) ProtoMessage() {}

func (x *ClientConfigMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigMetricRequest.ProtoReflect.Descriptor instead.
func (*ClientConfigMetricRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfigMetricRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientConfigMetricRequest) GetMetricsKeys() []*ClientConfigMetricRequestMetricsKey {
	if x != nil {
		return x.MetricsKeys
	}
	return nil
}

// metadata.type = "ClientConfigMetricRequestMetricsKey"
// Flattened from: MetricsKey
type ClientConfigMetricRequestMetricsKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfigMetricRequestMetricsKey) Reset() {
	*x = ClientConfigMetricRequestMetricsKey{}
	mi := &file_config_config_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfigMetricRequestMetricsKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigMetricRequestMetricsKey) ProtoMessage() {}

func (x *ClientConfigMetricRequestMetricsKey) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigMetricRequestMetricsKey.ProtoReflect.Descriptor instead.
func (*ClientConfigMetricRequestMetricsKey) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfigMetricRequestMetricsKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientConfigMetricRequestMetricsKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// metadata.type = "ConfigBatchListenRequest"
// Flattened from: ConfigBatchListenRequest -> AbstractConfigRequest -> Request
type ConfigBatchListenRequest struct {
	state                protoimpl.MessageState                         `protogen:"open.v1"`
	RequestId            string                                         `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId               string                                         `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group                string                                         `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant               string                                         `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Listen               bool                                           `protobuf:"varint,5,opt,name=listen,proto3" json:"listen,omitempty"`
	ConfigListenContexts []*ConfigBatchListenRequestConfigListenContext `protobuf:"bytes,6,rep,name=configListenContexts,proto3" json:"configListenContexts,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConfigBatchListenRequest) Reset() {
	*x = ConfigBatchListenRequest{}
	mi := &file_config_config_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigBatchListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigBatchListenRequest) ProtoMessage() {}

func (x *ConfigBatchListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigBatchListenRequest.ProtoReflect.Descriptor instead.
func (*ConfigBatchListenRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigBatchListenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetListen() bool {
	if x != nil {
		return x.Listen
	}
	return false
}

func (x *ConfigBatchListenRequest) GetConfigListenContexts() []*ConfigBatchListenRequestConfigListenContext {
	if x != nil {
		return x.ConfigListenContexts
	}
	return nil
}

// metadata.type = "ConfigBatchListenRequestConfigListenContext"
// Flattened from: ConfigListenContext
type ConfigBatchListenRequestConfigListenContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Md5           string                 `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigBatchListenRequestConfigListenContext) Reset() {
	*x = ConfigBatchListenRequestConfigListenContext{}
	mi := &file_config_config_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigBatchListenRequestConfigListenContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigBatchListenRequestConfigListenContext) ProtoMessage() {}

func (x *ConfigBatchListenRequestConfigListenContext) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigBatchListenRequestConfigListenContext.ProtoReflect.Descriptor instead.
func (*ConfigBatchListenRequestConfigListenContext) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigBatchListenRequestConfigListenContext) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigBatchListenRequestConfigListenContext) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ConfigBatchListenRequestConfigListenContext) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigBatchListenRequestConfigListenContext) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// metadata.type = "ConfigChangeClusterSyncRequest"
// Flattened from: ConfigChangeClusterSyncRequest -> AbstractConfigRequest -> Request
type ConfigChangeClusterSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	LastModified  int64                  `protobuf:"varint,5,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	GrayName      string                 `protobuf:"bytes,6,opt,name=grayName,proto3" json:"grayName,omitempty"`
	IsBeta        bool                   `protobuf:"varint,7,opt,name=isBeta,json=beta,proto3" json:"isBeta,omitempty"`
	Tag           string                 `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeClusterSyncRequest) Reset() {
	*x = ConfigChangeClusterSyncRequest{}
	mi := &file_config_config_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeClusterSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeClusterSyncRequest) ProtoMessage() {}

func (x *ConfigChangeClusterSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeClusterSyncRequest.ProtoReflect.Descriptor instead.
func (*ConfigChangeClusterSyncRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigChangeClusterSyncRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigChangeClusterSyncRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigChangeClusterSyncRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigChangeClusterSyncRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigChangeClusterSyncRequest) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *ConfigChangeClusterSyncRequest) GetGrayName() string {
	if x != nil {
		return x.GrayName
	}
	return ""
}

func (x *ConfigChangeClusterSyncRequest) GetIsBeta() bool {
	if x != nil {
		return x.IsBeta
	}
	return false
}

func (x *ConfigChangeClusterSyncRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// metadata.type = "ConfigChangeNotifyRequest"
// Flattened from: ConfigChangeNotifyRequest -> ServerRequest -> Request
type ConfigChangeNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeNotifyRequest) Reset() {
	*x = ConfigChangeNotifyRequest{}
	mi := &file_config_config_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeNotifyRequest) ProtoMessage() {}

func (x *ConfigChangeNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeNotifyRequest.ProtoReflect.Descriptor instead.
func (*ConfigChangeNotifyRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigChangeNotifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigChangeNotifyRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigChangeNotifyRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigChangeNotifyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// metadata.type = "ConfigFuzzyWatchChangeNotifyRequest"
// Flattened from: ConfigFuzzyWatchChangeNotifyRequest -> AbstractFuzzyWatchNotifyRequest -> ServerRequest -> Request
type ConfigFuzzyWatchChangeNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	GroupKey      string                 `protobuf:"bytes,2,opt,name=groupKey,proto3" json:"groupKey,omitempty"`
	ChangeType    string                 `protobuf:"bytes,3,opt,name=changeType,proto3" json:"changeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFuzzyWatchChangeNotifyRequest) Reset() {
	*x = ConfigFuzzyWatchChangeNotifyRequest{}
	mi := &file_config_config_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFuzzyWatchChangeNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFuzzyWatchChangeNotifyRequest) ProtoMessage() {}

func (x *ConfigFuzzyWatchChangeNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFuzzyWatchChangeNotifyRequest.ProtoReflect.Descriptor instead.
func (*ConfigFuzzyWatchChangeNotifyRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigFuzzyWatchChangeNotifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigFuzzyWatchChangeNotifyRequest) GetGroupKey() string {
	if x != nil {
		return x.GroupKey
	}
	return ""
}

func (x *ConfigFuzzyWatchChangeNotifyRequest) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

// metadata.type = "ConfigFuzzyWatchRequest"
// Flattened from: ConfigFuzzyWatchRequest -> Request
type ConfigFuzzyWatchRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	GroupKeyPattern   string                 `protobuf:"bytes,2,opt,name=groupKeyPattern,proto3" json:"groupKeyPattern,omitempty"`
	ReceivedGroupKeys []string               `protobuf:"bytes,3,rep,name=receivedGroupKeys,proto3" json:"receivedGroupKeys,omitempty"`
	WatchType         string                 `protobuf:"bytes,4,opt,name=watchType,proto3" json:"watchType,omitempty"`
	IsInitializing    bool                   `protobuf:"varint,5,opt,name=isInitializing,json=initializing,proto3" json:"isInitializing,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigFuzzyWatchRequest) Reset() {
	*x = ConfigFuzzyWatchRequest{}
	mi := &file_config_config_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFuzzyWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFuzzyWatchRequest) ProtoMessage() {}

func (x *ConfigFuzzyWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFuzzyWatchRequest.ProtoReflect.Descriptor instead.
func (*ConfigFuzzyWatchRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigFuzzyWatchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigFuzzyWatchRequest) GetGroupKeyPattern() string {
	if x != nil {
		return x.GroupKeyPattern
	}
	return ""
}

func (x *ConfigFuzzyWatchRequest) GetReceivedGroupKeys() []string {
	if x != nil {
		return x.ReceivedGroupKeys
	}
	return nil
}

func (x *ConfigFuzzyWatchRequest) GetWatchType() string {
	if x != nil {
		return x.WatchType
	}
	return ""
}

func (x *ConfigFuzzyWatchRequest) GetIsInitializing() bool {
	if x != nil {
		return x.IsInitializing
	}
	return false
}

// metadata.type = "ConfigFuzzyWatchSyncRequest"
// Flattened from: ConfigFuzzyWatchSyncRequest -> AbstractFuzzyWatchNotifyRequest -> ServerRequest -> Request
type ConfigFuzzyWatchSyncRequest struct {
	state           protoimpl.MessageState                `protogen:"open.v1"`
	RequestId       string                                `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	GroupKeyPattern string                                `protobuf:"bytes,2,opt,name=groupKeyPattern,proto3" json:"groupKeyPattern,omitempty"`
	Contexts        []*ConfigFuzzyWatchSyncRequestContext `protobuf:"bytes,3,rep,name=contexts,proto3" json:"contexts,omitempty"`
	SyncType        string                                `protobuf:"bytes,4,opt,name=syncType,proto3" json:"syncType,omitempty"`
	TotalBatch      int32                                 `protobuf:"varint,5,opt,name=totalBatch,proto3" json:"totalBatch,omitempty"`
	CurrentBatch    int32                                 `protobuf:"varint,6,opt,name=currentBatch,proto3" json:"currentBatch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigFuzzyWatchSyncRequest) Reset() {
	*x = ConfigFuzzyWatchSyncRequest{}
	mi := &file_config_config_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFuzzyWatchSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFuzzyWatchSyncRequest) ProtoMessage() {}

func (x *ConfigFuzzyWatchSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFuzzyWatchSyncRequest.ProtoReflect.Descriptor instead.
func (*ConfigFuzzyWatchSyncRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigFuzzyWatchSyncRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigFuzzyWatchSyncRequest) GetGroupKeyPattern() string {
	if x != nil {
		return x.GroupKeyPattern
	}
	return ""
}

func (x *ConfigFuzzyWatchSyncRequest) GetContexts() []*ConfigFuzzyWatchSyncRequestContext {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *ConfigFuzzyWatchSyncRequest) GetSyncType() string {
	if x != nil {
		return x.SyncType
	}
	return ""
}

func (x *ConfigFuzzyWatchSyncRequest) GetTotalBatch() int32 {
	if x != nil {
		return x.TotalBatch
	}
	return 0
}

func (x *ConfigFuzzyWatchSyncRequest) GetCurrentBatch() int32 {
	if x != nil {
		return x.CurrentBatch
	}
	return 0
}

// metadata.type = "ConfigFuzzyWatchSyncRequestContext"
// Flattened from: Context
type ConfigFuzzyWatchSyncRequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupKey      string                 `protobuf:"bytes,1,opt,name=groupKey,proto3" json:"groupKey,omitempty"`
	ChangedType   string                 `protobuf:"bytes,2,opt,name=changedType,proto3" json:"changedType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFuzzyWatchSyncRequestContext) Reset() {
	*x = ConfigFuzzyWatchSyncRequestContext{}
	mi := &file_config_config_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFuzzyWatchSyncRequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFuzzyWatchSyncRequestContext) ProtoMessage() {}

func (x *ConfigFuzzyWatchSyncRequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFuzzyWatchSyncRequestContext.ProtoReflect.Descriptor instead.
func (*ConfigFuzzyWatchSyncRequestContext) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigFuzzyWatchSyncRequestContext) GetGroupKey() string {
	if x != nil {
		return x.GroupKey
	}
	return ""
}

func (x *ConfigFuzzyWatchSyncRequestContext) GetChangedType() string {
	if x != nil {
		return x.ChangedType
	}
	return ""
}

// metadata.type = "ConfigPublishRequest"
// Flattened from: ConfigPublishRequest -> AbstractConfigRequest -> Request
type ConfigPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CasMd5        string                 `protobuf:"bytes,6,opt,name=casMd5,proto3" json:"casMd5,omitempty"`
	AdditionMap   map[string]string      `protobuf:"bytes,7,rep,name=additionMap,proto3" json:"additionMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPublishRequest) Reset() {
	*x = ConfigPublishRequest{}
	mi := &file_config_config_request_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPublishRequest) ProtoMessage() {}

func (x *ConfigPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPublishRequest.ProtoReflect.Descriptor instead.
func (*ConfigPublishRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigPublishRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPublishRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigPublishRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigPublishRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigPublishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigPublishRequest) GetCasMd5() string {
	if x != nil {
		return x.CasMd5
	}
	return ""
}

func (x *ConfigPublishRequest) GetAdditionMap() map[string]string {
	if x != nil {
		return x.AdditionMap
	}
	return nil
}

// metadata.type = "ConfigQueryRequest"
// Flattened from: ConfigQueryRequest -> AbstractConfigRequest -> Request
type ConfigQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigQueryRequest) Reset() {
	*x = ConfigQueryRequest{}
	mi := &file_config_config_request_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQueryRequest) ProtoMessage() {}

func (x *ConfigQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQueryRequest.ProtoReflect.Descriptor instead.
func (*ConfigQueryRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigQueryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigQueryRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigQueryRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigQueryRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigQueryRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// metadata.type = "ConfigRemoveRequest"
// Flattened from: ConfigRemoveRequest -> AbstractConfigRequest -> Request
type ConfigRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRemoveRequest) Reset() {
	*x = ConfigRemoveRequest{}
	mi := &file_config_config_request_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRemoveRequest) ProtoMessage() {}

func (x *ConfigRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRemoveRequest.ProtoReflect.Descriptor instead.
func (*ConfigRemoveRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigRemoveRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigRemoveRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigRemoveRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigRemoveRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigRemoveRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_config_config_request_proto protoreflect.FileDescriptor

const file_config_config_request_proto_rawDesc = "" +
	"\n" +
	"\x1bconfig/config_request.proto\x12\fnacos.config\"\x8e\x01\n" +
	"\x19ClientConfigMetricRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12S\n" +
	"\vmetricsKeys\x18\x02 \x03(\v21.nacos.config.ClientConfigMetricRequestMetricsKeyR\vmetricsKeys\"K\n" +
	"#ClientConfigMetricRequestMetricsKey\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x85\x02\n" +
	"\x18ConfigBatchListenRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06listen\x18\x05 \x01(\bR\x06listen\x12m\n" +
	"\x14configListenContexts\x18\x06 \x03(\v29.nacos.config.ConfigBatchListenRequestConfigListenContextR\x14configListenContexts\"\x85\x01\n" +
	"+ConfigBatchListenRequestConfigListenContext\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03md5\x18\x02 \x01(\tR\x03md5\x12\x16\n" +
	"\x06dataId\x18\x03 \x01(\tR\x06dataId\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\"\xec\x01\n" +
	"\x1eConfigChangeClusterSyncRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\"\n" +
	"\flastModified\x18\x05 \x01(\x03R\flastModified\x12\x1a\n" +
	"\bgrayName\x18\x06 \x01(\tR\bgrayName\x12\x14\n" +
	"\x06isBeta\x18\a \x01(\bR\x04beta\x12\x10\n" +
	"\x03tag\x18\b \x01(\tR\x03tag\"\x7f\n" +
	"\x19ConfigChangeNotifyRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\"\x7f\n" +
	"#ConfigFuzzyWatchChangeNotifyRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bgroupKey\x18\x02 \x01(\tR\bgroupKey\x12\x1e\n" +
	"\n" +
	"changeType\x18\x03 \x01(\tR\n" +
	"changeType\"\xd3\x01\n" +
	"\x17ConfigFuzzyWatchRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12(\n" +
	"\x0fgroupKeyPattern\x18\x02 \x01(\tR\x0fgroupKeyPattern\x12,\n" +
	"\x11receivedGroupKeys\x18\x03 \x03(\tR\x11receivedGroupKeys\x12\x1c\n" +
	"\twatchType\x18\x04 \x01(\tR\twatchType\x12$\n" +
	"\x0eisInitializing\x18\x05 \x01(\bR\finitializing\"\x93\x02\n" +
	"\x1bConfigFuzzyWatchSyncRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12(\n" +
	"\x0fgroupKeyPattern\x18\x02 \x01(\tR\x0fgroupKeyPattern\x12L\n" +
	"\bcontexts\x18\x03 \x03(\v20.nacos.config.ConfigFuzzyWatchSyncRequestContextR\bcontexts\x12\x1a\n" +
	"\bsyncType\x18\x04 \x01(\tR\bsyncType\x12\x1e\n" +
	"\n" +
	"totalBatch\x18\x05 \x01(\x05R\n" +
	"totalBatch\x12\"\n" +
	"\fcurrentBatch\x18\x06 \x01(\x05R\fcurrentBatch\"b\n" +
	"\"ConfigFuzzyWatchSyncRequestContext\x12\x1a\n" +
	"\bgroupKey\x18\x01 \x01(\tR\bgroupKey\x12 \n" +
	"\vchangedType\x18\x02 \x01(\tR\vchangedType\"\xc3\x02\n" +
	"\x14ConfigPublishRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06casMd5\x18\x06 \x01(\tR\x06casMd5\x12U\n" +
	"\vadditionMap\x18\a \x03(\v23.nacos.config.ConfigPublishRequest.AdditionMapEntryR\vadditionMap\x1a>\n" +
	"\x10AdditionMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x12ConfigQueryRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\"\x8b\x01\n" +
	"\x13ConfigRemoveRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tagB2Z0github.com/nacos-group/nacos-sdk-proto/go/configb\x06proto3"

var (
	file_config_config_request_proto_rawDescOnce sync.Once
	file_config_config_request_proto_rawDescData []byte
)

func file_config_config_request_proto_rawDescGZIP() []byte {
	file_config_config_request_proto_rawDescOnce.Do(func() {
		file_config_config_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_config_request_proto_rawDesc), len(file_config_config_request_proto_rawDesc)))
	})
	return file_config_config_request_proto_rawDescData
}

var file_config_config_request_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_config_config_request_proto_goTypes = []any{
	(*ClientConfigMetricRequest)(nil),                   // 0: nacos.config.ClientConfigMetricRequest
	(*ClientConfigMetricRequestMetricsKey)(nil),         // 1: nacos.config.ClientConfigMetricRequestMetricsKey
	(*ConfigBatchListenRequest)(nil),                    // 2: nacos.config.ConfigBatchListenRequest
	(*ConfigBatchListenRequestConfigListenContext)(nil), // 3: nacos.config.ConfigBatchListenRequestConfigListenContext
	(*ConfigChangeClusterSyncRequest)(nil),              // 4: nacos.config.ConfigChangeClusterSyncRequest
	(*ConfigChangeNotifyRequest)(nil),                   // 5: nacos.config.ConfigChangeNotifyRequest
	(*ConfigFuzzyWatchChangeNotifyRequest)(nil),         // 6: nacos.config.ConfigFuzzyWatchChangeNotifyRequest
	(*ConfigFuzzyWatchRequest)(nil),                     // 7: nacos.config.ConfigFuzzyWatchRequest
	(*ConfigFuzzyWatchSyncRequest)(nil),                 // 8: nacos.config.ConfigFuzzyWatchSyncRequest
	(*ConfigFuzzyWatchSyncRequestContext)(nil),          // 9: nacos.config.ConfigFuzzyWatchSyncRequestContext
	(*ConfigPublishRequest)(nil),                        // 10: nacos.config.ConfigPublishRequest
	(*ConfigQueryRequest)(nil),                          // 11: nacos.config.ConfigQueryRequest
	(*ConfigRemoveRequest)(nil),                         // 12: nacos.config.ConfigRemoveRequest
	nil,                                                 // 13: nacos.config.ConfigPublishRequest.AdditionMapEntry
}
var file_config_config_request_proto_depIdxs = []int32{
	1,  // 0: nacos.config.ClientConfigMetricRequest.metricsKeys:type_name -> nacos.config.ClientConfigMetricRequestMetricsKey
	3,  // 1: nacos.config.ConfigBatchListenRequest.configListenContexts:type_name -> nacos.config.ConfigBatchListenRequestConfigListenContext
	9,  // 2: nacos.config.ConfigFuzzyWatchSyncRequest.contexts:type_name -> nacos.config.ConfigFuzzyWatchSyncRequestContext
	13, // 3: nacos.config.ConfigPublishRequest.additionMap:type_name -> nacos.config.ConfigPublishRequest.AdditionMapEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_config_config_request_proto_init() }
func file_config_config_request_proto_init() {
	if File_config_config_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_config_request_proto_rawDesc), len(file_config_config_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_config_request_proto_goTypes,
		DependencyIndexes: file_config_config_request_proto_depIdxs,
		MessageInfos:      file_config_config_request_proto_msgTypes,
	}.Build()
	File_config_config_request_proto = out.File
	file_config_config_request_proto_goTypes = nil
	file_config_config_request_proto_depIdxs = nil
}
