// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: config/config_response.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "ClientConfigMetricResponse"
// Flattened from: ClientConfigMetricResponse -> Response
type ClientConfigMetricResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ResultCode    int32                      `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                      `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                     `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Metrics       map[string]*structpb.Value `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfigMetricResponse) Reset() {
	*x = ClientConfigMetricResponse{}
	mi := &file_config_config_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfigMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigMetricResponse) ProtoMessage() {}

func (x *ClientConfigMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigMetricResponse.ProtoReflect.Descriptor instead.
func (*ClientConfigMetricResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfigMetricResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ClientConfigMetricResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ClientConfigMetricResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientConfigMetricResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientConfigMetricResponse) GetMetrics() map[string]*structpb.Value {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// metadata.type = "ConfigChangeBatchListenResponse"
// Flattened from: ConfigChangeBatchListenResponse -> Response
type ConfigChangeBatchListenResponse struct {
	state          protoimpl.MessageState                          `protogen:"open.v1"`
	ResultCode     int32                                           `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode      int32                                           `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message        string                                          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId      string                                          `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ChangedConfigs []*ConfigChangeBatchListenResponseConfigContext `protobuf:"bytes,5,rep,name=changedConfigs,proto3" json:"changedConfigs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigChangeBatchListenResponse) Reset() {
	*x = ConfigChangeBatchListenResponse{}
	mi := &file_config_config_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeBatchListenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeBatchListenResponse) ProtoMessage() {}

func (x *ConfigChangeBatchListenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeBatchListenResponse.ProtoReflect.Descriptor instead.
func (*ConfigChangeBatchListenResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigChangeBatchListenResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigChangeBatchListenResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigChangeBatchListenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigChangeBatchListenResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigChangeBatchListenResponse) GetChangedConfigs() []*ConfigChangeBatchListenResponseConfigContext {
	if x != nil {
		return x.ChangedConfigs
	}
	return nil
}

// metadata.type = "ConfigChangeBatchListenResponseConfigContext"
// Flattened from: ConfigContext
type ConfigChangeBatchListenResponseConfigContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeBatchListenResponseConfigContext) Reset() {
	*x = ConfigChangeBatchListenResponseConfigContext{}
	mi := &file_config_config_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeBatchListenResponseConfigContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeBatchListenResponseConfigContext) ProtoMessage() {}

func (x *ConfigChangeBatchListenResponseConfigContext) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeBatchListenResponseConfigContext.ProtoReflect.Descriptor instead.
func (*ConfigChangeBatchListenResponseConfigContext) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigChangeBatchListenResponseConfigContext) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigChangeBatchListenResponseConfigContext) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigChangeBatchListenResponseConfigContext) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// metadata.type = "ConfigChangeClusterSyncResponse"
// Flattened from: ConfigChangeClusterSyncResponse -> Response
type ConfigChangeClusterSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeClusterSyncResponse) Reset() {
	*x = ConfigChangeClusterSyncResponse{}
	mi := &file_config_config_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeClusterSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeClusterSyncResponse) ProtoMessage() {}

func (x *ConfigChangeClusterSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeClusterSyncResponse.ProtoReflect.Descriptor instead.
func (*ConfigChangeClusterSyncResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigChangeClusterSyncResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigChangeClusterSyncResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigChangeClusterSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigChangeClusterSyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigChangeNotifyResponse"
// Flattened from: ConfigChangeNotifyResponse -> Response
type ConfigChangeNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeNotifyResponse) Reset() {
	*x = ConfigChangeNotifyResponse{}
	mi := &file_config_config_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeNotifyResponse) ProtoMessage() {}

func (x *ConfigChangeNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeNotifyResponse.ProtoReflect.Descriptor instead.
func (*ConfigChangeNotifyResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigChangeNotifyResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigChangeNotifyResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigChangeNotifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigChangeNotifyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigFuzzyWatchChangeNotifyResponse"
// Flattened from: ConfigFuzzyWatchChangeNotifyResponse -> Response
type ConfigFuzzyWatchChangeNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFuzzyWatchChangeNotifyResponse) Reset() {
	*x = ConfigFuzzyWatchChangeNotifyResponse{}
	mi := &file_config_config_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFuzzyWatchChangeNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFuzzyWatchChangeNotifyResponse) ProtoMessage() {}

func (x *ConfigFuzzyWatchChangeNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFuzzyWatchChangeNotifyResponse.ProtoReflect.Descriptor instead.
func (*ConfigFuzzyWatchChangeNotifyResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigFuzzyWatchChangeNotifyResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigFuzzyWatchChangeNotifyResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigFuzzyWatchChangeNotifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigFuzzyWatchChangeNotifyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigFuzzyWatchResponse"
// Flattened from: ConfigFuzzyWatchResponse -> Response
type ConfigFuzzyWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFuzzyWatchResponse) Reset() {
	*x = ConfigFuzzyWatchResponse{}
	mi := &file_config_config_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFuzzyWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFuzzyWatchResponse) ProtoMessage() {}

func (x *ConfigFuzzyWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFuzzyWatchResponse.ProtoReflect.Descriptor instead.
func (*ConfigFuzzyWatchResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigFuzzyWatchResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigFuzzyWatchResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigFuzzyWatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigFuzzyWatchResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigFuzzyWatchSyncResponse"
// Flattened from: ConfigFuzzyWatchSyncResponse -> Response
type ConfigFuzzyWatchSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFuzzyWatchSyncResponse) Reset() {
	*x = ConfigFuzzyWatchSyncResponse{}
	mi := &file_config_config_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFuzzyWatchSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFuzzyWatchSyncResponse) ProtoMessage() {}

func (x *ConfigFuzzyWatchSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFuzzyWatchSyncResponse.ProtoReflect.Descriptor instead.
func (*ConfigFuzzyWatchSyncResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigFuzzyWatchSyncResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigFuzzyWatchSyncResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigFuzzyWatchSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigFuzzyWatchSyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigPublishResponse"
// Flattened from: ConfigPublishResponse -> Response
type ConfigPublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPublishResponse) Reset() {
	*x = ConfigPublishResponse{}
	mi := &file_config_config_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPublishResponse) ProtoMessage() {}

func (x *ConfigPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPublishResponse.ProtoReflect.Descriptor instead.
func (*ConfigPublishResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigPublishResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigPublishResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigPublishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPublishResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigQueryResponse"
// Flattened from: ConfigQueryResponse -> Response
type ConfigQueryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResultCode       int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode        int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId        string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Content          string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	EncryptedDataKey string                 `protobuf:"bytes,6,opt,name=encryptedDataKey,proto3" json:"encryptedDataKey,omitempty"`
	ContentType      string                 `protobuf:"bytes,7,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Md5              string                 `protobuf:"bytes,8,opt,name=md5,proto3" json:"md5,omitempty"`
	LastModified     int64                  `protobuf:"varint,9,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	IsBeta           bool                   `protobuf:"varint,10,opt,name=isBeta,proto3" json:"isBeta,omitempty"`
	Tag              string                 `protobuf:"bytes,11,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigQueryResponse) Reset() {
	*x = ConfigQueryResponse{}
	mi := &file_config_config_response_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQueryResponse) ProtoMessage() {}

func (x *ConfigQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQueryResponse.ProtoReflect.Descriptor instead.
func (*ConfigQueryResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigQueryResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigQueryResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigQueryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigQueryResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigQueryResponse) GetEncryptedDataKey() string {
	if x != nil {
		return x.EncryptedDataKey
	}
	return ""
}

func (x *ConfigQueryResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigQueryResponse) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ConfigQueryResponse) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *ConfigQueryResponse) GetIsBeta() bool {
	if x != nil {
		return x.IsBeta
	}
	return false
}

func (x *ConfigQueryResponse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// metadata.type = "ConfigRemoveResponse"
// Flattened from: ConfigRemoveResponse -> Response
type ConfigRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRemoveResponse) Reset() {
	*x = ConfigRemoveResponse{}
	mi := &file_config_config_response_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRemoveResponse) ProtoMessage() {}

func (x *ConfigRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRemoveResponse.ProtoReflect.Descriptor instead.
func (*ConfigRemoveResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigRemoveResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigRemoveResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigRemoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigRemoveResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_config_config_response_proto protoreflect.FileDescriptor

const file_config_config_response_proto_rawDesc = "" +
	"\n" +
	"\x1cconfig/config_response.proto\x12\fnacos.config\x1a\x1cgoogle/protobuf/struct.proto\"\xb7\x02\n" +
	"\x1aClientConfigMetricResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12O\n" +
	"\ametrics\x18\x05 \x03(\v25.nacos.config.ClientConfigMetricResponse.MetricsEntryR\ametrics\x1aR\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x1fConfigChangeBatchListenResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12b\n" +
	"\x0echangedConfigs\x18\x05 \x03(\v2:.nacos.config.ConfigChangeBatchListenResponseConfigContextR\x0echangedConfigs\"t\n" +
	",ConfigChangeBatchListenResponseConfigContext\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\"\x97\x01\n" +
	"\x1fConfigChangeClusterSyncResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x92\x01\n" +
	"\x1aConfigChangeNotifyResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x9c\x01\n" +
	"$ConfigFuzzyWatchChangeNotifyResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x90\x01\n" +
	"\x18ConfigFuzzyWatchResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x94\x01\n" +
	"\x1cConfigFuzzyWatchSyncResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x8d\x01\n" +
	"\x15ConfigPublishResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\xd3\x02\n" +
	"\x13ConfigQueryResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12*\n" +
	"\x10encryptedDataKey\x18\x06 \x01(\tR\x10encryptedDataKey\x12 \n" +
	"\vcontentType\x18\a \x01(\tR\vcontentType\x12\x10\n" +
	"\x03md5\x18\b \x01(\tR\x03md5\x12\"\n" +
	"\flastModified\x18\t \x01(\x03R\flastModified\x12\x16\n" +
	"\x06isBeta\x18\n" +
	" \x01(\bR\x06isBeta\x12\x10\n" +
	"\x03tag\x18\v \x01(\tR\x03tag\"\x8c\x01\n" +
	"\x14ConfigRemoveResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestIdB2Z0github.com/nacos-group/nacos-sdk-proto/go/configb\x06proto3"

var (
	file_config_config_response_proto_rawDescOnce sync.Once
	file_config_config_response_proto_rawDescData []byte
)

func file_config_config_response_proto_rawDescGZIP() []byte {
	file_config_config_response_proto_rawDescOnce.Do(func() {
		file_config_config_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_config_response_proto_rawDesc), len(file_config_config_response_proto_rawDesc)))
	})
	return file_config_config_response_proto_rawDescData
}

var file_config_config_response_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_config_config_response_proto_goTypes = []any{
	(*ClientConfigMetricResponse)(nil),                   // 0: nacos.config.ClientConfigMetricResponse
	(*ConfigChangeBatchListenResponse)(nil),              // 1: nacos.config.ConfigChangeBatchListenResponse
	(*ConfigChangeBatchListenResponseConfigContext)(nil), // 2: nacos.config.ConfigChangeBatchListenResponseConfigContext
	(*ConfigChangeClusterSyncResponse)(nil),              // 3: nacos.config.ConfigChangeClusterSyncResponse
	(*ConfigChangeNotifyResponse)(nil),                   // 4: nacos.config.ConfigChangeNotifyResponse
	(*ConfigFuzzyWatchChangeNotifyResponse)(nil),         // 5: nacos.config.ConfigFuzzyWatchChangeNotifyResponse
	(*ConfigFuzzyWatchResponse)(nil),                     // 6: nacos.config.ConfigFuzzyWatchResponse
	(*ConfigFuzzyWatchSyncResponse)(nil),                 // 7: nacos.config.ConfigFuzzyWatchSyncResponse
	(*ConfigPublishResponse)(nil),                        // 8: nacos.config.ConfigPublishResponse
	(*ConfigQueryResponse)(nil),                          // 9: nacos.config.ConfigQueryResponse
	(*ConfigRemoveResponse)(nil),                         // 10: nacos.config.ConfigRemoveResponse
	nil,                                                  // 11: nacos.config.ClientConfigMetricResponse.MetricsEntry
	(*structpb.Value)(nil),                               // 12: google.protobuf.Value
}
var file_config_config_response_proto_depIdxs = []int32{
	11, // 0: nacos.config.ClientConfigMetricResponse.metrics:type_name -> nacos.config.ClientConfigMetricResponse.MetricsEntry
	2,  // 1: nacos.config.ConfigChangeBatchListenResponse.changedConfigs:type_name -> nacos.config.ConfigChangeBatchListenResponseConfigContext
	12, // 2: nacos.config.ClientConfigMetricResponse.MetricsEntry.value:type_name -> google.protobuf.Value
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_config_config_response_proto_init() }
func file_config_config_response_proto_init() {
	if File_config_config_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_config_response_proto_rawDesc), len(file_config_config_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_config_response_proto_goTypes,
		DependencyIndexes: file_config_config_response_proto_depIdxs,
		MessageInfos:      file_config_config_response_proto_msgTypes,
	}.Build()
	File_config_config_response_proto = out.File
	file_config_config_response_proto_goTypes = nil
	file_config_config_response_proto_depIdxs = nil
}
