// Auto-generated by proto-generator. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: naming/naming_response.proto

package naming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "BatchInstanceResponse"
// Flattened from: BatchInstanceResponse -> InstanceResponse -> Response
type BatchInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInstanceResponse) Reset() {
	*x = BatchInstanceResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInstanceResponse) ProtoMessage() {}

func (x *BatchInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInstanceResponse.ProtoReflect.Descriptor instead.
func (*BatchInstanceResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{0}
}

func (x *BatchInstanceResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *BatchInstanceResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *BatchInstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchInstanceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BatchInstanceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// metadata.type = "InstanceResponse"
// Flattened from: InstanceResponse -> Response
type InstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceResponse) Reset() {
	*x = InstanceResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceResponse) ProtoMessage() {}

func (x *InstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceResponse.ProtoReflect.Descriptor instead.
func (*InstanceResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *InstanceResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *InstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstanceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InstanceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// metadata.type = "NamingFuzzyWatchChangeNotifyResponse"
// Flattened from: NamingFuzzyWatchChangeNotifyResponse -> Response
type NamingFuzzyWatchChangeNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamingFuzzyWatchChangeNotifyResponse) Reset() {
	*x = NamingFuzzyWatchChangeNotifyResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamingFuzzyWatchChangeNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamingFuzzyWatchChangeNotifyResponse) ProtoMessage() {}

func (x *NamingFuzzyWatchChangeNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamingFuzzyWatchChangeNotifyResponse.ProtoReflect.Descriptor instead.
func (*NamingFuzzyWatchChangeNotifyResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{2}
}

func (x *NamingFuzzyWatchChangeNotifyResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *NamingFuzzyWatchChangeNotifyResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *NamingFuzzyWatchChangeNotifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NamingFuzzyWatchChangeNotifyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "NamingFuzzyWatchResponse"
// Flattened from: NamingFuzzyWatchResponse -> Response
type NamingFuzzyWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamingFuzzyWatchResponse) Reset() {
	*x = NamingFuzzyWatchResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamingFuzzyWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamingFuzzyWatchResponse) ProtoMessage() {}

func (x *NamingFuzzyWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamingFuzzyWatchResponse.ProtoReflect.Descriptor instead.
func (*NamingFuzzyWatchResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{3}
}

func (x *NamingFuzzyWatchResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *NamingFuzzyWatchResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *NamingFuzzyWatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NamingFuzzyWatchResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "NamingFuzzyWatchSyncResponse"
// Flattened from: NamingFuzzyWatchSyncResponse -> Response
type NamingFuzzyWatchSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamingFuzzyWatchSyncResponse) Reset() {
	*x = NamingFuzzyWatchSyncResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamingFuzzyWatchSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamingFuzzyWatchSyncResponse) ProtoMessage() {}

func (x *NamingFuzzyWatchSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamingFuzzyWatchSyncResponse.ProtoReflect.Descriptor instead.
func (*NamingFuzzyWatchSyncResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{4}
}

func (x *NamingFuzzyWatchSyncResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *NamingFuzzyWatchSyncResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *NamingFuzzyWatchSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NamingFuzzyWatchSyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "NotifySubscriberResponse"
// Flattened from: NotifySubscriberResponse -> Response
type NotifySubscriberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifySubscriberResponse) Reset() {
	*x = NotifySubscriberResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifySubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifySubscriberResponse) ProtoMessage() {}

func (x *NotifySubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifySubscriberResponse.ProtoReflect.Descriptor instead.
func (*NotifySubscriberResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{5}
}

func (x *NotifySubscriberResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *NotifySubscriberResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *NotifySubscriberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotifySubscriberResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "QueryServiceResponse"
// Flattened from: QueryServiceResponse -> Response
type QueryServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ServiceInfo   *ServiceInfo           `protobuf:"bytes,5,opt,name=serviceInfo,proto3" json:"serviceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryServiceResponse) Reset() {
	*x = QueryServiceResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServiceResponse) ProtoMessage() {}

func (x *QueryServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServiceResponse.ProtoReflect.Descriptor instead.
func (*QueryServiceResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{6}
}

func (x *QueryServiceResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *QueryServiceResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *QueryServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryServiceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryServiceResponse) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

// metadata.type = "ServiceListResponse"
// Flattened from: ServiceListResponse -> Response
type ServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	ServiceNames  []string               `protobuf:"bytes,6,rep,name=serviceNames,proto3" json:"serviceNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListResponse) Reset() {
	*x = ServiceListResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListResponse) ProtoMessage() {}

func (x *ServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListResponse.ProtoReflect.Descriptor instead.
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceListResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ServiceListResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ServiceListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceListResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ServiceListResponse) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

// metadata.type = "SubscribeServiceResponse"
// Flattened from: SubscribeServiceResponse -> Response
type SubscribeServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ServiceInfo   *ServiceInfo           `protobuf:"bytes,5,opt,name=serviceInfo,proto3" json:"serviceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServiceResponse) Reset() {
	*x = SubscribeServiceResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServiceResponse) ProtoMessage() {}

func (x *SubscribeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServiceResponse.ProtoReflect.Descriptor instead.
func (*SubscribeServiceResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeServiceResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *SubscribeServiceResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SubscribeServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubscribeServiceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeServiceResponse) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

var File_naming_naming_response_proto protoreflect.FileDescriptor

const file_naming_naming_response_proto_rawDesc = "" +
	"\n" +
	"\x1cnaming/naming_response.proto\x12\fnacos.naming\x1a\x18naming/serviceinfo.proto\"\xa1\x01\n" +
	"\x15BatchInstanceResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\x9c\x01\n" +
	"\x10InstanceResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\x9c\x01\n" +
	"$NamingFuzzyWatchChangeNotifyResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x90\x01\n" +
	"\x18NamingFuzzyWatchResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x94\x01\n" +
	"\x1cNamingFuzzyWatchSyncResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x90\x01\n" +
	"\x18NotifySubscriberResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\xc9\x01\n" +
	"\x14QueryServiceResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12;\n" +
	"\vserviceInfo\x18\x05 \x01(\v2\x19.nacos.naming.ServiceInfoR\vserviceInfo\"\xc5\x01\n" +
	"\x13ServiceListResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\"\n" +
	"\fserviceNames\x18\x06 \x03(\tR\fserviceNames\"\xcd\x01\n" +
	"\x18SubscribeServiceResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12;\n" +
	"\vserviceInfo\x18\x05 \x01(\v2\x19.nacos.naming.ServiceInfoR\vserviceInfoB2Z0github.com/nacos-group/nacos-sdk-proto/go/namingb\x06proto3"

var (
	file_naming_naming_response_proto_rawDescOnce sync.Once
	file_naming_naming_response_proto_rawDescData []byte
)

func file_naming_naming_response_proto_rawDescGZIP() []byte {
	file_naming_naming_response_proto_rawDescOnce.Do(func() {
		file_naming_naming_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_naming_naming_response_proto_rawDesc), len(file_naming_naming_response_proto_rawDesc)))
	})
	return file_naming_naming_response_proto_rawDescData
}

var file_naming_naming_response_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_naming_naming_response_proto_goTypes = []any{
	(*BatchInstanceResponse)(nil),                // 0: nacos.naming.BatchInstanceResponse
	(*InstanceResponse)(nil),                     // 1: nacos.naming.InstanceResponse
	(*NamingFuzzyWatchChangeNotifyResponse)(nil), // 2: nacos.naming.NamingFuzzyWatchChangeNotifyResponse
	(*NamingFuzzyWatchResponse)(nil),             // 3: nacos.naming.NamingFuzzyWatchResponse
	(*NamingFuzzyWatchSyncResponse)(nil),         // 4: nacos.naming.NamingFuzzyWatchSyncResponse
	(*NotifySubscriberResponse)(nil),             // 5: nacos.naming.NotifySubscriberResponse
	(*QueryServiceResponse)(nil),                 // 6: nacos.naming.QueryServiceResponse
	(*ServiceListResponse)(nil),                  // 7: nacos.naming.ServiceListResponse
	(*SubscribeServiceResponse)(nil),             // 8: nacos.naming.SubscribeServiceResponse
	(*ServiceInfo)(nil),                          // 9: nacos.naming.ServiceInfo
}
var file_naming_naming_response_proto_depIdxs = []int32{
	9, // 0: nacos.naming.QueryServiceResponse.serviceInfo:type_name -> nacos.naming.ServiceInfo
	9, // 1: nacos.naming.SubscribeServiceResponse.serviceInfo:type_name -> nacos.naming.ServiceInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_naming_naming_response_proto_init() }
func file_naming_naming_response_proto_init() {
	if File_naming_naming_response_proto != nil {
		return
	}
	file_naming_serviceinfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_naming_naming_response_proto_rawDesc), len(file_naming_naming_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_naming_naming_response_proto_goTypes,
		DependencyIndexes: file_naming_naming_response_proto_depIdxs,
		MessageInfos:      file_naming_naming_response_proto_msgTypes,
	}.Build()
	File_naming_naming_response_proto = out.File
	file_naming_naming_response_proto_goTypes = nil
	file_naming_naming_response_proto_depIdxs = nil
}
