// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.3
// source: lock/lock.proto

/* eslint-disable */

/** Auto-generated by proto-generator. DO NOT EDIT. */

/**
 * metadata.type = "LockNotificationRequest"
 * Flattened from: LockNotificationRequest -> ServerRequest -> Request
 */
export interface LockNotificationRequest {
  requestId: string;
  lockKey: string;
  lockType: string;
  owner: string;
  notificationType: string;
}

/**
 * metadata.type = "LockNotificationResponse"
 * Flattened from: LockNotificationResponse -> Response
 */
export interface LockNotificationResponse {
  resultCode: number;
  errorCode: number;
  message: string;
  requestId: string;
}

/**
 * metadata.type = "LockOperationRequest"
 * Flattened from: LockOperationRequest -> AbstractLockRequest -> Request
 */
export interface LockOperationRequest {
  requestId: string;
  lockInstance: LockInstance | undefined;
  lockOperationEnum: string;
}

/**
 * metadata.type = "LockInstance"
 * Flattened from: LockInstance
 */
export interface LockInstance {
  key: string;
  expiredTime: number;
  params: { [key: string]: any | undefined };
  lockType: string;
  owner: string;
  waitTime: number;
  waiterRetry: boolean;
}

export interface LockInstance_ParamsEntry {
  key: string;
  value: any | undefined;
}

/**
 * metadata.type = "LockOperationResponse"
 * Flattened from: LockOperationResponse -> Response
 */
export interface LockOperationResponse {
  resultCode: number;
  errorCode: number;
  message: string;
  requestId: string;
  result: any | undefined;
  lockResult: LockResult | undefined;
}

/**
 * metadata.type = "LockResult"
 * Flattened from: LockResult
 */
export interface LockResult {
  success: boolean;
  reentrantCount: number;
  waitPosition: number;
  errorMessage: string;
}

function createBaseLockNotificationRequest(): LockNotificationRequest {
  return { requestId: "", lockKey: "", lockType: "", owner: "", notificationType: "" };
}

export const LockNotificationRequest: MessageFns<LockNotificationRequest> = {
  fromJSON(object: any): LockNotificationRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      lockKey: isSet(object.lockKey) ? globalThis.String(object.lockKey) : "",
      lockType: isSet(object.lockType) ? globalThis.String(object.lockType) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      notificationType: isSet(object.notificationType) ? globalThis.String(object.notificationType) : "",
    };
  },

  toJSON(message: LockNotificationRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.lockKey !== "") {
      obj.lockKey = message.lockKey;
    }
    if (message.lockType !== "") {
      obj.lockType = message.lockType;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.notificationType !== "") {
      obj.notificationType = message.notificationType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockNotificationRequest>, I>>(base?: I): LockNotificationRequest {
    return LockNotificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockNotificationRequest>, I>>(object: I): LockNotificationRequest {
    const message = createBaseLockNotificationRequest();
    message.requestId = object.requestId ?? "";
    message.lockKey = object.lockKey ?? "";
    message.lockType = object.lockType ?? "";
    message.owner = object.owner ?? "";
    message.notificationType = object.notificationType ?? "";
    return message;
  },
};

function createBaseLockNotificationResponse(): LockNotificationResponse {
  return { resultCode: 0, errorCode: 0, message: "", requestId: "" };
}

export const LockNotificationResponse: MessageFns<LockNotificationResponse> = {
  fromJSON(object: any): LockNotificationResponse {
    return {
      resultCode: isSet(object.resultCode) ? globalThis.Number(object.resultCode) : 0,
      errorCode: isSet(object.errorCode) ? globalThis.Number(object.errorCode) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
    };
  },

  toJSON(message: LockNotificationResponse): unknown {
    const obj: any = {};
    if (message.resultCode !== 0) {
      obj.resultCode = Math.round(message.resultCode);
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockNotificationResponse>, I>>(base?: I): LockNotificationResponse {
    return LockNotificationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockNotificationResponse>, I>>(object: I): LockNotificationResponse {
    const message = createBaseLockNotificationResponse();
    message.resultCode = object.resultCode ?? 0;
    message.errorCode = object.errorCode ?? 0;
    message.message = object.message ?? "";
    message.requestId = object.requestId ?? "";
    return message;
  },
};

function createBaseLockOperationRequest(): LockOperationRequest {
  return { requestId: "", lockInstance: undefined, lockOperationEnum: "" };
}

export const LockOperationRequest: MessageFns<LockOperationRequest> = {
  fromJSON(object: any): LockOperationRequest {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      lockInstance: isSet(object.lockInstance) ? LockInstance.fromJSON(object.lockInstance) : undefined,
      lockOperationEnum: isSet(object.lockOperationEnum) ? globalThis.String(object.lockOperationEnum) : "",
    };
  },

  toJSON(message: LockOperationRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.lockInstance !== undefined) {
      obj.lockInstance = LockInstance.toJSON(message.lockInstance);
    }
    if (message.lockOperationEnum !== "") {
      obj.lockOperationEnum = message.lockOperationEnum;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockOperationRequest>, I>>(base?: I): LockOperationRequest {
    return LockOperationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockOperationRequest>, I>>(object: I): LockOperationRequest {
    const message = createBaseLockOperationRequest();
    message.requestId = object.requestId ?? "";
    message.lockInstance = (object.lockInstance !== undefined && object.lockInstance !== null)
      ? LockInstance.fromPartial(object.lockInstance)
      : undefined;
    message.lockOperationEnum = object.lockOperationEnum ?? "";
    return message;
  },
};

function createBaseLockInstance(): LockInstance {
  return { key: "", expiredTime: 0, params: {}, lockType: "", owner: "", waitTime: 0, waiterRetry: false };
}

export const LockInstance: MessageFns<LockInstance> = {
  fromJSON(object: any): LockInstance {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      expiredTime: isSet(object.expiredTime) ? globalThis.Number(object.expiredTime) : 0,
      params: isObject(object.params)
        ? (globalThis.Object.entries(object.params) as [string, any][]).reduce(
          (acc: { [key: string]: any | undefined }, [key, value]: [string, any]) => {
            acc[key] = value as any | undefined;
            return acc;
          },
          {},
        )
        : {},
      lockType: isSet(object.lockType) ? globalThis.String(object.lockType) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      waitTime: isSet(object.waitTime) ? globalThis.Number(object.waitTime) : 0,
      waiterRetry: isSet(object.waiterRetry) ? globalThis.Boolean(object.waiterRetry) : false,
    };
  },

  toJSON(message: LockInstance): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.expiredTime !== 0) {
      obj.expiredTime = Math.round(message.expiredTime);
    }
    if (message.params) {
      const entries = globalThis.Object.entries(message.params) as [string, any | undefined][];
      if (entries.length > 0) {
        obj.params = {};
        entries.forEach(([k, v]) => {
          obj.params[k] = v;
        });
      }
    }
    if (message.lockType !== "") {
      obj.lockType = message.lockType;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.waitTime !== 0) {
      obj.waitTime = Math.round(message.waitTime);
    }
    if (message.waiterRetry !== false) {
      obj.waiterRetry = message.waiterRetry;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockInstance>, I>>(base?: I): LockInstance {
    return LockInstance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockInstance>, I>>(object: I): LockInstance {
    const message = createBaseLockInstance();
    message.key = object.key ?? "";
    message.expiredTime = object.expiredTime ?? 0;
    message.params = (globalThis.Object.entries(object.params ?? {}) as [string, any | undefined][]).reduce(
      (acc: { [key: string]: any | undefined }, [key, value]: [string, any | undefined]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.lockType = object.lockType ?? "";
    message.owner = object.owner ?? "";
    message.waitTime = object.waitTime ?? 0;
    message.waiterRetry = object.waiterRetry ?? false;
    return message;
  },
};

function createBaseLockInstance_ParamsEntry(): LockInstance_ParamsEntry {
  return { key: "", value: undefined };
}

export const LockInstance_ParamsEntry: MessageFns<LockInstance_ParamsEntry> = {
  fromJSON(object: any): LockInstance_ParamsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: LockInstance_ParamsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockInstance_ParamsEntry>, I>>(base?: I): LockInstance_ParamsEntry {
    return LockInstance_ParamsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockInstance_ParamsEntry>, I>>(object: I): LockInstance_ParamsEntry {
    const message = createBaseLockInstance_ParamsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseLockOperationResponse(): LockOperationResponse {
  return { resultCode: 0, errorCode: 0, message: "", requestId: "", result: undefined, lockResult: undefined };
}

export const LockOperationResponse: MessageFns<LockOperationResponse> = {
  fromJSON(object: any): LockOperationResponse {
    return {
      resultCode: isSet(object.resultCode) ? globalThis.Number(object.resultCode) : 0,
      errorCode: isSet(object.errorCode) ? globalThis.Number(object.errorCode) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      result: isSet(object?.result) ? object.result : undefined,
      lockResult: isSet(object.lockResult) ? LockResult.fromJSON(object.lockResult) : undefined,
    };
  },

  toJSON(message: LockOperationResponse): unknown {
    const obj: any = {};
    if (message.resultCode !== 0) {
      obj.resultCode = Math.round(message.resultCode);
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.result !== undefined) {
      obj.result = message.result;
    }
    if (message.lockResult !== undefined) {
      obj.lockResult = LockResult.toJSON(message.lockResult);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockOperationResponse>, I>>(base?: I): LockOperationResponse {
    return LockOperationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockOperationResponse>, I>>(object: I): LockOperationResponse {
    const message = createBaseLockOperationResponse();
    message.resultCode = object.resultCode ?? 0;
    message.errorCode = object.errorCode ?? 0;
    message.message = object.message ?? "";
    message.requestId = object.requestId ?? "";
    message.result = object.result ?? undefined;
    message.lockResult = (object.lockResult !== undefined && object.lockResult !== null)
      ? LockResult.fromPartial(object.lockResult)
      : undefined;
    return message;
  },
};

function createBaseLockResult(): LockResult {
  return { success: false, reentrantCount: 0, waitPosition: 0, errorMessage: "" };
}

export const LockResult: MessageFns<LockResult> = {
  fromJSON(object: any): LockResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      reentrantCount: isSet(object.reentrantCount) ? globalThis.Number(object.reentrantCount) : 0,
      waitPosition: isSet(object.waitPosition) ? globalThis.Number(object.waitPosition) : 0,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "",
    };
  },

  toJSON(message: LockResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.reentrantCount !== 0) {
      obj.reentrantCount = Math.round(message.reentrantCount);
    }
    if (message.waitPosition !== 0) {
      obj.waitPosition = Math.round(message.waitPosition);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockResult>, I>>(base?: I): LockResult {
    return LockResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockResult>, I>>(object: I): LockResult {
    const message = createBaseLockResult();
    message.success = object.success ?? false;
    message.reentrantCount = object.reentrantCount ?? 0;
    message.waitPosition = object.waitPosition ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
